#ifndef FABLE_ENGINE_C3DMESHFILEXBOUNDINGSPHERECHUNK_H
#define FABLE_ENGINE_C3DMESHFILEXBOUNDINGSPHERECHUNK_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof C3DMeshFileXBoundingSphereChunk = 0x20.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct C3DMeshFileXBoundingSphereChunk {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char Center[0xc];                               // +0x10 C3DVector
    float         Radius;                                    // +0x1c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(C3DMeshFileXBoundingSphereChunk) == 0x20);
FABLE_STATIC_ASSERT(offsetof(C3DMeshFileXBoundingSphereChunk, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(C3DMeshFileXBoundingSphereChunk, Center) == 0x10);
FABLE_STATIC_ASSERT(offsetof(C3DMeshFileXBoundingSphereChunk, Radius) == 0x1c);

#endif // FABLE_ENGINE_C3DMESHFILEXBOUNDINGSPHERECHUNK_H
