#ifndef FABLE_ENGINE_CAISTATEGROUP_CREATUREUSECOVERBASE_H
#define FABLE_ENGINE_CAISTATEGROUP_CREATUREUSECOVERBASE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CAIStateGroup_CreatureUseCoverBase = 0x50.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CAIStateGroup_CreatureUseCoverBase {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    bool          HasDiveAnim;                               // +0x1c
    bool          HasJumpOutAnims;                           // +0x1d
    bool          TimingCritical;                            // +0x1e
    unsigned char PCoverThing[0x8];                          // +0x1f CIntelligentPointer<CThing>
    unsigned char _pad_0x27[0x1];                            // +0x27
    unsigned char CoverList[0x10];                           // +0x28 vector<CIntelligentPointer<CThing>,std::allocator<CIntelligentPointer<CThing>_>_>
    bool          FailedToFindCover;                         // +0x38
    unsigned char _pad_0x39[0x3];                            // +0x39
    long          FailedTime;                                // +0x3c
    float         FailedToFindCoverAt_X;                     // +0x40 C3DVector::X
    float         FailedToFindCoverAt_Y;                     // +0x44 C3DVector::Y
    float         FailedToFindCoverAt_Z;                     // +0x48 C3DVector::Z
    long          ValidPositionsFound;                       // +0x4c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CAIStateGroup_CreatureUseCoverBase) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, HasDiveAnim) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, HasJumpOutAnims) == 0x1d);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, TimingCritical) == 0x1e);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, PCoverThing) == 0x1f);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, CoverList) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, FailedToFindCover) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, FailedTime) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, FailedToFindCoverAt_X) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, FailedToFindCoverAt_Y) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, FailedToFindCoverAt_Z) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_CreatureUseCoverBase, ValidPositionsFound) == 0x4c);

#endif // FABLE_ENGINE_CAISTATEGROUP_CREATUREUSECOVERBASE_H
