#ifndef FABLE_ENGINE_CAISTATEGROUP_SUMMONERLIGHTNINGATTACK_H
#define FABLE_ENGINE_CAISTATEGROUP_SUMMONERLIGHTNINGATTACK_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CAIStateGroup_SummonerLightningAttack = 0x24.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CAIStateGroup_SummonerLightningAttack {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char PTarget[0x8];                              // +0x14 CIntelligentPointer<CThing>
    unsigned char PDef[0x4];                                 // +0x1c CDefPointer<CSummonerDef_const_>
    long          NextFrameForPreemptiveUse;                 // +0x20
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CAIStateGroup_SummonerLightningAttack) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_SummonerLightningAttack, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_SummonerLightningAttack, PTarget) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_SummonerLightningAttack, PDef) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CAIStateGroup_SummonerLightningAttack, NextFrameForPreemptiveUse) == 0x20);

#endif // FABLE_ENGINE_CAISTATEGROUP_SUMMONERLIGHTNINGATTACK_H
