#ifndef FABLE_ENGINE_CANIMCOMPONENTCOMBATFLOURISHTARGETOFFSET_H
#define FABLE_ENGINE_CANIMCOMPONENTCOMBATFLOURISHTARGETOFFSET_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CAnimComponentCombatFlourishTargetOffset = 0x11.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing; PINNED by 1 retyped file(s) despite conflicts.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CAnimComponentCombatFlourishTargetOffset {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _base_0x04[0x4];                           // +0x04 flattened base-class subobject(s)
    bool          TargetOffset;                              // +0x08
    float         TargetOffsetVector_X;                      // +0x09 C2DVector::X
    float         TargetOffsetVector_Y;                      // +0x0d C2DVector::Y
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CAnimComponentCombatFlourishTargetOffset) == 0x11);
FABLE_STATIC_ASSERT(offsetof(CAnimComponentCombatFlourishTargetOffset, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CAnimComponentCombatFlourishTargetOffset, TargetOffset) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CAnimComponentCombatFlourishTargetOffset, TargetOffsetVector_X) == 0x9);
FABLE_STATIC_ASSERT(offsetof(CAnimComponentCombatFlourishTargetOffset, TargetOffsetVector_Y) == 0xd);

#endif // FABLE_ENGINE_CANIMCOMPONENTCOMBATFLOURISHTARGETOFFSET_H
