#ifndef FABLE_ENGINE_CBULLETTIMEMANAGER_H
#define FABLE_ENGINE_CBULLETTIMEMANAGER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CBulletTimeManager = 0x20.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CPlayerManager;
struct CWorld;

#pragma pack(push, 1)
struct CBulletTimeManager {
    unsigned char   BulletTimeInfoMap[0x10];                 // +0x00 map<void_*,CBulletTimeManager::CBulletTimeInfo,std::less<void_*>,std::allocator<std::pair<void_*_const,CBulletTimeManager::CBulletTimeInfo>_>_>
    bool            Override;                                // +0x10
    bool            UseDefaultMultiplier;                    // +0x11
    unsigned char   _pad_0x12[0x2];                          // +0x12
    long            LastStrikeActionTick;                    // +0x14
    CWorld*         World;                                   // +0x18
    CPlayerManager* PlayerManager;                           // +0x1c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CBulletTimeManager) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, BulletTimeInfoMap) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, Override) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, UseDefaultMultiplier) == 0x11);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, LastStrikeActionTick) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, World) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CBulletTimeManager, PlayerManager) == 0x1c);

#endif // FABLE_ENGINE_CBULLETTIMEMANAGER_H
