#ifndef FABLE_ENGINE_CCOMBATABILITYSTRAFEDEF_H
#define FABLE_ENGINE_CCOMBATABILITYSTRAFEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CCombatAbilityStrafeDef = 0x44.
// Retail evidence: 2 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CCombatAbilityStrafeDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char CombatAbility[0x1c];                       // +0x28 CCombatAbilityStrafingData
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CCombatAbilityStrafeDef) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CCombatAbilityStrafeDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CCombatAbilityStrafeDef, CombatAbility) == 0x28);

#endif // FABLE_ENGINE_CCOMBATABILITYSTRAFEDEF_H
