#ifndef FABLE_ENGINE_CDISKFILEWIN32_H
#define FABLE_ENGINE_CDISKFILEWIN32_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CDiskFileWin32 = 0x1c.
// Retail evidence: 4 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CDiskFileWin32 {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char AccessType[0x4];                           // +0x04 FileAccessType
    long          Position;                                  // +0x08
    long          Length;                                    // +0x0c
    void*         WinFileHandle;                             // +0x10
    bool          Opened;                                    // +0x14
    unsigned char _pad_0x15[0x3];                            // +0x15
    unsigned char Pathname[0x4];                             // +0x18 CWideString
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CDiskFileWin32) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, AccessType) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, Position) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, Length) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, WinFileHandle) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, Opened) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CDiskFileWin32, Pathname) == 0x18);

#endif // FABLE_ENGINE_CDISKFILEWIN32_H
