#ifndef FABLE_ENGINE_CDOORDEF_H
#define FABLE_ENGINE_CDOORDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CDoorDef = 0x3c.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CDoorDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char TriggerType[0x4];                          // +0x28 EDoorTriggerType
    float         TriggerRadius;                             // +0x2c
    long          OpenCollisionMesh;                         // +0x30
    long          ClosedCollisionMesh;                       // +0x34
    bool          PostVandalismCrimeIfDestroyed;             // +0x38
    bool          LockPickable;                              // +0x39
    bool          PreventLockingByOwner;                     // +0x3a
    unsigned char _pad_0x3b[0x1];                            // +0x3b
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CDoorDef) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, TriggerType) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, TriggerRadius) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, OpenCollisionMesh) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, ClosedCollisionMesh) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, PostVandalismCrimeIfDestroyed) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, LockPickable) == 0x39);
FABLE_STATIC_ASSERT(offsetof(CDoorDef, PreventLockingByOwner) == 0x3a);

#endif // FABLE_ENGINE_CDOORDEF_H
