#ifndef FABLE_ENGINE_CDRIVEMANAGER_H
#define FABLE_ENGINE_CDRIVEMANAGER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CDriveManager = 0x8.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CSystemManager;

#pragma pack(push, 1)
struct CDriveManager {
    void*           __vftable;                               // +0x00 vptr, or first dword of a flattened base subobject
    CSystemManager* SystemManager;                           // +0x04
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CDriveManager) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CDriveManager, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CDriveManager, SystemManager) == 0x4);

#endif // FABLE_ENGINE_CDRIVEMANAGER_H
