#ifndef FABLE_ENGINE_CENGINEPRIMITIVERENDERER_H
#define FABLE_ENGINE_CENGINEPRIMITIVERENDERER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CEnginePrimitiveRenderer = 0x358.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CCPPointerInfo;
struct CEngineClothRenderer;
struct CEnginePrimitiveChangerManager;
struct CEnginePrimitiveGroupManager;
struct CEnginePrimitiveManagerAnimatedMeshes;
struct CEnginePrimitiveManagerDecal;
struct CEnginePrimitiveManagerFlareSprites;
struct CEnginePrimitiveManagerGameMeshes;
struct CEnginePrimitiveManagerLines;
struct CEnginePrimitiveManagerParticleDecalGroup;
struct CEnginePrimitiveManagerParticleGroup;
struct CEnginePrimitiveManagerParticleLineGroup;
struct CEnginePrimitiveManagerParticleMeshGroup;
struct CEnginePrimitiveManagerParticleSpriteGroup;
struct CEnginePrimitiveManagerParticleSpriteTrailGroup;
struct CEnginePrimitiveManagerRepeatedStaticMeshes;
struct CEnginePrimitiveManagerRepeatedZSprites;
struct CEnginePrimitiveManagerSpriteTrails;
struct CEnginePrimitiveManagerSprites;
struct CEnginePrimitiveManagerStaticMeshes;
struct CEnginePrimitiveManagerText;
struct CEnginePrimitiveManagerWeaponTrails;
struct CEnginePrimitiveManagerWeatherMask;
struct CEnginePrimitiveOcclusionGroupManager;

#pragma pack(push, 1)
struct CEnginePrimitiveRenderer {
    void*                                            __vftable; // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char                                    _pad_0x04[0x4]; // +0x04
    unsigned char                                    _pad_0x08[0x4]; // +0x08
    unsigned char                                    _pad_0x0c[0x4]; // +0x0c
    unsigned char                                    _pad_0x10[0x4]; // +0x10
    unsigned char                                    _pad_0x14[0x4]; // +0x14
    unsigned char                                    _pad_0x18[0x4]; // +0x18
    unsigned char                                    _pad_0x1c[0x4]; // +0x1c
    unsigned char                                    _pad_0x20[0x4]; // +0x20
    unsigned char                                    _pad_0x24[0x4]; // +0x24
    unsigned char                                    _pad_0x28[0x4]; // +0x28
    unsigned char                                    _pad_0x2c[0x4]; // +0x2c
    unsigned char                                    _pad_0x30[0x4]; // +0x30
    unsigned char                                    _pad_0x34[0x4]; // +0x34
    unsigned char                                    _pad_0x38[0x4]; // +0x38
    unsigned char                                    _pad_0x3c[0x4]; // +0x3c
    unsigned char                                    _pad_0x40[0x4]; // +0x40
    unsigned char                                    _pad_0x44[0x4]; // +0x44
    unsigned char                                    _pad_0x48[0x4]; // +0x48
    unsigned char                                    _pad_0x4c[0x4]; // +0x4c
    unsigned char                                    _pad_0x50[0x4]; // +0x50
    unsigned char                                    _pad_0x54[0x4]; // +0x54
    unsigned char                                    _pad_0x58[0x4]; // +0x58
    unsigned char                                    _pad_0x5c[0x4]; // +0x5c
    unsigned char                                    _pad_0x60[0x4]; // +0x60
    unsigned char                                    _pad_0x64[0x4]; // +0x64
    unsigned char                                    _pad_0x68[0x4]; // +0x68
    unsigned char                                    _pad_0x6c[0x4]; // +0x6c
    unsigned char                                    _pad_0x70[0x4]; // +0x70
    unsigned char                                    _pad_0x74[0x4]; // +0x74
    unsigned char                                    _pad_0x78[0x4]; // +0x78
    unsigned char                                    _pad_0x7c[0x4]; // +0x7c
    unsigned char                                    _pad_0x80[0x4]; // +0x80
    unsigned char                                    _pad_0x84[0x4]; // +0x84
    unsigned char                                    _pad_0x88[0x4]; // +0x88
    unsigned char                                    _pad_0x8c[0x4]; // +0x8c
    unsigned char                                    _pad_0x90[0x4]; // +0x90
    unsigned char                                    _pad_0x94[0x4]; // +0x94
    unsigned char                                    _pad_0x98[0x4]; // +0x98
    unsigned char                                    _pad_0x9c[0x4]; // +0x9c
    unsigned char                                    _pad_0xa0[0x4]; // +0xa0
    unsigned char                                    _pad_0xa4[0x4]; // +0xa4
    unsigned char                                    _pad_0xa8[0x4]; // +0xa8
    unsigned char                                    _pad_0xac[0x4]; // +0xac
    unsigned char                                    _pad_0xb0[0x4]; // +0xb0
    unsigned char                                    _pad_0xb4[0x4]; // +0xb4
    unsigned char                                    _pad_0xb8[0x4]; // +0xb8
    unsigned char                                    _pad_0xbc[0x4]; // +0xbc
    unsigned char                                    _pad_0xc0[0x4]; // +0xc0
    unsigned char                                    _pad_0xc4[0x4]; // +0xc4
    unsigned char                                    _pad_0xc8[0x4]; // +0xc8
    unsigned char                                    _pad_0xcc[0x4]; // +0xcc
    unsigned char                                    _pad_0xd0[0x4]; // +0xd0
    unsigned char                                    _pad_0xd4[0x4]; // +0xd4
    unsigned char                                    _pad_0xd8[0x4]; // +0xd8
    unsigned char                                    _pad_0xdc[0x4]; // +0xdc
    unsigned char                                    _pad_0xe0[0x4]; // +0xe0
    unsigned char                                    _pad_0xe4[0x4]; // +0xe4
    unsigned char                                    _pad_0xe8[0x4]; // +0xe8
    unsigned char                                    _pad_0xec[0x4]; // +0xec
    unsigned char                                    _pad_0xf0[0x4]; // +0xf0
    unsigned char                                    _pad_0xf4[0x4]; // +0xf4
    unsigned char                                    _pad_0xf8[0x4]; // +0xf8
    unsigned char                                    _pad_0xfc[0x4]; // +0xfc
    unsigned char                                    _pad_0x100[0x4]; // +0x100
    unsigned char                                    _pad_0x104[0x4]; // +0x104
    unsigned char                                    _pad_0x108[0x4]; // +0x108
    unsigned char                                    _pad_0x10c[0x4]; // +0x10c
    unsigned char                                    _pad_0x110[0x4]; // +0x110
    unsigned char                                    _pad_0x114[0x4]; // +0x114
    unsigned char                                    _pad_0x118[0x4]; // +0x118
    unsigned char                                    _pad_0x11c[0x4]; // +0x11c
    unsigned char                                    _pad_0x120[0x4]; // +0x120
    unsigned char                                    _pad_0x124[0x4]; // +0x124
    unsigned char                                    _pad_0x128[0x4]; // +0x128
    unsigned char                                    _pad_0x12c[0x4]; // +0x12c
    unsigned char                                    _pad_0x130[0x4]; // +0x130
    unsigned char                                    _pad_0x134[0x4]; // +0x134
    unsigned char                                    _pad_0x138[0x4]; // +0x138
    unsigned char                                    _pad_0x13c[0x4]; // +0x13c
    unsigned char                                    _pad_0x140[0x4]; // +0x140
    unsigned char                                    _pad_0x144[0x4]; // +0x144
    unsigned char                                    _pad_0x148[0x4]; // +0x148
    unsigned char                                    _pad_0x14c[0x4]; // +0x14c
    unsigned char                                    _pad_0x150[0x4]; // +0x150
    unsigned char                                    _pad_0x154[0x4]; // +0x154
    unsigned char                                    _pad_0x158[0x4]; // +0x158
    unsigned char                                    _pad_0x15c[0x4]; // +0x15c
    unsigned char                                    _pad_0x160[0x4]; // +0x160
    unsigned char                                    _pad_0x164[0x4]; // +0x164
    unsigned char                                    _pad_0x168[0x4]; // +0x168
    unsigned char                                    _pad_0x16c[0x4]; // +0x16c
    unsigned char                                    _pad_0x170[0x4]; // +0x170
    unsigned char                                    _pad_0x174[0x4]; // +0x174
    unsigned char                                    _pad_0x178[0x4]; // +0x178
    unsigned char                                    _pad_0x17c[0x4]; // +0x17c
    unsigned char                                    _pad_0x180[0x4]; // +0x180
    unsigned char                                    _pad_0x184[0x4]; // +0x184
    unsigned char                                    _pad_0x188[0x4]; // +0x188
    unsigned char                                    _pad_0x18c[0x4]; // +0x18c
    unsigned char                                    _pad_0x190[0x4]; // +0x190
    unsigned char                                    _pad_0x194[0x4]; // +0x194
    unsigned char                                    _pad_0x198[0x4]; // +0x198
    unsigned char                                    _pad_0x19c[0x4]; // +0x19c
    unsigned char                                    _pad_0x1a0[0x4]; // +0x1a0
    unsigned char                                    _pad_0x1a4[0x4]; // +0x1a4
    unsigned char                                    _pad_0x1a8[0x4]; // +0x1a8
    unsigned char                                    _pad_0x1ac[0x4]; // +0x1ac
    unsigned char                                    _pad_0x1b0[0x4]; // +0x1b0
    unsigned char                                    _pad_0x1b4[0x4]; // +0x1b4
    unsigned char                                    _pad_0x1b8[0x4]; // +0x1b8
    unsigned char                                    _pad_0x1bc[0x4]; // +0x1bc
    unsigned char                                    _pad_0x1c0[0x4]; // +0x1c0
    unsigned char                                    _pad_0x1c4[0x4]; // +0x1c4
    unsigned char                                    _pad_0x1c8[0x4]; // +0x1c8
    unsigned char                                    _pad_0x1cc[0x4]; // +0x1cc
    unsigned char                                    _pad_0x1d0[0x4]; // +0x1d0
    unsigned char                                    _pad_0x1d4[0x4]; // +0x1d4
    unsigned char                                    _pad_0x1d8[0x4]; // +0x1d8
    unsigned char                                    _pad_0x1dc[0x4]; // +0x1dc
    unsigned char                                    _pad_0x1e0[0x4]; // +0x1e0
    unsigned char                                    _pad_0x1e4[0x4]; // +0x1e4
    unsigned char                                    _pad_0x1e8[0x4]; // +0x1e8
    unsigned char                                    _pad_0x1ec[0x4]; // +0x1ec
    unsigned char                                    _pad_0x1f0[0x4]; // +0x1f0
    unsigned char                                    _pad_0x1f4[0x4]; // +0x1f4
    unsigned char                                    _pad_0x1f8[0x4]; // +0x1f8
    unsigned char                                    _pad_0x1fc[0x4]; // +0x1fc
    unsigned char                                    _pad_0x200[0x4]; // +0x200
    unsigned char                                    _pad_0x204[0x4]; // +0x204
    unsigned char                                    _pad_0x208[0x4]; // +0x208
    unsigned char                                    _pad_0x20c[0x4]; // +0x20c
    unsigned char                                    _pad_0x210[0x4]; // +0x210
    unsigned char                                    _pad_0x214[0x4]; // +0x214
    unsigned char                                    _pad_0x218[0x4]; // +0x218
    unsigned char                                    _pad_0x21c[0x4]; // +0x21c
    unsigned char                                    _pad_0x220[0x4]; // +0x220
    unsigned char                                    _pad_0x224[0x4]; // +0x224
    unsigned char                                    _pad_0x228[0x4]; // +0x228
    unsigned char                                    _pad_0x22c[0x4]; // +0x22c
    unsigned char                                    _pad_0x230[0x4]; // +0x230
    unsigned char                                    _pad_0x234[0x4]; // +0x234
    unsigned char                                    _pad_0x238[0x4]; // +0x238
    unsigned char                                    _pad_0x23c[0x4]; // +0x23c
    unsigned char                                    _pad_0x240[0x4]; // +0x240
    unsigned char                                    _pad_0x244[0x4]; // +0x244
    unsigned char                                    _pad_0x248[0x4]; // +0x248
    unsigned char                                    _pad_0x24c[0x4]; // +0x24c
    unsigned char                                    _pad_0x250[0x4]; // +0x250
    unsigned char                                    _pad_0x254[0x4]; // +0x254
    unsigned char                                    _pad_0x258[0x4]; // +0x258
    unsigned char                                    _pad_0x25c[0x4]; // +0x25c
    unsigned char                                    _pad_0x260[0x4]; // +0x260
    unsigned char                                    _pad_0x264[0x4]; // +0x264
    unsigned char                                    _pad_0x268[0x4]; // +0x268
    unsigned char                                    _pad_0x26c[0x4]; // +0x26c
    unsigned char                                    _pad_0x270[0x4]; // +0x270
    unsigned char                                    PrimitiveManagers[0x10]; // +0x274 CArray<CCountedPointer<CEnginePrimitiveManager>_>
    CEnginePrimitiveManagerStaticMeshes*             StaticMeshManager_Data; // +0x284 CCountedPointer<CEnginePrimitiveManagerStaticMeshes>::Data
    CCPPointerInfo*                                  StaticMeshManager_Info; // +0x288 CCountedPointer<CEnginePrimitiveManagerStaticMeshes>::Info
    CEnginePrimitiveManagerAnimatedMeshes*           AnimatedMeshManager_Data; // +0x28c CCountedPointer<CEnginePrimitiveManagerAnimatedMeshes>::Data
    CCPPointerInfo*                                  AnimatedMeshManager_Info; // +0x290 CCountedPointer<CEnginePrimitiveManagerAnimatedMeshes>::Info
    CEnginePrimitiveManagerRepeatedStaticMeshes*     RepeatedStaticMeshManager_Data; // +0x294 CCountedPointer<CEnginePrimitiveManagerRepeatedStaticMeshes>::Data
    CCPPointerInfo*                                  RepeatedStaticMeshManager_Info; // +0x298 CCountedPointer<CEnginePrimitiveManagerRepeatedStaticMeshes>::Info
    CEnginePrimitiveManagerRepeatedZSprites*         RepeatedZSpriteManager_Data; // +0x29c CCountedPointer<CEnginePrimitiveManagerRepeatedZSprites>::Data
    CCPPointerInfo*                                  RepeatedZSpriteManager_Info; // +0x2a0 CCountedPointer<CEnginePrimitiveManagerRepeatedZSprites>::Info
    CEnginePrimitiveManagerSprites*                  SpriteManager_Data; // +0x2a4 CCountedPointer<CEnginePrimitiveManagerSprites>::Data
    CCPPointerInfo*                                  SpriteManager_Info; // +0x2a8 CCountedPointer<CEnginePrimitiveManagerSprites>::Info
    CEnginePrimitiveManagerFlareSprites*             FlareSpriteManager_Data; // +0x2ac CCountedPointer<CEnginePrimitiveManagerFlareSprites>::Data
    CCPPointerInfo*                                  FlareSpriteManager_Info; // +0x2b0 CCountedPointer<CEnginePrimitiveManagerFlareSprites>::Info
    CEnginePrimitiveManagerWeaponTrails*             WeaponTrailManager_Data; // +0x2b4 CCountedPointer<CEnginePrimitiveManagerWeaponTrails>::Data
    CCPPointerInfo*                                  WeaponTrailManager_Info; // +0x2b8 CCountedPointer<CEnginePrimitiveManagerWeaponTrails>::Info
    CEnginePrimitiveManagerSpriteTrails*             SpriteTrailManager_Data; // +0x2bc CCountedPointer<CEnginePrimitiveManagerSpriteTrails>::Data
    CCPPointerInfo*                                  SpriteTrailManager_Info; // +0x2c0 CCountedPointer<CEnginePrimitiveManagerSpriteTrails>::Info
    CEnginePrimitiveManagerLines*                    LineManager_Data; // +0x2c4 CCountedPointer<CEnginePrimitiveManagerLines>::Data
    CCPPointerInfo*                                  LineManager_Info; // +0x2c8 CCountedPointer<CEnginePrimitiveManagerLines>::Info
    CEnginePrimitiveManagerText*                     TextManager_Data; // +0x2cc CCountedPointer<CEnginePrimitiveManagerText>::Data
    CCPPointerInfo*                                  TextManager_Info; // +0x2d0 CCountedPointer<CEnginePrimitiveManagerText>::Info
    CEnginePrimitiveManagerGameMeshes*               GameMeshManager_Data; // +0x2d4 CCountedPointer<CEnginePrimitiveManagerGameMeshes>::Data
    CCPPointerInfo*                                  GameMeshManager_Info; // +0x2d8 CCountedPointer<CEnginePrimitiveManagerGameMeshes>::Info
    CEnginePrimitiveOcclusionGroupManager*           OcclusionGroupManager_Data; // +0x2dc CCountedPointer<CEnginePrimitiveOcclusionGroupManager>::Data
    CCPPointerInfo*                                  OcclusionGroupManager_Info; // +0x2e0 CCountedPointer<CEnginePrimitiveOcclusionGroupManager>::Info
    CEnginePrimitiveGroupManager*                    PrimitiveGroupManager_Data; // +0x2e4 CCountedPointer<CEnginePrimitiveGroupManager>::Data
    CCPPointerInfo*                                  PrimitiveGroupManager_Info; // +0x2e8 CCountedPointer<CEnginePrimitiveGroupManager>::Info
    CEnginePrimitiveChangerManager*                  PrimitiveChangerManager_Data; // +0x2ec CCountedPointer<CEnginePrimitiveChangerManager>::Data
    CCPPointerInfo*                                  PrimitiveChangerManager_Info; // +0x2f0 CCountedPointer<CEnginePrimitiveChangerManager>::Info
    CEngineClothRenderer*                            ClothRenderer_Data; // +0x2f4 CCountedPointer<CEngineClothRenderer>::Data
    CCPPointerInfo*                                  ClothRenderer_Info; // +0x2f8 CCountedPointer<CEngineClothRenderer>::Info
    CEnginePrimitiveManagerParticleLineGroup*        ParticleLineGroupManager_Data; // +0x2fc CCountedPointer<CEnginePrimitiveManagerParticleLineGroup>::Data
    CCPPointerInfo*                                  ParticleLineGroupManager_Info; // +0x300 CCountedPointer<CEnginePrimitiveManagerParticleLineGroup>::Info
    CEnginePrimitiveManagerParticleMeshGroup*        ParticleMeshGroupManager_Data; // +0x304 CCountedPointer<CEnginePrimitiveManagerParticleMeshGroup>::Data
    CCPPointerInfo*                                  ParticleMeshGroupManager_Info; // +0x308 CCountedPointer<CEnginePrimitiveManagerParticleMeshGroup>::Info
    CEnginePrimitiveManagerParticleSpriteGroup*      ParticleSpriteGroupManager_Data; // +0x30c CCountedPointer<CEnginePrimitiveManagerParticleSpriteGroup>::Data
    CCPPointerInfo*                                  ParticleSpriteGroupManager_Info; // +0x310 CCountedPointer<CEnginePrimitiveManagerParticleSpriteGroup>::Info
    CEnginePrimitiveManagerParticleSpriteTrailGroup* ParticleSpriteTrailGroupManager_Data; // +0x314 CCountedPointer<CEnginePrimitiveManagerParticleSpriteTrailGroup>::Data
    CCPPointerInfo*                                  ParticleSpriteTrailGroupManager_Info; // +0x318 CCountedPointer<CEnginePrimitiveManagerParticleSpriteTrailGroup>::Info
    CEnginePrimitiveManagerParticleGroup*            ParticleGroupManager_Data; // +0x31c CCountedPointer<CEnginePrimitiveManagerParticleGroup>::Data
    CCPPointerInfo*                                  ParticleGroupManager_Info; // +0x320 CCountedPointer<CEnginePrimitiveManagerParticleGroup>::Info
    CEnginePrimitiveManagerDecal*                    DecalManager_Data; // +0x324 CCountedPointer<CEnginePrimitiveManagerDecal>::Data
    CCPPointerInfo*                                  DecalManager_Info; // +0x328 CCountedPointer<CEnginePrimitiveManagerDecal>::Info
    CEnginePrimitiveManagerParticleDecalGroup*       DecalGroupManager_Data; // +0x32c CCountedPointer<CEnginePrimitiveManagerParticleDecalGroup>::Data
    CCPPointerInfo*                                  DecalGroupManager_Info; // +0x330 CCountedPointer<CEnginePrimitiveManagerParticleDecalGroup>::Info
    CEnginePrimitiveManagerWeatherMask*              WeatherMaskManager_Data; // +0x334 CCountedPointer<CEnginePrimitiveManagerWeatherMask>::Data
    CCPPointerInfo*                                  WeatherMaskManager_Info; // +0x338 CCountedPointer<CEnginePrimitiveManagerWeatherMask>::Info
    unsigned char                                    SceneList[0x10]; // +0x33c CArray<CEngineScene_*>
    float                                            MaxPreloadRadius; // +0x34c
    float                                            MinPreloadRadius; // +0x350
    float                                            MaxPreloadMipmapTolerance; // +0x354
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CEnginePrimitiveRenderer) == 0x358);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, PrimitiveManagers) == 0x274);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, StaticMeshManager_Data) == 0x284);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, StaticMeshManager_Info) == 0x288);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, AnimatedMeshManager_Data) == 0x28c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, AnimatedMeshManager_Info) == 0x290);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, RepeatedStaticMeshManager_Data) == 0x294);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, RepeatedStaticMeshManager_Info) == 0x298);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, RepeatedZSpriteManager_Data) == 0x29c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, RepeatedZSpriteManager_Info) == 0x2a0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, SpriteManager_Data) == 0x2a4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, SpriteManager_Info) == 0x2a8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, FlareSpriteManager_Data) == 0x2ac);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, FlareSpriteManager_Info) == 0x2b0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, WeaponTrailManager_Data) == 0x2b4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, WeaponTrailManager_Info) == 0x2b8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, SpriteTrailManager_Data) == 0x2bc);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, SpriteTrailManager_Info) == 0x2c0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, LineManager_Data) == 0x2c4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, LineManager_Info) == 0x2c8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, TextManager_Data) == 0x2cc);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, TextManager_Info) == 0x2d0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, GameMeshManager_Data) == 0x2d4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, GameMeshManager_Info) == 0x2d8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, OcclusionGroupManager_Data) == 0x2dc);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, OcclusionGroupManager_Info) == 0x2e0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, PrimitiveGroupManager_Data) == 0x2e4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, PrimitiveGroupManager_Info) == 0x2e8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, PrimitiveChangerManager_Data) == 0x2ec);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, PrimitiveChangerManager_Info) == 0x2f0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ClothRenderer_Data) == 0x2f4);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ClothRenderer_Info) == 0x2f8);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleLineGroupManager_Data) == 0x2fc);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleLineGroupManager_Info) == 0x300);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleMeshGroupManager_Data) == 0x304);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleMeshGroupManager_Info) == 0x308);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleSpriteGroupManager_Data) == 0x30c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleSpriteGroupManager_Info) == 0x310);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleSpriteTrailGroupManager_Data) == 0x314);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleSpriteTrailGroupManager_Info) == 0x318);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleGroupManager_Data) == 0x31c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, ParticleGroupManager_Info) == 0x320);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, DecalManager_Data) == 0x324);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, DecalManager_Info) == 0x328);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, DecalGroupManager_Data) == 0x32c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, DecalGroupManager_Info) == 0x330);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, WeatherMaskManager_Data) == 0x334);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, WeatherMaskManager_Info) == 0x338);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, SceneList) == 0x33c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, MaxPreloadRadius) == 0x34c);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, MinPreloadRadius) == 0x350);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitiveRenderer, MaxPreloadMipmapTolerance) == 0x354);

#endif // FABLE_ENGINE_CENGINEPRIMITIVERENDERER_H
