#ifndef FABLE_ENGINE_CENGINE_H
#define FABLE_ENGINE_CENGINE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CEngine = 0x188.
// Retail evidence: 2 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 1 agreeing; PINNED by 8 retyped file(s) despite conflicts.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CCamera;
struct CDefPointeeBase;

#pragma pack(push, 1)
struct CEngine {
    void*            __vftable;                              // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char    _pad_0x04[0x4];                         // +0x04
    unsigned char    f;                                      // +0x08 retail-only unsigned char (previous header)
    unsigned char    _pad_0x09[0x3];                         // +0x09
    unsigned char    _pad_0x0c[0x4];                         // +0x0c
    bool             EnableWireFrame;                        // +0x10
    bool             EnableEngine;                           // +0x11
    bool             EnableLocalLights;                      // +0x12
    bool             EnableTextures;                         // +0x13
    CCamera*         CurrentCamera;                          // +0x14
    bool             NewSceneFlag;                           // +0x18
    unsigned char    _pad_0x19[0x3];                         // +0x19
    unsigned long    NewSceneLoadFlags;                      // +0x1c
    float            NewSceneTimeOut;                        // +0x20
    bool             CutscenePreloadFlag;                    // +0x24
    unsigned char    _pad_0x25[0x3];                         // +0x25
    float            CutscenePreloadTimeout;                 // +0x28
    float            CutsceneFastPreloadTimeout;             // +0x2c
    float            ActorAdditionalLoadTimeout;             // +0x30
    float            ActorRadius;                            // +0x34
    bool             ActorsLoading;                          // +0x38
    bool             CameraAngleChanged;                     // +0x39
    unsigned char    _pad_0x3a[0x2];                         // +0x3a
    unsigned char    PreloadCameras[0x14];                   // +0x3c CArray<CCamera>
    unsigned char    PreloadStats[0x20];                     // +0x50 CPreloadStats
    float            PreloadedCameraPos_X;                   // +0x70 C3DVector::X
    float            PreloadedCameraPos_Y;                   // +0x74 C3DVector::Y
    float            PreloadedCameraPos_Z;                   // +0x78 C3DVector::Z
    float            PreloadedLookVector_X;                  // +0x7c C3DVector::X
    float            PreloadedLookVector_Y;                  // +0x80 C3DVector::Y
    float            PreloadedLookVector_Z;                  // +0x84 C3DVector::Z
    float            StartNewSceneTransitionTime;            // +0x88
    bool             IsInitialised;                          // +0x8c
    unsigned char    _pad_0x8d[0x3];                         // +0x8d
    long             CurrentRenderFrame;                     // +0x90
    long             CurrentWorldFrame;                      // +0x94
    long             CurrentPausedWorldFrame;                // +0x98
    unsigned char    _pad_0x9c[0x4];                         // +0x9c
    double           NonInterpolatedWorldTime;               // +0xa0
    double           NonInterpolatedPausedWorldTime;         // +0xa8
    double           InterpolatedWorldTime;                  // +0xb0
    unsigned long    WorldFramesPerSecond;                   // +0xb8
    bool             BlockOnLoad;                            // +0xbc
    unsigned char    _pad_0xbd[0x3];                         // +0xbd
    unsigned long    SceneFilterFlags;                       // +0xc0
    bool             EnableScreenShotMode;                   // +0xc4
    bool             EnablePostDeviceReset;                  // +0xc5
    unsigned char    _pad_0xc6[0x2];                         // +0xc6
    unsigned char    VideoOptions[0x38];                     // +0xc8 CEngineVideoOptions
    unsigned char    OffWorldTickProcessInfo[0x20];          // +0x100 <unnamed-type-OffWorldTickProcessInfo>
    CDefPointeeBase* PEnvironmentDef_Object;                 // +0x120 CDefPointer<CDefClassBase_const_>::Object
    CDefPointeeBase* PEngineDef_Object;                      // +0x124 CDefPointer<CDefClassBase_const_>::Object
    unsigned char    PEngineVideoOptionsDefs[0x10];          // +0x128 CDefPointer<CDefClassBase_const_>[4]
    unsigned char    FrameMemoryPool[0x1c];                  // +0x138 CSimpleMemoryPool
    unsigned char    ScratchZBuffersD24S8[0x10];             // +0x154 CArray<CSurface_*>
    long             AnisotropicFilteringLevel;              // +0x164
    unsigned char    RenderLayers[0x10];                     // +0x168 CArray<CEngineLayerRenderer_*>
    unsigned char    EngineComponents[0x10];                 // +0x178 CArray<CEngineComponent_*>
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CEngine) == 0x188);
FABLE_STATIC_ASSERT(offsetof(CEngine, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CEngine, f) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnableWireFrame) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnableEngine) == 0x11);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnableLocalLights) == 0x12);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnableTextures) == 0x13);
FABLE_STATIC_ASSERT(offsetof(CEngine, CurrentCamera) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CEngine, NewSceneFlag) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CEngine, NewSceneLoadFlags) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CEngine, NewSceneTimeOut) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CEngine, CutscenePreloadFlag) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CEngine, CutscenePreloadTimeout) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CEngine, CutsceneFastPreloadTimeout) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CEngine, ActorAdditionalLoadTimeout) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CEngine, ActorRadius) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CEngine, ActorsLoading) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CEngine, CameraAngleChanged) == 0x39);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadCameras) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadStats) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedCameraPos_X) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedCameraPos_Y) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedCameraPos_Z) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedLookVector_X) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedLookVector_Y) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CEngine, PreloadedLookVector_Z) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CEngine, StartNewSceneTransitionTime) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CEngine, IsInitialised) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CEngine, CurrentRenderFrame) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CEngine, CurrentWorldFrame) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CEngine, CurrentPausedWorldFrame) == 0x98);
FABLE_STATIC_ASSERT(offsetof(CEngine, NonInterpolatedWorldTime) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CEngine, NonInterpolatedPausedWorldTime) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CEngine, InterpolatedWorldTime) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CEngine, WorldFramesPerSecond) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CEngine, BlockOnLoad) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CEngine, SceneFilterFlags) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnableScreenShotMode) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CEngine, EnablePostDeviceReset) == 0xc5);
FABLE_STATIC_ASSERT(offsetof(CEngine, VideoOptions) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CEngine, OffWorldTickProcessInfo) == 0x100);
FABLE_STATIC_ASSERT(offsetof(CEngine, PEnvironmentDef_Object) == 0x120);
FABLE_STATIC_ASSERT(offsetof(CEngine, PEngineDef_Object) == 0x124);
FABLE_STATIC_ASSERT(offsetof(CEngine, PEngineVideoOptionsDefs) == 0x128);
FABLE_STATIC_ASSERT(offsetof(CEngine, FrameMemoryPool) == 0x138);
FABLE_STATIC_ASSERT(offsetof(CEngine, ScratchZBuffersD24S8) == 0x154);
FABLE_STATIC_ASSERT(offsetof(CEngine, AnisotropicFilteringLevel) == 0x164);
FABLE_STATIC_ASSERT(offsetof(CEngine, RenderLayers) == 0x168);
FABLE_STATIC_ASSERT(offsetof(CEngine, EngineComponents) == 0x178);

#endif // FABLE_ENGINE_CENGINE_H
