#ifndef FABLE_ENGINE_CENGINEPRIMITIVE2DVIEWPORTMANAGER_H
#define FABLE_ENGINE_CENGINEPRIMITIVE2DVIEWPORTMANAGER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CEnginePrimitive2DViewportManager = 0x38.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CEnginePrimitive2DViewportManager {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char AlphaMaskInfo[0x2c];                       // +0x0c C2DAlphaMaskInfo
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CEnginePrimitive2DViewportManager) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitive2DViewportManager, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CEnginePrimitive2DViewportManager, AlphaMaskInfo) == 0xc);

#endif // FABLE_ENGINE_CENGINEPRIMITIVE2DVIEWPORTMANAGER_H
