#ifndef FABLE_ENGINE_CENGINESCREENEFFECTRADIALBLURRENDERER_H
#define FABLE_ENGINE_CENGINESCREENEFFECTRADIALBLURRENDERER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CEngineScreenEffectRadialBlurRenderer = 0x22c.
// Retail evidence: 2 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CTexture;

#pragma pack(push, 1)
struct CEngineScreenEffectRadialBlurRenderer {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    CTexture*     BlurTexture256_1;                          // +0x0c
    CTexture*     BlurTexture256_2;                          // +0x10
    long          BlurTextureHandle256_1;                    // +0x14
    long          BlurTextureHandle256_2;                    // +0x18
    long          DynamicTexturePageHandle;                  // +0x1c
    unsigned char ScreenCopyVertexShader[0x8];               // +0x20 CVertexShader
    unsigned char RadialBlurVertexShader[0x8];               // +0x28 CVertexShader
    unsigned char ScreenCopyPixelShader[0x8];                // +0x30 CPixelShader
    unsigned char RadialBlurPixelShader[0x8];                // +0x38 CPixelShader
    unsigned char TextureOnlyPixelShader[0x8];               // +0x40 CPixelShader
    unsigned char TextureDiffusePixelShader[0x8];            // +0x48 CPixelShader
    unsigned char BackBufferToTextureVerts[0x60];            // +0x50 CTVertexColTex1[4]
    unsigned char Blur256ToBlur256Verts[0x60];               // +0xb0 CTVertexColTex1[4]
    unsigned char TextureToBackBufferVerts[0x60];            // +0x110 CTVertexColTex1[4]
    unsigned char BlurCenter[0x8];                           // +0x170 C2DVector
    unsigned char AreaCenter[0x8];                           // +0x178 C2DVector
    unsigned char BlurCenterWorldTrackPosition[0xc];         // +0x180 C3DVector
    unsigned char AreaCenterWorldTrackPosition[0xc];         // +0x18c C3DVector
    unsigned char CurrentParameters[0x28];                   // +0x198 CParameters
    bool          AreaTrack3DPos;                            // +0x1c0
    bool          BlurTrack3DPos;                            // +0x1c1
    unsigned char _pad_0x1c2[0x2];                           // +0x1c2
    long          ShowDebug;                                 // +0x1c4
    bool          EffectSupported;                           // +0x1c8
    bool          UseEnvironmentParameters;                  // +0x1c9
    unsigned char _pad_0x1ca[0x2];                           // +0x1ca
    unsigned char BlurToBackBufferVerts[0x60];               // +0x1cc CTVertexColTex1[4]
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CEngineScreenEffectRadialBlurRenderer) == 0x22c);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurTexture256_1) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurTexture256_2) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurTextureHandle256_1) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurTextureHandle256_2) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, DynamicTexturePageHandle) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, ScreenCopyVertexShader) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, RadialBlurVertexShader) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, ScreenCopyPixelShader) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, RadialBlurPixelShader) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, TextureOnlyPixelShader) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, TextureDiffusePixelShader) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BackBufferToTextureVerts) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, Blur256ToBlur256Verts) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, TextureToBackBufferVerts) == 0x110);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurCenter) == 0x170);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, AreaCenter) == 0x178);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurCenterWorldTrackPosition) == 0x180);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, AreaCenterWorldTrackPosition) == 0x18c);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, CurrentParameters) == 0x198);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, AreaTrack3DPos) == 0x1c0);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurTrack3DPos) == 0x1c1);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, ShowDebug) == 0x1c4);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, EffectSupported) == 0x1c8);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, UseEnvironmentParameters) == 0x1c9);
FABLE_STATIC_ASSERT(offsetof(CEngineScreenEffectRadialBlurRenderer, BlurToBackBufferVerts) == 0x1cc);

#endif // FABLE_ENGINE_CENGINESCREENEFFECTRADIALBLURRENDERER_H
