#ifndef FABLE_ENGINE_CGAMETIMEMANAGER_H
#define FABLE_ENGINE_CGAMETIMEMANAGER_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CGameTimeManager = 0x40.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CMainGameComponent;
struct CWorld;

#pragma pack(push, 1)
struct CGameTimeManager {
    CWorld*             World;                               // +0x00
    CMainGameComponent* GameComponent;                       // +0x04
    float               Time;                                // +0x08
    float               PrevTime;                            // +0x0c
    float               TimeStep;                            // +0x10
    long                DayCount;                            // +0x14
    bool                UsingVillageTime;                    // +0x18
    unsigned char       _pad_0x19[0x3];                      // +0x19
    float               VillageTime;                         // +0x1c
    bool                VillageDay;                          // +0x20
    bool                FastForwardingToTime;                // +0x21
    unsigned char       _pad_0x22[0x2];                      // +0x22
    float               TimeFastForwardingTo;                // +0x24
    float               SecondsLeftToFastForwardTime;        // +0x28
    unsigned char       StopTimeIndexes[0x10];               // +0x2c set<long,std::less<long>,std::allocator<long>_>
    long                NextStopTimeIndex;                   // +0x3c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CGameTimeManager) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, World) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, GameComponent) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, Time) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, PrevTime) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, TimeStep) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, DayCount) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, UsingVillageTime) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, VillageTime) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, VillageDay) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, FastForwardingToTime) == 0x21);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, TimeFastForwardingTo) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, SecondsLeftToFastForwardTime) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, StopTimeIndexes) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CGameTimeManager, NextStopTimeIndex) == 0x3c);

#endif // FABLE_ENGINE_CGAMETIMEMANAGER_H
