#ifndef FABLE_ENGINE_CINVENTORYITEMDEF_H
#define FABLE_ENGINE_CINVENTORYITEMDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CInventoryItemDef = 0x70.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CInventoryItemDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x1];                            // +0x24
    unsigned char Graphic[0xf];                              // +0x25 CEngineGraphic
    unsigned long ItemDescription;                           // +0x34
    unsigned long ItemDetails;                               // +0x38
    long          InventoryCategory;                         // +0x3c
    long          MaxNumberItems;                            // +0x40
    long          SlotIndex;                                 // +0x44
    float         ActivationTime;                            // +0x48
    unsigned char UseButtonAction[0x4];                      // +0x4c EInventoryActionType
    unsigned char InventoryType[0x4];                        // +0x50 ETCInterfaceType
    unsigned char Orientation[0x4];                          // +0x54 EInventoryObjectOrientation
    long          HeroAbilityDef;                            // +0x58
    bool          IsSellable;                                // +0x5c
    bool          IsBuyable;                                 // +0x5d
    bool          IsConfiscatable;                           // +0x5e
    bool          DoNotPersistUntilQuestCompleted;           // +0x5f
    bool          DoNotAutoPickUp;                           // +0x60
    bool          AutoPickUpAfterFirstPickUp;                // +0x61
    unsigned char _pad_0x62[0x2];                            // +0x62
    long          ItemToSelectUponRemoval;                   // +0x64
    unsigned char TutorialCategory[0x4];                     // +0x68 ETutorialCategory
    unsigned char UIInventoryCategory[0x4];                  // +0x6c EUIInventoryCategory
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CInventoryItemDef) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, Graphic) == 0x25);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, ItemDescription) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, ItemDetails) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, InventoryCategory) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, MaxNumberItems) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, SlotIndex) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, ActivationTime) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, UseButtonAction) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, InventoryType) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, Orientation) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, HeroAbilityDef) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, IsSellable) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, IsBuyable) == 0x5d);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, IsConfiscatable) == 0x5e);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, DoNotPersistUntilQuestCompleted) == 0x5f);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, DoNotAutoPickUp) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, AutoPickUpAfterFirstPickUp) == 0x61);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, ItemToSelectUponRemoval) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, TutorialCategory) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CInventoryItemDef, UIInventoryCategory) == 0x6c);

#endif // FABLE_ENGINE_CINVENTORYITEMDEF_H
