#ifndef FABLE_ENGINE_CLANDSCAPEBACKGROUNDPATCH_H
#define FABLE_ENGINE_CLANDSCAPEBACKGROUNDPATCH_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CLandscapeBackgroundPatch = 0x11c.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CEngineWaterBackgroundSubPatch;
struct CIndexBuffer;
struct CLandscapeBackgroundTreeNode;
struct CSubPatchTreeLODLockElement;
struct CTexture;
struct CVertexBufferWin32;

#pragma pack(push, 1)
struct CLandscapeBackgroundPatch {
    void*                           __vftable;               // +0x00 vptr, or first dword of a flattened base subobject
    CLandscapeBackgroundTreeNode*   Parent;                  // +0x04
    unsigned char                   EdgeStrips[0xb0];        // +0x08 CPatchTesselationEdgeStrip[4]
    CTexture*                       Texture;                 // +0xb8
    CIndexBuffer*                   IndexBuffer;             // +0xbc
    CVertexBufferWin32*             VertexBuffer;            // +0xc0
    CIndexBuffer*                   BridgeIndexBuffers[4];   // +0xc4
    CVertexBufferWin32*             BridgeVertexBuffers[4];  // +0xd4
    unsigned short                  BridgePolyCount[4];      // +0xe4
    CSubPatchTreeLODLockElement*    UVLockTreeU;             // +0xec
    CSubPatchTreeLODLockElement*    UVLockTreeV;             // +0xf0
    CEngineWaterBackgroundSubPatch* WaterSubPatch;           // +0xf4
    float                           MinZ;                    // +0xf8
    float                           MaxZ;                    // +0xfc
    long                            ZSorterHandle;           // +0x100
    unsigned short                  VertexCount;             // +0x104
    unsigned short                  PolyCountIncDegenerates; // +0x106
    unsigned short                  TextureWidthNeeded;      // +0x108
    unsigned short                  TextureHeightNeeded;     // +0x10a
    unsigned short                  MapX;                    // +0x10c
    unsigned short                  MapY;                    // +0x10e
    unsigned short                  Width;                   // +0x110
    unsigned short                  Height;                  // +0x112
    unsigned short                  LockedGridSpacingX;      // +0x114
    unsigned short                  LockedGridSpacingY;      // +0x116
    unsigned char                   LODBand;                 // +0x118
    bool                            SharedIndexBuffer;       // +0x119
    bool                            WaterOnlyPatch;          // +0x11a
    bool                            IsDefaultSection;        // +0x11b
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CLandscapeBackgroundPatch) == 0x11c);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, Parent) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, EdgeStrips) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, Texture) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, IndexBuffer) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, VertexBuffer) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, BridgeIndexBuffers) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, BridgeVertexBuffers) == 0xd4);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, BridgePolyCount) == 0xe4);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, UVLockTreeU) == 0xec);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, UVLockTreeV) == 0xf0);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, WaterSubPatch) == 0xf4);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, MinZ) == 0xf8);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, MaxZ) == 0xfc);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, ZSorterHandle) == 0x100);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, VertexCount) == 0x104);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, PolyCountIncDegenerates) == 0x106);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, TextureWidthNeeded) == 0x108);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, TextureHeightNeeded) == 0x10a);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, MapX) == 0x10c);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, MapY) == 0x10e);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, Width) == 0x110);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, Height) == 0x112);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, LockedGridSpacingX) == 0x114);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, LockedGridSpacingY) == 0x116);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, LODBand) == 0x118);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, SharedIndexBuffer) == 0x119);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, WaterOnlyPatch) == 0x11a);
FABLE_STATIC_ASSERT(offsetof(CLandscapeBackgroundPatch, IsDefaultSection) == 0x11b);

#endif // FABLE_ENGINE_CLANDSCAPEBACKGROUNDPATCH_H
