#ifndef FABLE_ENGINE_CNAVIGATORASTAR_H
#define FABLE_ENGINE_CNAVIGATORASTAR_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CNavigatorAStar = 0xd4.
// Retail evidence: 2 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CANavQuadTreeNode;

#pragma pack(push, 1)
struct CNavigatorAStar {
    void*              __vftable;                            // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char      _pad_0x04[0x4];                       // +0x04
    unsigned char      _pad_0x08[0x4];                       // +0x08
    unsigned char      _pad_0x0c[0x4];                       // +0x0c
    unsigned char      _pad_0x10[0x4];                       // +0x10
    unsigned char      _pad_0x14[0x4];                       // +0x14
    unsigned char      _pad_0x18[0x4];                       // +0x18
    unsigned char      _pad_0x1c[0x4];                       // +0x1c
    void*              sub;                                  // +0x20 retail-only (CNavigatorAStar_CreateLineList_00a1bfc0.cpp)
    unsigned char      States[0x10];                         // +0x24 map<long,CNavigatorAStar::CAStarState,std::less<long>,std::allocator<std::pair<long_const_,CNavigatorAStar::CAStarState>_>_>
    unsigned char      BlockedStartNode[0x10];               // +0x34 CNavBlockedQuadTreeNode
    unsigned char      BlockedEndNode[0x10];                 // +0x44 CNavBlockedQuadTreeNode
    unsigned char      BlockedNodeAskedToGetTo[0x10];        // +0x54 CNavBlockedQuadTreeNode
    unsigned char      OpenList[0x10];                       // +0x64 CPriorityQueue<CNavigatorAStar::CAStarState_*>
    CANavQuadTreeNode* GoalNode;                             // +0x74
    unsigned char      GoalPosition[0x8];                    // +0x78 C2DVector
    CANavQuadTreeNode* NodeAskedToGetTo;                     // +0x80
    unsigned char      PosAskedToGetTo[0xc];                 // +0x84 C3DVector
    CANavQuadTreeNode* LastNavigableNodeVisited;             // +0x90
    unsigned char      Route[0xc];                           // +0x94 list<CNavWayPoint,std::allocator<CNavWayPoint>_>
    unsigned char      CullFront[0x4];                       // +0xa0 _List_iterator<std::_List_val<CNavWayPoint,std::allocator<CNavWayPoint>_>_>
    unsigned char      CullBack[0x4];                        // +0xa4 _List_iterator<std::_List_val<CNavWayPoint,std::allocator<CNavWayPoint>_>_>
    unsigned char      LastWayPointVisited[0x8];             // +0xa8 C2DVector
    unsigned char      StringLeadPosition[0x8];              // +0xb0 C2DVector
    unsigned char      LastKnownNavPos[0xc];                 // +0xb8 C3DVector
    float              LastKnownNavSpeed;                    // +0xc4
    long               LastKnownNavLayer;                    // +0xc8
    bool               HeadingForActionPoint;                // +0xcc
    bool               Initialised;                          // +0xcd
    bool               GotRoute;                             // +0xce
    bool               SlowedDownForLastPoint;               // +0xcf
    bool               Culled;                               // +0xd0
    bool               PartWayThroughAStar;                  // +0xd1
    unsigned char      NoOfClockwiseTurns;                   // +0xd2
    unsigned char      NoOfAntiClockwiseTurns;               // +0xd3
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CNavigatorAStar) == 0xd4);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, sub) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, States) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, BlockedStartNode) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, BlockedEndNode) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, BlockedNodeAskedToGetTo) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, OpenList) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, GoalNode) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, GoalPosition) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, NodeAskedToGetTo) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, PosAskedToGetTo) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, LastNavigableNodeVisited) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, Route) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, CullFront) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, CullBack) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, LastWayPointVisited) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, StringLeadPosition) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, LastKnownNavPos) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, LastKnownNavSpeed) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, LastKnownNavLayer) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, HeadingForActionPoint) == 0xcc);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, Initialised) == 0xcd);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, GotRoute) == 0xce);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, SlowedDownForLastPoint) == 0xcf);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, Culled) == 0xd0);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, PartWayThroughAStar) == 0xd1);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, NoOfClockwiseTurns) == 0xd2);
FABLE_STATIC_ASSERT(offsetof(CNavigatorAStar, NoOfAntiClockwiseTurns) == 0xd3);

#endif // FABLE_ENGINE_CNAVIGATORASTAR_H
