#ifndef FABLE_ENGINE_COPTIMISEDFACE_H
#define FABLE_ENGINE_COPTIMISEDFACE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof COptimisedFace = 0x48.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct COptimisedFace {
    unsigned long VertexIndices[3];                          // +0x00
    unsigned long UniqueVertexIndices[3];                    // +0x0c
    long          Edges[3];                                  // +0x18
    float         UTangent_X;                                // +0x24 C3DVector::X
    float         UTangent_Y;                                // +0x28 C3DVector::Y
    float         UTangent_Z;                                // +0x2c C3DVector::Z
    float         VTangent_X;                                // +0x30 C3DVector::X
    float         VTangent_Y;                                // +0x34 C3DVector::Y
    float         VTangent_Z;                                // +0x38 C3DVector::Z
    bool          Exists;                                    // +0x3c
    unsigned char _pad_0x3d[0x3];                            // +0x3d
    unsigned long OutputIndex;                               // +0x40
    long          Segment;                                   // +0x44
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(COptimisedFace) == 0x48);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, VertexIndices) == 0x0);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, UniqueVertexIndices) == 0xc);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, Edges) == 0x18);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, UTangent_X) == 0x24);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, UTangent_Y) == 0x28);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, UTangent_Z) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, VTangent_X) == 0x30);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, VTangent_Y) == 0x34);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, VTangent_Z) == 0x38);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, Exists) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, OutputIndex) == 0x40);
FABLE_STATIC_ASSERT(offsetof(COptimisedFace, Segment) == 0x44);

#endif // FABLE_ENGINE_COPTIMISEDFACE_H
