#ifndef FABLE_ENGINE_CPARENTDEFCLASSBASE_H
#define FABLE_ENGINE_CPARENTDEFCLASSBASE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CParentDefClassBase = 0x3d.
// Retail evidence: 3 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CParentDefClassBase {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _base_0x04[0x21];                          // +0x04 flattened base-class subobject(s)
    unsigned char InstantiationName[0x4];                    // +0x25 CDefString
    unsigned char SubDefInfoMap[0x14];                       // +0x29 CVectorMap<unsigned_long,CDefClassBase::CSubDefInfo,CKeyPairCompareLess<unsigned_long,CDefClassBase::CSubDefInfo>_>
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CParentDefClassBase) == 0x3d);
FABLE_STATIC_ASSERT(offsetof(CParentDefClassBase, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CParentDefClassBase, InstantiationName) == 0x25);
FABLE_STATIC_ASSERT(offsetof(CParentDefClassBase, SubDefInfoMap) == 0x29);

#endif // FABLE_ENGINE_CPARENTDEFCLASSBASE_H
