#ifndef FABLE_ENGINE_CPERCEIVEDTHINGDEF_H
#define FABLE_ENGINE_CPERCEIVEDTHINGDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CPerceivedThingDef = 0x50.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CPerceivedThingDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    float         FieldOfView;                               // +0x28
    float         GiveUpChaseRadius;                         // +0x2c
    float         SightRadius;                               // +0x30
    float         ExtendedSightRadius;                       // +0x34
    float         SoundRadius;                               // +0x38
    float         SmellRadius;                               // +0x3c
    unsigned char Type[0x4];                                 // +0x40 EPerceivedThingType
    float         AwarenessTimer;                            // +0x44
    float         DayTimeVisibilityMultiplier;               // +0x48
    float         NightTimeVisibilityMultiplier;             // +0x4c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CPerceivedThingDef) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, FieldOfView) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, GiveUpChaseRadius) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, SightRadius) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, ExtendedSightRadius) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, SoundRadius) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, SmellRadius) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, Type) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, AwarenessTimer) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, DayTimeVisibilityMultiplier) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CPerceivedThingDef, NightTimeVisibilityMultiplier) == 0x4c);

#endif // FABLE_ENGINE_CPERCEIVEDTHINGDEF_H
