#ifndef FABLE_ENGINE_CREACTIONMATCH_SPHERE_H
#define FABLE_ENGINE_CREACTIONMATCH_SPHERE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CReactionMatch_Sphere = 0x1c.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CReactionMatch_Sphere {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char Centre[0x10];                              // +0x08 COpinionSet
    float         SqRadius;                                  // +0x18
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CReactionMatch_Sphere) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CReactionMatch_Sphere, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CReactionMatch_Sphere, Centre) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CReactionMatch_Sphere, SqRadius) == 0x18);

#endif // FABLE_ENGINE_CREACTIONMATCH_SPHERE_H
