#ifndef FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_LINEARTIME_H
#define FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_LINEARTIME_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CReactionFrequencyTraits_LinearTime = 0x10.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CReactionFrequencyTraits_LinearTime {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    float         MinWait;                                   // +0x04
    float         WaitRange;                                 // +0x08
    unsigned long FrameHappened;                             // +0x0c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CReactionFrequencyTraits_LinearTime) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_LinearTime, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_LinearTime, MinWait) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_LinearTime, WaitRange) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_LinearTime, FrameHappened) == 0xc);

#endif // FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_LINEARTIME_H
