#ifndef FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_CONTROLLEDCOUNT_H
#define FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_CONTROLLEDCOUNT_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CReactionFrequencyTraits_ControlledCount = 0x2c.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CThingAICreature;

#pragma pack(push, 1)
struct CReactionFrequencyTraits_ControlledCount {
    void*             __vftable;                             // +0x00 vptr, or first dword of a flattened base subobject
    bool              AllowIndividualRepeats;                // +0x04
    unsigned char     _pad_0x05[0x3];                        // +0x05
    CThingAICreature* PLastReactionCreature;                 // +0x08
    bool              InRisingPhase;                         // +0x0c
    unsigned char     _pad_0x0d[0x3];                        // +0x0d
    unsigned long     MinGapFrames;                          // +0x10
    float             CountRechargePerFrame;                 // +0x14
    float             CurrentAvailableCount;                 // +0x18
    float             MaxCount;                              // +0x1c
    float             InvMaxCount;                           // +0x20
    unsigned long     FrameLastStarted;                      // +0x24
    unsigned long     FrameLastRecharged;                    // +0x28
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CReactionFrequencyTraits_ControlledCount) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, AllowIndividualRepeats) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, PLastReactionCreature) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, InRisingPhase) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, MinGapFrames) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, CountRechargePerFrame) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, CurrentAvailableCount) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, MaxCount) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, InvMaxCount) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, FrameLastStarted) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CReactionFrequencyTraits_ControlledCount, FrameLastRecharged) == 0x28);

#endif // FABLE_ENGINE_CREACTIONFREQUENCYTRAITS_CONTROLLEDCOUNT_H
