#ifndef FABLE_ENGINE_CSCRIPTTHING_H
#define FABLE_ENGINE_CSCRIPTTHING_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CScriptThing = 0xc.
// Retail evidence: 62 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CCPPointerInfo;

#pragma pack(push, 1)
struct CScriptThing {
    void*           __vftable;                               // +0x00 vptr, or first dword of a flattened base subobject
    CScriptThing*   PImp_Data;                               // +0x04 CCountedPointer<CScriptThing>::Data
    CCPPointerInfo* PImp_Info;                               // +0x08 CCountedPointer<CScriptThing>::Info
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CScriptThing) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CScriptThing, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CScriptThing, PImp_Data) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CScriptThing, PImp_Info) == 0x8);

#endif // FABLE_ENGINE_CSCRIPTTHING_H
