#ifndef FABLE_ENGINE_CSCRIPTGAMERESOURCEOBJECTSCRIPTEDTHING_H
#define FABLE_ENGINE_CSCRIPTGAMERESOURCEOBJECTSCRIPTEDTHING_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CScriptGameResourceObjectScriptedThing = 0x28.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CGameScriptInterface;

#pragma pack(push, 1)
struct CScriptGameResourceObjectScriptedThing {
    void*                 __vftable;                         // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char         _pad_0x04[0x4];                    // +0x04
    unsigned char         _pad_0x08[0x4];                    // +0x08
    unsigned char         _pad_0x0c[0x4];                    // +0x0c
    CGameScriptInterface* ScriptInterface;                   // +0x10
    unsigned char         PThing[0x8];                       // +0x14 CIntelligentPointer<CThing>
    long                  ScriptID;                          // +0x1c
    bool                  NullResource;                      // +0x20
    unsigned char         _pad_0x21[0x3];                    // +0x21
    long                  ActionPriority;                    // +0x24
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CScriptGameResourceObjectScriptedThing) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, ScriptInterface) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, PThing) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, ScriptID) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, NullResource) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CScriptGameResourceObjectScriptedThing, ActionPriority) == 0x24);

#endif // FABLE_ENGINE_CSCRIPTGAMERESOURCEOBJECTSCRIPTEDTHING_H
