#ifndef FABLE_ENGINE_CSTREAMINGFONTDATABANKENTRY_H
#define FABLE_ENGINE_CSTREAMINGFONTDATABANKENTRY_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CStreamingFontDataBankEntry = 0x18.
// Retail evidence: 2 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CStreamingFontDataBank;

#pragma pack(push, 1)
struct CStreamingFontDataBankEntry {
    void*                   __vftable;                       // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char           Font[0x8];                       // +0x04 CCountedPointer<CFontBank>
    CStreamingFontDataBank* Bank;                            // +0x0c
    unsigned long           Index;                           // +0x10
    unsigned long           DataType;                        // +0x14
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CStreamingFontDataBankEntry) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CStreamingFontDataBankEntry, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CStreamingFontDataBankEntry, Font) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CStreamingFontDataBankEntry, Bank) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CStreamingFontDataBankEntry, Index) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CStreamingFontDataBankEntry, DataType) == 0x14);

#endif // FABLE_ENGINE_CSTREAMINGFONTDATABANKENTRY_H
