#ifndef FABLE_ENGINE_CTCBUYABLEHOUSE_H
#define FABLE_ENGINE_CTCBUYABLEHOUSE_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCBuyableHouse = 0x4c.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CDefPointeeBase;

#pragma pack(push, 1)
struct CTCBuyableHouse {
    void*            __vftable;                              // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char    _pad_0x04[0x4];                         // +0x04
    unsigned char    _pad_0x08[0x4];                         // +0x08
    CDefPointeeBase* PDef_Object;                            // +0x0c CDefPointer<CBuyableHouseDef_const_>::Object
    bool             IsScripted;                             // +0x10
    bool             OwnedByPlayer;                          // +0x11
    bool             Rented;                                 // +0x12
    unsigned char    _pad_0x13[0x1];                         // +0x13
    long             DaySomeoneWillMoveIn;                   // +0x14
    long             DayNextRentIsDue;                       // +0x18
    long             CurrentDressLevel;                      // +0x1c
    long             MaxDressLevel;                          // +0x20
    unsigned char    MainSignPost[0x8];                      // +0x24 CIntelligentPointer<CThing>
    unsigned char    DressingSignPost[0x8];                  // +0x2c CIntelligentPointer<CThing>
    long             FrameToNextCheckIfWeNeedToCreateAnything; // +0x34
    unsigned char    WifeLivingHere[0x8];                    // +0x38 CIntelligentPointer<CThing>
    bool             InitiallySetupDressLevel;               // +0x40
    unsigned char    _pad_0x41[0x3];                         // +0x41
    long             VirtualMoneyBags;                       // +0x44
    bool             HasPreviouslyBeenBuyable;               // +0x48
    bool             IsResidential;                          // +0x49
    unsigned char    _pad_0x4a[0x2];                         // +0x4a
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCBuyableHouse) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, PDef_Object) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, IsScripted) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, OwnedByPlayer) == 0x11);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, Rented) == 0x12);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, DaySomeoneWillMoveIn) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, DayNextRentIsDue) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, CurrentDressLevel) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, MaxDressLevel) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, MainSignPost) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, DressingSignPost) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, FrameToNextCheckIfWeNeedToCreateAnything) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, WifeLivingHere) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, InitiallySetupDressLevel) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, VirtualMoneyBags) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, HasPreviouslyBeenBuyable) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CTCBuyableHouse, IsResidential) == 0x49);

#endif // FABLE_ENGINE_CTCBUYABLEHOUSE_H
