#ifndef FABLE_ENGINE_CTCCREATUREGROUPBOASTINGCROWD_H
#define FABLE_ENGINE_CTCCREATUREGROUPBOASTINGCROWD_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCCreatureGroupBoastingCrowd = 0x4c.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CTCCreatureGroupBoastingCrowd {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char PHero[0x8];                                // +0x28 CIntelligentPointer<CThing>
    unsigned char CrowdState[0x4];                           // +0x30 EBoastingCrowdState
    unsigned char CurrentEncouragementState[0x4];            // +0x34 EBoastingCrowdState
    bool          HeroBoasted;                               // +0x38
    bool          HeroMadeGoodBoast;                         // +0x39
    unsigned char _pad_0x3a[0x2];                            // +0x3a
    long          CurrentOpinionDeedHandle;                  // +0x3c
    long          HeroOpinionSourcesPushed;                  // +0x40
    long          FrameToClearRemainingOpinionSources;       // +0x44
    long          FrameToLeavePostBoastState;                // +0x48
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCCreatureGroupBoastingCrowd) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, PHero) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, CrowdState) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, CurrentEncouragementState) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, HeroBoasted) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, HeroMadeGoodBoast) == 0x39);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, CurrentOpinionDeedHandle) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, HeroOpinionSourcesPushed) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, FrameToClearRemainingOpinionSources) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureGroupBoastingCrowd, FrameToLeavePostBoastState) == 0x48);

#endif // FABLE_ENGINE_CTCCREATUREGROUPBOASTINGCROWD_H
