#ifndef FABLE_ENGINE_CTCCREATUREOPINIONOFHERO_H
#define FABLE_ENGINE_CTCCREATUREOPINIONOFHERO_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCCreatureOpinionOfHero = 0x65c.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CTCCreatureOpinionOfHero {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    long          LastOpinionReactionFrame;                  // +0x0c
    float         NumberOfTimesHit;                          // +0x10
    float         ToleranceToBeingHitOverride;               // +0x14
    long          FrameToDecayNumberOfTimesHit;              // +0x18
    unsigned char PDef[0x4];                                 // +0x1c CDefPointer<COpinionOfHeroDef_const_>
    unsigned char PPersonalityDef[0x4];                      // +0x20 CDefPointer<COpinionPersonalityDef_const_>
    unsigned char AttitudeMask[0x14];                        // +0x24 vector<bool,std::allocator<bool>_>
    unsigned char ReactionMask[0x14];                        // +0x38 vector<bool,std::allocator<bool>_>
    unsigned char DeedMask[0x14];                            // +0x4c vector<bool,std::allocator<bool>_>
    unsigned char RelativeOpinion[0x10];                     // +0x60 COpinionSet
    unsigned char PendingDeeds[0xc];                         // +0x70 list<long,std::allocator<long>_>
    long          LastFrameAppliedDeedEffect[92];            // +0x7c
    unsigned char KnownDeeds[0x450];                         // +0x1ec list<long,std::allocator<long>_>[92]
    unsigned char TransientOffsets[0xc];                     // +0x63c list<COpinionTransientOffset,std::allocator<COpinionTransientOffset>_>
    unsigned char ForcedAttitude[0x4];                       // +0x648 EOpinionAttitudeType
    bool          InteractedFlag;                            // +0x64c
    bool          GreetedFlag;                               // +0x64d
    bool          HeroOpinionEnemy;                          // +0x64e
    bool          InFindAGuardAndYellForHelp;                // +0x64f
    unsigned char PUnknownThreatOpinionSource[0x8];          // +0x650 CIntelligentPointer<CThing>
    long          FrameLastUpdatedUnknownThreat;             // +0x658
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCCreatureOpinionOfHero) == 0x65c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, LastOpinionReactionFrame) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, NumberOfTimesHit) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, ToleranceToBeingHitOverride) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, FrameToDecayNumberOfTimesHit) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, PDef) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, PPersonalityDef) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, AttitudeMask) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, ReactionMask) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, DeedMask) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, RelativeOpinion) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, PendingDeeds) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, LastFrameAppliedDeedEffect) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, KnownDeeds) == 0x1ec);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, TransientOffsets) == 0x63c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, ForcedAttitude) == 0x648);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, InteractedFlag) == 0x64c);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, GreetedFlag) == 0x64d);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, HeroOpinionEnemy) == 0x64e);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, InFindAGuardAndYellForHelp) == 0x64f);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, PUnknownThreatOpinionSource) == 0x650);
FABLE_STATIC_ASSERT(offsetof(CTCCreatureOpinionOfHero, FrameLastUpdatedUnknownThreat) == 0x658);

#endif // FABLE_ENGINE_CTCCREATUREOPINIONOFHERO_H
