#ifndef FABLE_ENGINE_CTCLOOK_H
#define FABLE_ENGINE_CTCLOOK_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCLook = 0xd4.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CAnimationEntry;
struct CPrimitive;
struct CThingCreatureBase;

#pragma pack(push, 1)
struct CTCLook {
    void*               __vftable;                           // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char       _base_0x04[0xc];                     // +0x04 flattened base-class subobject(s)
    CThingCreatureBase* PParentCreature;                     // +0x10
    unsigned char       PDef[0x4];                           // +0x14 CDefPointer<CLookDef_const_>
    unsigned char       PAppearanceDef[0x4];                 // +0x18 CDefPointer<CAppearanceDef_const_>
    float               RecoveryAngleToLookAtXY;             // +0x1c
    float               RecoveryAngleToLookAtYZ;             // +0x20
    float               BodyAngleXY;                         // +0x24
    float               BodyAngleYZ;                         // +0x28
    float               HeadAngleRelToBodyXY;                // +0x2c
    float               HeadAngleRelToBodyYZ;                // +0x30
    float               EyeAnglesRelToHeadXY;                // +0x34
    float               EyeAnglesRelToHeadYZ;                // +0x38
    long                LookTimer;                           // +0x3c
    bool                UsingOldStyleTurning;                // +0x40
    bool                TurningViaAnimationDisable;          // +0x41
    unsigned char       _pad_0x42[0x2];                      // +0x42
    float               FractionOfTurningToAcceptEachFrame;  // +0x44
    long                HeadTurnState;                       // +0x48
    long                BodyTurnState;                       // +0x4c
    bool                CanTurnBody;                         // +0x50
    unsigned char       _pad_0x51[0x3];                      // +0x51
    float               BodyVelocityXY;                      // +0x54
    float               BodyVelocityYZ;                      // +0x58
    float               HeadVelocityXY;                      // +0x5c
    float               HeadVelocityYZ;                      // +0x60
    long                LookFlags;                           // +0x64
    unsigned char       PosToLookAt[0xc];                    // +0x68 C3DVector
    unsigned char       DirectionToLookIn[0xc];              // +0x74 C3DVector
    bool                EyeAnglesChanged;                    // +0x80
    unsigned char       _pad_0x81[0x3];                      // +0x81
    CPrimitive*         LeftEyePrimitive;                    // +0x84
    CPrimitive*         RightEyePrimitive;                   // +0x88
    unsigned char       TurningAnims[0x10];                  // +0x8c vector<std::pair<float,CAnimationEntry_const_*>,std::allocator<std::pair<float,CAnimationEntry_const_*>_>_>
    float               TurningViaAnimMinAngle;              // +0x9c
    CAnimationEntry*    PCurrentTurningAnim;                 // +0xa0
    bool                TargetAcquired;                      // +0xa4
    unsigned char       CachedHeadPos[0xf];                  // +0xa5 C3DVector
    long                HeadCacheTimer;                      // +0xb4
    long                TimeToStopLooking;                   // +0xb8
    bool                OneFrameDelay;                       // +0xbc
    unsigned char       _pad_0xbd[0x3];                      // +0xbd
    unsigned char       PHeadTurnAnimH[0x8];                 // +0xc0 CCountedPointer<NAnimationEntryBodge::CAnimEntryLite>
    unsigned char       PHeadTurnAnimV[0x8];                 // +0xc8 CCountedPointer<NAnimationEntryBodge::CAnimEntryLite>
    bool                FirstTimeThrough;                    // +0xd0
    unsigned char       _pad_0xd1[0x3];                      // +0xd1
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCLook) == 0xd4);
FABLE_STATIC_ASSERT(offsetof(CTCLook, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PParentCreature) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PDef) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PAppearanceDef) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CTCLook, RecoveryAngleToLookAtXY) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, RecoveryAngleToLookAtYZ) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CTCLook, BodyAngleXY) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CTCLook, BodyAngleYZ) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadAngleRelToBodyXY) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadAngleRelToBodyYZ) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CTCLook, EyeAnglesRelToHeadXY) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CTCLook, EyeAnglesRelToHeadYZ) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTCLook, LookTimer) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, UsingOldStyleTurning) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTCLook, TurningViaAnimationDisable) == 0x41);
FABLE_STATIC_ASSERT(offsetof(CTCLook, FractionOfTurningToAcceptEachFrame) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadTurnState) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CTCLook, BodyTurnState) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, CanTurnBody) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CTCLook, BodyVelocityXY) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CTCLook, BodyVelocityYZ) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadVelocityXY) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadVelocityYZ) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CTCLook, LookFlags) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PosToLookAt) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CTCLook, DirectionToLookIn) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CTCLook, EyeAnglesChanged) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CTCLook, LeftEyePrimitive) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CTCLook, RightEyePrimitive) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CTCLook, TurningAnims) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, TurningViaAnimMinAngle) == 0x9c);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PCurrentTurningAnim) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CTCLook, TargetAcquired) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CTCLook, CachedHeadPos) == 0xa5);
FABLE_STATIC_ASSERT(offsetof(CTCLook, HeadCacheTimer) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(CTCLook, TimeToStopLooking) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CTCLook, OneFrameDelay) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PHeadTurnAnimH) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CTCLook, PHeadTurnAnimV) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CTCLook, FirstTimeThrough) == 0xd0);

#endif // FABLE_ENGINE_CTCLOOK_H
