#ifndef FABLE_ENGINE_CTCPHYSICSSTANDARD_H
#define FABLE_ENGINE_CTCPHYSICSSTANDARD_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCPhysicsStandard = 0x88.
// Retail evidence: 3 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CThingPhysicsMeshInfo;

#pragma pack(push, 1)
struct CTCPhysicsStandard {
    void*                  __vftable;                        // +0x00 vptr, or first dword of a flattened base subobject
    long                   owner;                            // +0x04 retail-only (previous header)
    unsigned char          _pad_0x08[0x4];                   // +0x08
    long                   ground;                           // +0x0c retail-only (previous header)
    unsigned char          _pad_0x10[0x4];                   // +0x10
    unsigned char          _pad_0x14[0x4];                   // +0x14
    unsigned char          _pad_0x18[0x4];                   // +0x18
    unsigned char          _pad_0x1c[0x4];                   // +0x1c
    unsigned char          _pad_0x20[0x4];                   // +0x20
    unsigned char          _pad_0x24[0x4];                   // +0x24
    unsigned char          _pad_0x28[0x4];                   // +0x28
    unsigned char          _pad_0x2c[0x4];                   // +0x2c
    unsigned char          _pad_0x30[0x4];                   // +0x30
    unsigned char          _pad_0x34[0x4];                   // +0x34
    unsigned char          _pad_0x38[0x4];                   // +0x38
    unsigned char          _pad_0x3c[0x4];                   // +0x3c
    CThingPhysicsMeshInfo* PPhysicsMeshInfo;                 // +0x40
    float                  OffsetVector3D_X;                 // +0x44 C3DVector::X
    float                  OffsetVector3D_Y;                 // +0x48 C3DVector::Y
    float                  OffsetVector3D_Z;                 // +0x4c C3DVector::Z
    unsigned char          RHSet[0x18];                      // +0x50 CRightHandedSet
    unsigned char          OldRHSet[0x18];                   // +0x68 CRightHandedSet
    long                   RHSetLastFrameSet;                // +0x80
    unsigned char          CollidesWithThings[0x1];          // +0x84 bitfield group: bool:1
    unsigned char          Impassable[0x3];                  // +0x85 bitfield group: bool:1
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCPhysicsStandard) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, owner) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, ground) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, PPhysicsMeshInfo) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, OffsetVector3D_X) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, OffsetVector3D_Y) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, OffsetVector3D_Z) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, RHSet) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, OldRHSet) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, RHSetLastFrameSet) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, CollidesWithThings) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CTCPhysicsStandard, Impassable) == 0x85);

#endif // FABLE_ENGINE_CTCPHYSICSSTANDARD_H
