#ifndef FABLE_ENGINE_CTCQUESTCARD_H
#define FABLE_ENGINE_CTCQUESTCARD_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCQuestCard = 0x34.
// Retail evidence: 1 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CTCQuestCard {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char PDef[0x4];                                 // +0x0c CDefPointer<CQuestCardDef_const_>
    bool          Finished;                                  // +0x10
    bool          Replayable;                                // +0x11
    unsigned char _pad_0x12[0x2];                            // +0x12
    long          FeatIndex;                                 // +0x14
    unsigned char QuestName[0x4];                            // +0x18 CCharString
    unsigned char ObjectiveName[0x4];                        // +0x1c CCharString
    unsigned char RegionName[0x4];                           // +0x20 CCharString
    unsigned char TeleporterRegionName[0x4];                 // +0x24 CCharString
    unsigned char ScriptQuestName[0x4];                      // +0x28 CCharString
    long          GoldReward;                                // +0x2c
    long          RenownReward;                              // +0x30
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCQuestCard) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, PDef) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, Finished) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, Replayable) == 0x11);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, FeatIndex) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, QuestName) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, ObjectiveName) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, RegionName) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, TeleporterRegionName) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, ScriptQuestName) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, GoldReward) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CTCQuestCard, RenownReward) == 0x30);

#endif // FABLE_ENGINE_CTCQUESTCARD_H
