#ifndef FABLE_ENGINE_CTCSPOTLIGHT_H
#define FABLE_ENGINE_CTCSPOTLIGHT_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTCSpotLight = 0x2c.
// Retail evidence: 2 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct CPrimitive;

#pragma pack(push, 1)
struct CTCSpotLight {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char PLightInfo[0x8];                           // +0x10 CCountedPointer<CTCSpotLight::CSpotLightInfo>
    unsigned char PLightDef[0x4];                            // +0x18 CDefPointer<CSpotLightDef_const_>
    bool          Overridden;                                // +0x1c
    unsigned char _pad_0x1d[0x3];                            // +0x1d
    CPrimitive*   LightPrimitive;                            // +0x20
    float         AccumilativeFlickerFactor;                 // +0x24
    float         OldAccumilativeFlickerFactor;              // +0x28
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTCSpotLight) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, PLightInfo) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, PLightDef) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, Overridden) == 0x1c);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, LightPrimitive) == 0x20);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, AccumilativeFlickerFactor) == 0x24);
FABLE_STATIC_ASSERT(offsetof(CTCSpotLight, OldAccumilativeFlickerFactor) == 0x28);

#endif // FABLE_ENGINE_CTCSPOTLIGHT_H
