#ifndef FABLE_ENGINE_CTHINGMULTIARROWSHOTDEF_H
#define FABLE_ENGINE_CTHINGMULTIARROWSHOTDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CThingMultiArrowShotDef = 0x54.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CThingMultiArrowShotDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    float         AccelerationScalar;                        // +0x28
    float         MaxDistance;                               // +0x2c
    float         MaxAngle;                                  // +0x30
    float         TimeToReachTarget;                         // +0x34
    float         MaxAngleToTurnDegs;                        // +0x38
    long          MultiArrowWeaponTrail;                     // +0x3c
    long          MultiArrowHitEffect;                       // +0x40
    long          MultiArrowTrailEffect;                     // +0x44
    float         MultiArrowSpeed;                           // +0x48
    bool          MultiArrowDeflectionByMelee;               // +0x4c
    unsigned char _pad_0x4d[0x3];                            // +0x4d
    float         MultiArrowHitEffectPercentage;             // +0x50
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CThingMultiArrowShotDef) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, AccelerationScalar) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MaxDistance) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MaxAngle) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, TimeToReachTarget) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MaxAngleToTurnDegs) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowWeaponTrail) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowHitEffect) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowTrailEffect) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowSpeed) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowDeflectionByMelee) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CThingMultiArrowShotDef, MultiArrowHitEffectPercentage) == 0x50);

#endif // FABLE_ENGINE_CTHINGMULTIARROWSHOTDEF_H
