#ifndef FABLE_ENGINE_CWEATHERMASK_H
#define FABLE_ENGINE_CWEATHERMASK_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CWeatherMask = 0x5c.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CWeatherMask {
    unsigned char BSphere[0x10];                             // +0x00 C3DBoundingSphere
    unsigned char BBox[0x18];                                // +0x10 C3DBoundingBox
    unsigned char InvTransform[0x30];                        // +0x28 CMatrix3x4
    float         Scale;                                     // +0x58
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CWeatherMask) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CWeatherMask, BSphere) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CWeatherMask, BBox) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CWeatherMask, InvTransform) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CWeatherMask, Scale) == 0x58);

#endif // FABLE_ENGINE_CWEATHERMASK_H
