#ifndef FABLE_ENGINE_CWILLRESPONSEDEF_H
#define FABLE_ENGINE_CWILLRESPONSEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CWillResponseDef = 0x2d.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CWillResponseDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _base_0x04[0x21];                          // +0x04 flattened base-class subobject(s)
    bool          IsForcePushable;                           // +0x25
    bool          IsLifeDrainable;                           // +0x26
    bool          IsLightningable;                           // +0x27
    bool          IsNotBloodyWillable;                       // +0x28
    bool          IsAffectedBySlowTime;                      // +0x29
    bool          IsAbleToBeLifted;                          // +0x2a
    bool          IsEpicPowerExplodable;                     // +0x2b
    bool          IsEpicSpellable;                           // +0x2c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CWillResponseDef) == 0x2d);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsForcePushable) == 0x25);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsLifeDrainable) == 0x26);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsLightningable) == 0x27);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsNotBloodyWillable) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsAffectedBySlowTime) == 0x29);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsAbleToBeLifted) == 0x2a);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsEpicPowerExplodable) == 0x2b);
FABLE_STATIC_ASSERT(offsetof(CWillResponseDef, IsEpicSpellable) == 0x2c);

#endif // FABLE_ENGINE_CWILLRESPONSEDEF_H
