#ifndef FABLE_ENGINE_LHHTTP2_H
#define FABLE_ENGINE_LHHTTP2_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof LHHttp2 = 0x1104.
// Retail evidence: 0 trusted landed function(s); reconciliation clean.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

struct LHHttpDocumentParts;
struct LSocket;

#pragma pack(push, 1)
struct LHHttp2 {
    LSocket*             Host;                               // +0x00
    unsigned char        Hostname[0x1c];                     // +0x04 basic_string<char,std::char_traits<char>,std::allocator<char>_>
    unsigned short       Port;                               // +0x20
    unsigned char        _pad_0x22[0x2];                     // +0x22
    unsigned char        PreparedRequest[0x1c];              // +0x24 basic_string<char,std::char_traits<char>,std::allocator<char>_>
    unsigned long        RequestBytesSent;                   // +0x40
    unsigned long        RequestLength;                      // +0x44
    unsigned char        MyHeaders[0x2c];                    // +0x48 LHHttpHeaders
    unsigned char        ReceivedHeaders[0x2c];              // +0x74 LHHttpHeaders
    unsigned long        TimeOutValue;                       // +0xa0
    unsigned long        ActionStartTime;                    // +0xa4
    bool                 ActionStarted;                      // +0xa8
    unsigned char        _pad_0xa9[0x1];                     // +0xa9
    unsigned short       CurrentAction;                      // +0xaa
    unsigned long        CurrDownSize;                       // +0xac
    unsigned long        Forwardings;                        // +0xb0
    unsigned long        CurrForwarding;                     // +0xb4
    char                 CurrentHeaderPart[2048];            // +0xb8
    unsigned long        CurrentHeaderPos;                   // +0x8b8
    unsigned char        ProxyHost[0x1c];                    // +0x8bc basic_string<char,std::char_traits<char>,std::allocator<char>_>
    unsigned long        ProxyPort;                          // +0x8d8
    unsigned char        DocumentParts[0x10];                // +0x8dc vector<LHNetworkLib::LHHttpDocumentParts_*,std::allocator<LHNetworkLib::LHHttpDocumentParts_*>_>
    unsigned char        DocumentEncoding[0x4];              // +0x8ec HTTP_TRANSFER_ENCODING
    unsigned long        DocumentEstimatedLength;            // +0x8f0
    unsigned long        DocumentLength;                     // +0x8f4
    char                 CurrentDocumentPart[2048];          // +0x8f8
    unsigned long        CurrentDocumentPos;                 // +0x10f8
    bool                 InChunkMode;                        // +0x10fc
    unsigned char        _pad_0x10fd[0x3];                   // +0x10fd
    LHHttpDocumentParts* CurrentDocumentChunk;               // +0x1100
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(LHHttp2) == 0x1104);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, Host) == 0x0);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, Hostname) == 0x4);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, Port) == 0x20);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, PreparedRequest) == 0x24);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, RequestBytesSent) == 0x40);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, RequestLength) == 0x44);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, MyHeaders) == 0x48);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, ReceivedHeaders) == 0x74);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, TimeOutValue) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, ActionStartTime) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, ActionStarted) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentAction) == 0xaa);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrDownSize) == 0xac);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, Forwardings) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrForwarding) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentHeaderPart) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentHeaderPos) == 0x8b8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, ProxyHost) == 0x8bc);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, ProxyPort) == 0x8d8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, DocumentParts) == 0x8dc);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, DocumentEncoding) == 0x8ec);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, DocumentEstimatedLength) == 0x8f0);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, DocumentLength) == 0x8f4);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentDocumentPart) == 0x8f8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentDocumentPos) == 0x10f8);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, InChunkMode) == 0x10fc);
FABLE_STATIC_ASSERT(offsetof(LHHttp2, CurrentDocumentChunk) == 0x1100);

#endif // FABLE_ENGINE_LHHTTP2_H
