class CScriptThing;

class CCharString
{
public:
    CCharString(const char* s, int n);
    ~CCharString();
};

class CGameScriptInterface
{
public:
    virtual void Pad0();
    virtual void Pad1();
    virtual void Pad2();
    virtual void Pad3();
    virtual void Pad4();
    virtual void Pad5();
    virtual void Pad6();
    virtual void Pad7();
    virtual void Pad8();
    virtual void Pad9();
    virtual void Pad10();
    virtual void Pad11();
    virtual void Pad12();
    virtual void Pad13();
    virtual void Pad14();
    virtual void Pad15();
    virtual void Pad16();
    virtual void Pad17();
    virtual void Pad18();
    virtual void Pad19();
    virtual void Pad20();
    virtual void Pad21();
    virtual void Pad22();
    virtual void Pad23();
    virtual void Pad24();
    virtual void Pad25();
    virtual void Pad26();
    virtual void Pad27();
    virtual void Pad28();
    virtual void Pad29();
    virtual void Pad30();
    virtual void Pad31();
    virtual void Pad32();
    virtual void Pad33();
    virtual void Pad34();
    virtual void Pad35();
    virtual void Pad36();
    virtual void Pad37();
    virtual void Pad38();
    virtual void Pad39();
    virtual void Pad40();
    virtual void Pad41();
    virtual void Pad42();
    virtual void Pad43();
    virtual void Pad44();
    virtual void Pad45();
    virtual void Pad46();
    virtual void Pad47();
    virtual void Pad48();
    virtual void Pad49();
    virtual void Pad50();
    virtual void Pad51();
    virtual void Pad52();
    virtual void Pad53();
    virtual void Pad54();
    virtual void Pad55();
    virtual void Pad56();
    virtual void Pad57();
    virtual void Pad58();
    virtual void Pad59();
    virtual void Pad60();
    virtual void Pad61();
    virtual void Pad62();
    virtual void Pad63();
    virtual void Pad64();
    virtual void Pad65();
    virtual void Pad66();
    virtual void Pad67();
    virtual void Pad68();
    virtual void Pad69();
    virtual void Pad70();
    virtual void Pad71();
    virtual void Pad72();
    virtual void Pad73();
    virtual void Pad74();
    virtual void Pad75();
    virtual void Pad76();
    virtual void Pad77();
    virtual void Pad78();
    virtual void Pad79();
    virtual void Pad80();
    virtual void Pad81();
    virtual void Pad82();
    virtual void Pad83();
    virtual void Pad84();
    virtual void Pad85();
    virtual void Pad86();
    virtual void Pad87();
    virtual void Pad88();
    virtual void Pad89();
    virtual void Pad90();
    virtual void Pad91();
    virtual void Pad92();
    virtual void Pad93();
    virtual void Pad94();
    virtual void Pad95();
    virtual void Pad96();
    virtual void Pad97();
    virtual void Pad98();
    virtual void Pad99();
    virtual void Pad100();
    virtual void Pad101();
    virtual void Pad102();
    virtual void Pad103();
    virtual void Pad104();
    virtual void Pad105();
    virtual void Pad106();
    virtual void Pad107();
    virtual void Pad108();
    virtual void Pad109();
    virtual void Pad110();
    virtual void Pad111();
    virtual void Pad112();
    virtual void Pad113();
    virtual void Pad114();
    virtual void Pad115();
    virtual void Pad116();
    virtual void Pad117();
    virtual void Pad118();
    virtual void Pad119();
    virtual void Pad120();
    virtual void Pad121();
    virtual void Pad122();
    virtual void Pad123();
    virtual void Pad124();
    virtual void Pad125();
    virtual void Pad126();
    virtual void Pad127();
    virtual void Pad128();
    virtual void Pad129();
    virtual void Pad130();
    virtual void Pad131();
    virtual void Pad132();
    virtual void Pad133();
    virtual void Pad134();
    virtual void Pad135();
    virtual void Pad136();
    virtual void Pad137();
    virtual void Pad138();
    virtual void Pad139();
    virtual void Pad140();
    virtual void Pad141();
    virtual void Pad142();
    virtual void Pad143();
    virtual void Pad144();
    virtual void Pad145();
    virtual void Pad146();
    virtual void Pad147();
    virtual void Pad148();
    virtual void Pad149();
    virtual void Pad150();
    virtual void Pad151();
    virtual void Pad152();
    virtual void Pad153();
    virtual void Pad154();
    virtual void Pad155();
    virtual void Pad156();
    virtual void Pad157();
    virtual void Pad158();
    virtual void Pad159();
    virtual void Pad160();
    virtual void Pad161();
    virtual void Pad162();
    virtual void Pad163();
    virtual void Pad164();
    virtual void Pad165();
    virtual void Pad166();
    virtual void Pad167();
    virtual void Pad168();
    virtual void Pad169();
    virtual void Pad170();
    virtual void Pad171();
    virtual void Pad172();
    virtual void Pad173();
    virtual void Pad174();
    virtual void Pad175();
    virtual void Pad176();
    virtual void Pad177();
    virtual void Pad178();
    virtual void Pad179();
    virtual void Pad180();
    virtual void Pad181();
    virtual void Pad182();
    virtual void Pad183();
    virtual void Pad184();
    virtual void Pad185();
    virtual void Pad186();
    virtual void Pad187();
    virtual void Pad188();
    virtual void Pad189();
    virtual void Pad190();
    virtual void Pad191();
    virtual void Pad192();
    virtual void Pad193();
    virtual void Pad194();
    virtual void Pad195();
    virtual void Pad196();
    virtual void Pad197();
    virtual void Pad198();
    virtual void Pad199();
    virtual void Pad200();
    virtual void Pad201();
    virtual void Pad202();
    virtual void Pad203();
    virtual void Pad204();
    virtual void Pad205();
    virtual void Pad206();
    virtual void Pad207();
    virtual void Pad208();
    virtual void Pad209();
    virtual void Pad210();
    virtual void Pad211();
    virtual void Pad212();
    virtual void Pad213();
    virtual void Pad214();
    virtual void Pad215();
    virtual void Pad216();
    virtual void Pad217();
    virtual void Pad218();
    virtual void Pad219();
    virtual void Pad220();
    virtual void Pad221();
    virtual void Pad222();
    virtual void Pad223();
    virtual void Slot380(const CScriptThing& thing, const CCharString& string, const CCharString& slot) const;
    void GiveThingItemInHand(const CScriptThing& thing, const CCharString& string, bool right_hand) const;
};

void CGameScriptInterface::GiveThingItemInHand(const CScriptThing& thing, const CCharString& string, bool right_hand) const
{
    if (right_hand)
    {
        CCharString slot("CARRY_SLOT_RIGHT_HAND", -1);
        Slot380(thing, string, slot);
    }
    else
    {
        CCharString slot("CARRY_SLOT_LEFT_HAND", -1);
        Slot380(thing, string, slot);
    }
}