#define FABLE_LANGUAGE_DIRECTORY_FUNCTION \
    FableGetLanguageDirectoryA_0041A120
#define FABLE_LANGUAGE_DIRECTORY_FAIL \
    "FABLETLC_LANGUAGE_DIRECTORY_A_BEHAVIOR FAIL"
#define FABLE_LANGUAGE_DIRECTORY_PASS \
    "FABLETLC_LANGUAGE_DIRECTORY_A_BEHAVIOR PASS"
#include "LanguageDirectory_test.inl"
