#define FABLE_LANGUAGE_DIRECTORY_FUNCTION \
    FableGetLanguageDirectoryB_0041A330
#define FABLE_LANGUAGE_DIRECTORY_FAIL \
    "FABLETLC_LANGUAGE_DIRECTORY_B_BEHAVIOR FAIL"
#define FABLE_LANGUAGE_DIRECTORY_PASS \
    "FABLETLC_LANGUAGE_DIRECTORY_B_BEHAVIOR PASS"
#include "LanguageDirectory_test.inl"
