-- Lifted draft of retail QS_ScytheInfo (allocator 0x00E2AB00).
-- Generated by tools/script_recovery/lift_native_lua.py; every TODO(native) needs a human.
Quest = nil

function Init(questObject)
    Quest = questObject
    -- TODO(native): name field 0x48 (undefined1)
    Quest:SetStateBool("self_0x48", false)
end

function Main(questObject)
    Quest = questObject
    local bVar7, iVar6
    local alive = true
    Quest:AddEntityBinding("ScytheMarker", "ScytheInfo/Entities/ScytheMarker")
    Quest:AddEntityBinding("ScytheNearOracle", "ScytheInfo/Entities/ScytheNearOracle")
    Quest:FinalizeEntityBindings()
    local ppVar4 = Quest:GetActiveQuestName()
    Quest:SetQuestCardObjective(ppVar4, "TEXT_QUEST_AWAKEN_ORACLE_OBJECTIVE_03", "TEXT_QUEST_AWAKEN_ORACLE_OBJECTIVE_03", "")
    local uVar5 = Quest:RegisterTimer()
    Quest:SetTimer(uVar5, 100)
    local cVar2 = Quest:IsRegionLoaded("NorthernWastes2")
    while cVar2 do
        alive = Quest:NewScriptFrame()
        bVar7 = not alive
        if bVar7 then return end  -- TODO(native): goto LAB_00e29db9
        iVar6 = Quest:GetTimer(uVar5)
        if iVar6 == 0 then
            bVar7 = not alive
            if bVar7 then return end  -- TODO(native): goto LAB_00e29e58
            Quest:HeroReceiveMessageFromGuildMaster("TEXT_QST_B03_SCYTHE_RETURN_TO_SNOWSPIRE_REMINDER_10", "", nil --[[missing]], nil --[[missing]])
            Quest:SetTimer(uVar5, 100)
        end
        cVar2 = Quest:IsRegionLoaded("NorthernWastes2")
    end
    bVar7 = not alive
    if bVar7 then
        -- LAB_00e29db0: (native jump target)
        -- LAB_00e29db9: (native jump target)
        Quest:DeregisterTimer(uVar5)
        return
    end
    local CVar1 = Quest:GetStateBool("self_0x48")
    repeat
        if CVar1 then
            bVar7 = not alive
            if not bVar7 then
                ppVar4 = Quest:GetActiveQuestName()
                Quest:SetQuestAsCompleted(ppVar4, nil --[[missing]], nil --[[missing]], nil --[[missing]])
                ppVar4 = Quest:GetActiveQuestName()
                Quest:DeactivateQuestLater(ppVar4, nil --[[missing]])
                Quest:FadeScreenIn()
            end
            -- LAB_00e29e58: (native jump target)
            Quest:DeregisterTimer(uVar5)
            return
        end
        alive = Quest:NewScriptFrame()
        bVar7 = not alive
        if bVar7 then return end  -- TODO(native): goto LAB_00e29db0
        CVar1 = Quest:GetStateBool("self_0x48")
    until false
end

function OnPersist(questObject, context)
    Quest = questObject
end

