// Auto-generated from fse_api_manifest.json — feed to Ghidra: File > Parse C Source.
// Opaque forward decls for engine types (real layouts get filled in as RE progresses).

typedef struct CScriptThing CScriptThing;

// --- API prototypes (FSE-reversed engine surface) ---
void AcquireControl(CScriptThing* pMe);
void ReleaseControl(void);
void MoveToThing_NonBlocking(CScriptThing* pMe, void * spTargetThing, float radius, int moveType);
void PlayAnimation_NonBlocking(CScriptThing* pMe, void * animName, void * stayOnLastFrame, void * allowLooking);
void PlayLoopingAnimation_NonBlocking(CScriptThing* pMe, void * animName, int loopCount, void * useMovement, void * allowLooking);
void PlayCombatAnimation_NonBlocking(CScriptThing* pMe, void * animName, void * allowLooking);
void MoveToPosition_NonBlocking(CScriptThing* pMe, sol::table position, float radius, int moveType);
void FollowThing_NonBlocking(CScriptThing* pMe, void * spTargetThing, float distance, bool avoidObstacles);
void ClearCommands_NonBlocking(CScriptThing* pMe);
void StopFollowingThing_NonBlocking(CScriptThing* pMe, void * spTargetThing);
void FollowPreCalculatedRoute_NonBlocking(CScriptThing* pMe, void * spRoute, int moveType, void * avoidObstacles, void * ignorePathPreferability);
void MoveToAndPickUpGenericBox_NonBlocking(CScriptThing* pMe, CScriptThing* pBox, int moveType, void * avoidObstacles);
void DropGenericBox_NonBlocking(CScriptThing* pMe);
void Wait_NonBlocking(CScriptThing* pMe, float seconds);
void WaitForEntityToFinishPerformingTasks_NonBlocking(CScriptThing* pMe, void * spTargetEntity);
void ClearAllActions_NonBlocking(CScriptThing* pMe);
void ClearAllActionsIncludingLoopingAnimations_NonBlocking(CScriptThing* pMe);
void UnsheatheWeapons_NonBlocking(CScriptThing* pMe);
void SummonerLightningOrbAttackTarget_NonBlocking(CScriptThing* pMe, void * spTargetThing);
void FireProjectileWeaponAtTarget_NonBlocking(CScriptThing* pMe, void * spTargetThing);
void Speak_Blocking(CScriptThing* pMe, void * spTargetThing, void * dialogueKey, int selectionMethod, bool makeTargetListen, bool soundIn2D, bool overScreenFade);
void Converse_NonBlocking(CScriptThing* pMe, void * spTargetThing, void * dialogueKey);
void SpeakAndWait(CScriptThing* pMe, void * dialogueKey, int selectionMethod);
void GainControlAndSpeak(CScriptThing* pMe, void * dialogueKey, int selectionMethod);
void MakeBehavioral(CScriptThing* pMe);
void SetReadableText(CScriptThing* pMe, void * textTag);
void TakeExclusiveControl(CScriptThing* pMe);
void MoveToPosition(CScriptThing* pMe, sol::table position, float radius, int moveType);
void MoveToThing(CScriptThing* pMe, void * spTargetThing, float radius, int moveType);
void ClearCommands(CScriptThing* pMe);
void PerformExpression(CScriptThing* pMe, void * spTargetThing, void * expressionName);
void PlayAnimation(CScriptThing* pMe, void * animName, void * waitForFinish, void * stayOnLastFrame, void * allowLooking);
void PlayCombatAnimation(CScriptThing* pMe, void * animName, void * waitForFinish, void * allowLooking);
void PlayLoopingAnimation(CScriptThing* pMe, void * animName, int loopCount, void * waitForFinish, void * useMovement, void * allowLooking);
void MoveToAndPickUpGenericBox(CScriptThing* pMe, CScriptThing* pBox, int moveType, void * avoidObstacles);
void DropGenericBox(CScriptThing* pMe);
void UnsheatheWeapons(CScriptThing* pMe);
void Wait(CScriptThing* pMe, float seconds);
void FollowThing(CScriptThing* pMe, void * spTargetThing, float distance, bool avoidObstacles);
void StopFollowingThing(CScriptThing* pMe, CScriptThing* pTargetThing);
void SetAsUsable(CScriptThing* pMe, bool isUsable);
void SetFriendsWithEverythingFlag(CScriptThing* pMe, bool isFriends);
void SetActivationTriggerStatus(CScriptThing* pMe, bool isActive);
void SetToKillOnLevelUnload(CScriptThing* pMe, bool shouldKill);
bool IsFollowActionRunning_NonBlocking(CScriptThing* pMe, sol::object target_obj);
bool IsPerformingScriptTask(void);
bool IsTalkedToByHero(CScriptThing* pMe);
bool IsNull(CScriptThing* pMe);
bool IsKilledByHero(CScriptThing* pMe);
bool IsAwareOfHero(CScriptThing* pMe);
bool IsAlive(CScriptThing* pMe);
bool IsDead(CScriptThing* pMe);
bool IsFollowActionRunning(CScriptThing* pMe, CScriptThing* pTargetThing);
bool IsFollowingThing(CScriptThing* pMe);
bool IsUnconscious(CScriptThing* pMe);
bool IsOpenDoor(CScriptThing* pMe);
bool IsSneaking(CScriptThing* pMe);
bool MsgIsHitByHeroWithFlourish(CScriptThing* pMe);
bool MsgIsHitByHeroWithDecapitate(CScriptThing* pMe);
bool MsgIsHitByHeroWithWeapon(CScriptThing* pMe, void * weaponName);
bool MsgIsUsedByHero(CScriptThing* pMe);
bool MsgIsTriggeredByHero(CScriptThing* pMe);
bool MsgIsKnockedOutByHero(CScriptThing* pMe);
bool MsgPerformedSpecialAbility(CScriptThing* pMe, int abilityEnum);
bool MsgPerformedAnySpecialAbility(CScriptThing* pMe);
bool MsgPerformedAnyAggressiveSpecialAbility(CScriptThing* pMe);
bool MsgPerformedAnyNonAggressiveSpecialAbility(CScriptThing* pMe);
bool MsgReceivedInventoryItem(CScriptThing* pMe);
bool MsgIsHitByHeroSpecialAbility(CScriptThing* pMe, int abilityEnum);
bool MsgOpenedChest(CScriptThing* pMe);
bool MsgIsKicked(CScriptThing* pMe);
bool MsgIsPresentedWithItem(CScriptThing* pMe, sol::this_state s);
bool MsgIsHitByHero(CScriptThing* pMe);
bool MsgIsHitByAnySpecialAbilityFromHero(CScriptThing* pMe);
bool MsgIsHitByHealLifeFromHero(CScriptThing* pMe);
bool MsgIsKilledBy(CScriptThing* pMe, void * killerName);
void * GetDataString(CScriptThing* pMe);
void * GetCurrentMapName(CScriptThing* pMe);
void * GetHomeMapName(CScriptThing* pMe);
void * GetDefName(CScriptThing* pMe);
sol::table GetPos(CScriptThing* pMe, sol::this_state s);
sol::table GetHomePos(CScriptThing* pMe, sol::this_state s);
void * MsgWhoKilledMe(CScriptThing* pMe);
void * MsgWhoHitMe(CScriptThing* pMe);
sol::object MsgIsHitByHeroWithProjectileWeapon(CScriptThing* pMe, sol::this_state s);
sol::object MsgExpressionPerformedTo(CScriptThing* pMe, sol::this_state s);
sol::object MsgReceivedMoney(CScriptThing* pMe, sol::this_state s);
int MsgHowLongWasExpressionPerformed(CScriptThing* pMe);
void Log(void * message);
void CreateThread(void * luaFunctionName, sol::table args);
void ShowMessage(void * message, float duration);
void ActivateQuest(void * questName);
void AddQuestCard(void * questCardObjectName, void * questScriptName, bool replayable, bool skip_GM_message);
void SetHeroGuideShowsQuestCards(bool show);
void GiveQuestCardDirectly(void * textDBEntry, void * questName, bool flag);
void SetQuestGoldReward(void * questName, int amount);
void SetQuestRenownReward(void * questName, int amount);
void SetQuestCardObjective(void * questName, void * objectiveText, void * region1, void * region2);
void KickOffQuestStartScreen(void * questName, bool isStory, bool isGold);
void AddQuestRegion(void * questName, void * regionName);
void DeactivateQuest(void * questName, unsigned int delay);
void Pause(float duration);
void PlayCutscene(void * cutsceneName, sol::table actors);
void FixMovieSequenceCamera(bool isFixed);
void PauseAllNonScriptedEntities(bool isPaused);
void AddEntityBinding(void * entityScriptName, void * scriptFileName);
void FinalizeEntityBindings(void);
void SetCreatureGeneratorsEnabled(void * regionName, bool enabled);
void EntitySetStockItemPrice(CScriptThing* pThing, int price);
void EntitySetAsForSale(CScriptThing* pThing, bool bForSale);
void GiveHeroItem(CScriptThing* pItemThing);
void EntitySetAppearanceSeed(CScriptThing* pThing, unsigned int seed);
void ShowOnScreenMessageWithFont(sol::table position, void * message, sol::table color, void * fontName);
void EntitySetTargetable(CScriptThing* pThing, bool isTargetable);
void EntityTeleportToThing(CScriptThing* pThingToMove, CScriptThing* pTargetThing);
void EntitySetAsDrawable(CScriptThing* pThing, bool isDrawable);
void GiveHeroObject(void * objectDefName, int amount);
void RemoveThing(CScriptThing* pThing);
void EntitySetAllStategroupsEnabled(CScriptThing* pThing, bool enabled);
void SetQuestWorldMapOffset(void * questName, int x, int y);
void EntitySetAsKillable(CScriptThing* pThing, bool isKillable);
void EntitySetOpinionReactionMask(CScriptThing* pThing, void * maskName);
void SetThingHasInformation(CScriptThing* pThing, bool hasInfo);
void EntitySetFacingAngleTowardsThing(CScriptThing* pThing, CScriptThing* pTarget);
void TakeObjectFromHero(void * objectDefName);
void GiveHeroGold(int amount);
void GiveHeroMorality(float amount);
void GiveHeroExperience(int amount);
void ClearThingHasInformation(CScriptThing* pThing);
void FadeScreenOut(float fadeTime, float holdTime);
void FadeScreenIn(void);
void HeroReceiveMessageFromGuildMaster(void * messageKey, void * graphicName, bool highPriority, bool alwaysPlay);
void OverrideMusic(int musicSetType, bool isCutscene, bool forcePlay);
void ShowMessageWithButtons(void * message, void * button1Response, void * button2Response, float displayTime);
void SetTimer(int timerId, int timeValue);
void SetQuestAsFailed(void * questName, bool showScreen, void * wideMessage, bool useWideMessage);
void StopOverrideMusic(bool isCutscene);
void ResetPlayerCreatureCombatMultiplier(void);
void SetQuestAsCompleted(void * questName, bool showScreen, bool updateLogbook, bool showQuestCompleteScreen);
void DeactivateQuestLater(void * questName, unsigned int delayFrames);
void AddRumourCategory(void * categoryName);
void AddNewRumourToCategory(void * categoryName, void * rumourTextKey);
void AddGossipFactionToCategory(void * categoryName, void * factionName);
void EntitySetCutsceneBehaviour(CScriptThing* pThing, int behaviour);
void CameraDefault(void);
void EntitySetInFaction(CScriptThing* pThing, void * factionName);
void SetThingPersistent(CScriptThing* pThing, bool isPersistent);
void EntitySetAsDamageable(CScriptThing* pThing, bool isDamageable);
void EntitySetAsToAddToComboMultiplierWhenHit(CScriptThing* pThing, bool doesAddToCombo);
void SetRegionExitAsActive(CScriptThing* pThing, bool isActive);
void EntityFadeOut(CScriptThing* pThing, float duration);
void OpenDoor(CScriptThing* pThing);
void EntitySetThingAsEnemyOfThing(void * spThing1, void * spThing2);
void ChangeHeroHealthBy(float amount, bool canKill, bool showChange);
void CameraShake(float intensity, float duration);
void GiveHeroAbility(int abilityId, bool give);
void SetBeerRequestPhrase(void * spThing, unsigned int phraseID);
void ResetBeerRequestPhrase(void * spThing);
void SetScriptingStateGroup(void * spThing, int eGroup);
void ResetScriptingStateGroup(void * spThing);
void SetMaxHeroReactionDistance(void * spThing, float distance);
void ResetMaxHeroReactionDistance(void * spThing);
void SetActionFrequency(void * spThing, int frequency);
void ResetActionFrequency(void * spThing);
void SetActionFrequencyVariation(void * spThing, float variation);
void ResetActionFrequencyVariation(void * spThing);
void SetAction(void * spThing, void * action);
void ResetAction(void * spThing);
void SetFaceHeroForAction(void * spThing, bool bFaceHero);
void ResetFaceHeroForAction(void * spThing);
void SetTargetName(void * spThing, void * targetName);
void ResetTargetName(void * spThing);
void SetFollowDistance(void * spThing, float distance);
void ResetFollowDistance(void * spThing);
void SetAttackHeroOnSight(void * spThing, bool bAttack);
void ResetAttackHeroOnSight(void * spThing);
void SetTimeToSpendHarassingHero(void * spThing, int time);
void ResetTimeToSpendHarassingHero(void * spThing);
void SetCombatNearbyEnemyFleeingBreakOffRange(void * spThing, float range);
void ResetCombatNearbyEnemyFleeingBreakOffRange(void * spThing);
void SetCombatNearbyBreakOffRange(void * spThing, float range);
void ResetCombatNearbyBreakOffRange(void * spThing);
void SetStealStealableItems(void * spThing, bool bSteal);
void ResetStealStealableItems(void * spThing);
void SetRecoverStealableItems(void * spThing, bool bRecover);
void ResetRecoverStealableItems(void * spThing);
void SetTakeStealableItemToRandomDestination(void * spThing, bool bRandom);
void ResetTakeStealableItemToRandomDestination(void * spThing);
void SetKillSelfAndStealableItemAfterReachingDestination(void * spThing, bool bKill);
void ResetKillSelfAndStealableItemAfterReachingDestination(void * spThing);
void SetAllowedToFollow(void * spThing, bool bAllowed);
void ResetAllowedToFollow(void * spThing);
void SetTableName(void * spThing, void * tableName);
void ResetTableName(void * spThing);
void SetSeatName(void * spThing, void * seatName);
void ResetSeatName(void * spThing);
void SetDisableHeadLooking(void * spThing, bool bDisabled);
void ResetDisableHeadLooking(void * spThing);
void SetIsPushableByHero(void * spThing, bool bIsPushable);
void ResetIsPushableByHero(void * spThing);
void SetLookForFiniteTime(void * spThing, bool bFinite);
void ResetLookForFiniteTime(void * spThing);
void SetAvoidRegionExits(void * spThing, bool bAvoid);
void ResetAvoidRegionExits(void * spThing);
void SetTargetingDistanceOffset(void * spThing, float offset);
void ResetTargetingDistanceOffset(void * spThing);
void SetPlayerUsingMeleeDummies(bool bIsUsing);
void SetPlayerUsingRangedDummies(bool bIsUsing);
void SetPlayerUsingWillDummies(bool bIsUsing);
void SetCheapHeadLooking(bool bIsCheap);
void SetQuitTavernGame(bool bQuit);
void SetPrizeTavernTable(bool bIsPrize);
void SetBettingActive(bool bIsActive);
void SetBettingAccept(bool bAccept);
void SetBettingAmount(int amount);
void SetCountBetMoneyDown(bool bCount);
void SetSpotTheAdditionBeaten(bool bBeaten);
void SetGlobalTargetingDistanceOffset(float offset);
void SetTradingPriceMult(float mult);
void SetBoastingEnabled(bool bIsEnabled);
void SetActiveGossipCategories(void * category, bool isActive);
void ClearActiveGossipCategories(void);
void ClearIsGossipForPlayer(void);
void SetGossip(void * category, void * rumour, int index);
void ClearGossip(void * category);
void RemoveGossip(void * category);
void AddGossip(void * category);
void DeregisterTimer(int timerId);
void SetStateBool(void * key, bool value);
void SetStateInt(void * key, int value);
void SetStateString(void * key, void * value);
void SetGlobalBool(void * key, bool value);
void SetGlobalInt(void * key, int value);
void SetGlobalString(void * key, void * value);
void ReleaseThing(CScriptThing* pThing);
void LogReceivedPointer(CScriptThing* pThing, void * context);
void StartMovieSequence(void);
void EndMovieSequence(void);
void RemoveConversation(int conversationID, void * cutOffSpeech);
void DontPopulateNextLoadedRegion(void);
void DisplayQuestInfo(bool bDisplay);
void SetQuestInfoName(void * name);
void SetQuestInfoText(void * text);
void UpdateQuestInfoCounter(int elementID, int count, int max);
void AddScreenMessage(void * message, void * selectionMethod);
void ClearAllRumbles(void);
void AddScreenTitleMessage(void * message, float duration, void * bUnknown);
void DisplayGameInfo(void * infoKey);
void DisplayGameInfoText(void * wideText);
void GiveHeroWeapon(void * weaponDefName, bool bEquip);
void SetWeaponAsHerosActiveWeapon(void * weaponDefName);
void SetHeroAbleToGainExperience(bool bCanGain);
void SheatheHeroWeapons(void);
void SetHeroWillAsUsable(bool bIsUsable);
void SetHeroWeaponsAsUsable(bool bIsUsable);
void SetWeaponOutCrimeEnabled(bool bIsEnabled);
void SetGuardsIgnoreCrimes(bool bDoIgnore);
void RemoveAllHeroWeapons(void);
void ConfiscateAllHeroItems(void);
void ConfiscateAllHeroWeapons(void);
void ConfiscateItemsOfTypeFromHero(void * defName);
void ReturnAllConfiscatedItemsToHero(void);
void MakeHeroCarryItemInHand(void * spThing, bool setAsActive, bool setAsPersistent);
void AddTattooToHero(void * tattooDefName);
void SetPlayerCreatureOnlyTarget(void * spTarget);
void ResetPlayerCreatureOnlyTarget(void);
void ChangeHeroMoralityDueToTheft(void);
void ChangeHeroMoralityDueToPicklock(void);
void GiveHeroRenownPoints(int amount);
void IncreaseHeroRenownLevel(void);
void SetHeroAge(float age);
void SetHeroAsTeenager(bool bIsTeen);
void SetHeroAsApprentice(bool bIsApprentice);
void SetHeroWillEnergyLevel(float level);
void SetHeroWillEnergyAsAbleToRefill(bool bCanRefill);
void SetHeroHandLampAsLit(bool bIsLit);
void RemoveHeroClothing(void);
void SetHeroAsWearing(void * clothingDefName);
void ChangeHeroHairstyle(void * hairstyleDefName);
void RemoveHeroHairstyle(void);
void ApplyHeroPenaltyForDeath(void);
void GiveHeroTitle(void * titleKey);
void EntitySetAsMarryable(void * spThing, bool bIsMarryable);
void EntitySetAsAbleToRegionFollowWhenMarried(void * spThing, bool bCanFollow);
void EntityForceMarriageToHero(void * spThing, bool bIsForced);
void SetNumberOfTimesHeroHasHadSex(int count);
void SetHeroAsHavingHadSex(bool bHasHadSex);
void SetHeroAsHavingHadGaySex(bool bHasHadGaySex);
void GiveThingHeroRewardItem(void * spThing, void * pItemDefName, void * pBoneName);
void GiveThingItemInHand(void * spThing, void * pItemDefName, bool bShow);
void GiveThingItemInSlot(void * spThing, void * pItemDefName, void * pSlotName);
void GiveHeroExpression(void * pExpressionName, int level, void * bShowPopup);
void EntitySetAsAllowedToFollowHero(void * spThing, bool bIsAllowed);
void EntitySetAsAllowedToChangeRegionFollowingState(void * spThing, bool bIsAllowed);
void EntitySetAsRespondingToFollowAndWaitExpressions(void * spThing, bool bDoesRespond);
void EntitySetAsMirroringHeroEnemyRelationsWhileFollowing(void * spThing, bool bDoesMirror);
void TeleportAllFollowersToHeroPosition(void);
void EntityTeleportToHeroPosition(void * spThing);
void SendEntityEvent(int eventType, void * spSender, void * spReceiver);
void ModifyThingHealth(void * spThing, float amount, void * bUnknown);
void EntitySetMaxHealth(void * spThing, float maxHealth, bool bSetCurrentToMax);
void SetThingAsKilled(void * spThing);
void GiveHeroNewQuestObjective(void * pObjectiveText, unsigned int objectiveID);
void TellHeroQuestObjectiveCompleted(unsigned int objectiveID);
void TellHeroQuestObjectiveFailed(unsigned int objectiveID);
void SetGuildMasterMessages(bool bAreEnabled);
void SetQuestAsPersistent(void * questName, bool bIsPersistent);
void RemoveQuestCardFromGuild(void * questName);
void RemoveQuestCardFromHero(void * questName);
void RemoveAllAvailableQuestCardsFromGuild(void);
void FailAllActiveQuests(void);
void AddFeatCard(int featID, void * name, void * description);
void AddBoast(void * questName, int boastID, int renown, int gold, bool bIsBoast, void * boastText, int textID);
void RemoveBoast(int boastID, void * questName);
void SetBoastAsFailed(int boastID, void * questName);
void SetBoastAsCompleted(int boastID, void * questName);
void KickOffDeathScreen(void);
void KickOffCreditsScreen(void * creditsName);
void SetPreferredQuickAccessItem(void * itemName, int dPadDirection, int slot);
void SetDeathRecoveryMarkerName(void * markerName);
void ResetDeathRecoveryMarkerNameToDefault(void);
void SetWhetherToFailQuestOnDeath(bool bShouldFail);
void ResetWhetherToFailQuestOnDeathToDefault(void);
void UpdateQuestInfoBar(int id, float current, float max, float scale);
void ChangeQuestInfoBarColour(int id, sol::table color1, sol::table color2);
void UpdateQuestInfoTimer(int id, float scale);
void UpdateQuestInfoCounterList(int id, int count, int max);
void UpdateQuestInfoTick(int id, bool bState);
void RemoveQuestInfoElement(int id);
void RemoveAllQuestInfoElements(void);
void DisplayTime(bool bDisplay);
void DisplayMoneyBag(bool bDisplay);
void DisplayMiniGameInfo(bool bDisplay, int gameType);
void UpdateMiniGameInfoBar(float value);
void EntitySetAsPickPocketed(void * spThing);
void EntitySetAsPickLocked(void * spThing);
void EntitySetAsStolen(void * spThing);
void MiniMapAddMarker(void * spThing, void * markerName);
void MiniMapSetMarkerGraphic(void * spThing, void * graphicName);
void MiniMapRemoveMarker(void * spThing);
void MiniMapRemoveAllMarkers(void);
void MiniMapAllowRouteBetweenRegions(void * region1, void * region2, bool bAllow);
void MiniMapSetAsEnabled(bool bIsEnabled);
void EntitySetAsHiddenOnMiniMap(void * spThing, bool bIsHidden);
void SetHUDEnabled(bool bIsEnabled);
void EntitySetWillBeUsingNarrator(void * spThing, void * dialogueKey);
void EntityResetAsPureAINarrator(void * spThing);
void PlayAVIMovie(void * movieName);
void FadeScreenOutUntilNextCallToFadeScreenIn(float fadeTime, float holdTime);
void EndCutFade(void);
void EndLetterBox(void);
void PauseAllEntities(bool bIsPaused);
void SetAllowScreenFadingOnNextRegionChange(bool bIsAllowed);
void SetAllowScreenFadingIfAlreadyFaded(bool bIsAllowed);
void SetAbilityAvailability(int ability, bool bIsAvailable);
void SetEnvironmentalEffectsAlwaysUpdate(bool bAlwaysUpdate);
void SetDeadCreaturesAndExperienceOrbsAndDropBagsAsHidden(bool bIsHidden);
void RemoveDeadCreature(void * creatureName);
void CameraSetCameraPreloadFlag(bool bPreload);
void CameraCircleAroundThing(void * spThing, sol::table offset, float duration);
void CameraCircleAroundPos(sol::table pos, sol::table offset, float duration);
void CameraMoveToPosAndLookAtPos(sol::table camPos, sol::table targetPos, float duration);
void CameraMoveToPosAndLookAtThing(sol::table camPos, void * spTargetThing, float duration);
void CameraMoveBetweenLookingAt(void * spTargetThing, sol::table startPos, sol::table endPos, float f1, float f2);
void CameraMoveBetweenLookFromAndLookTo(sol::table startFrom, sol::table startTo, sol::table endFrom, sol::table endTo, float duration);
void CameraUseCameraPoint(void * spCamPoint, void * spTarget, float duration, int i1, int i2);
void CameraResetToViewBehindHero(float duration);
void CameraUseScreenEffect(float f1, float f2, float f3);
void CameraCancelScreenEffect(void);
void CameraEarthquakeIntensityAtPos(sol::table pos, float intensity, float duration);
void CameraDoConversation(void * spSpeaker, void * spListener, int eOp, void * bUnknown);
void CloseChest(void * spChest);
void DisplayLockedChestMessage(void * spChest);
void SetTrophyAsMountable(void * spTrophy, bool bIsMountable);
void SetVillageLimbo(void * spVillage, bool bIsInLimbo);
void SetCreatureNotReload(void * spCreature);
void EnableGuards(void * spVillage, bool bIsEnabled);
void EnableVillagerDefTypes(void * spVillage, bool bIsEnabled, void * defName);
void ClearHeroEnemyOfGuards(void * spVillage);
void SetThingAsUsable(void * spThing, bool bIsUsable);
void SetThingHomeBuilding(void * spThing, void * spHouse);
void GiveThingBestEnemyTarget(void * spThing, void * spTarget);
void ClearThingBestEnemyTarget(void * spThing);
void EntitySetInLimbo(void * spThing, bool bIsInLimbo, void * bUnknown);
void AddCrimeCommitted(void * spVillage, int crimeType, void * bUnknown, void * spCriminal, void * spVictim, int deedType);
void SetVillageAttitude(void * spVillage, int eAttitude);
void EntitySetNegateAllHits(void * spThing, bool bNegate);
void EntitySetEvadeAllHits(void * spThing, bool bEvade);
void EntitySetAbleToBeEngagedInCombat(void * spThing, bool bIsAble);
void EntitySetAlwaysBlockAttacksFromThing(void * spBlocker, void * spAttacker, bool bBlock);
void EntitySetAttackThingImmediately(void * spAttacker, void * spTarget, void * b1, void * b2);
void EntitySetCombatType(void * spThing, void * combatType);
void EntityResetCombatTypeToDefault(void * spThing);
void EntitySetMaxNumberOfAttackers(void * spThing, int maxAttackers);
void EntityClearMaxNumberOfAttackers(void * spThing);
void EntityAttachToScript(void * spThing, void * questName);
void EntitySetCombatAbility(void * spThing, float ability);
void EntitySetRangedTarget(void * spThing, void * spTarget);
void EntityClearRangedTarget(void * spThing);
void EntitySetTargetingValidTargetWithoutLOS(void * spThing, bool bIsValid);
void EntitySetTargetingType(void * spThing, int eType);
void EntityTeleportToPosition(void * spThing, sol::table pos, float f, void * b1, void * b2);
void EntitySetFacingAngle(void * spThing, float angle, void * bUnknown);
void EntitySetPerceptionVariables(void * spThing, float f1, float f2, float f3);
void EntitySetThingAsWantingMoney(void * spThing, int amount);
void EntitySetAppearanceMorphSeed(void * spThing, int seed);
void SetEntityAsRegionFollowing(void * spFollower, void * spTarget, bool bFollow);
void SetEntityAsFollowingHeroThroughTeleporters(void * spThing, bool bFollow);
void EntitySetMaxRunningSpeed(void * spThing, float speed);
void EntitySetMaxWalkingSpeed(void * spThing, float speed);
void EntityResetMaxRunningSpeed(void * spThing);
void EntityResetMaxWalkingSpeed(void * spThing);
void EntityAttachToVillage(void * spThing, void * spVillage);
void EntitySetAsSittingOnFloor(void * spThing, bool bIsSitting);
void EntitySetAsHavingBoundHands(void * spThing, bool bIsBound);
void EntitySetAsRemoveAllMovementBlockingModes(void * spThing);
void EntitySetAsScared(void * spThing, bool bIsScared);
void EntitySetAsDrunk(void * spThing, bool bIsDrunk);
void EntityForceToLookAtThing(void * spLooker, void * spTarget);
void EntityForceToLookAtCamera(void * spLooker, bool bLook);
void EntityForceToLookAtNothing(void * spLooker);
void EntityResetForceToLookAt(void * spLooker);
void EntitySetShotAccuracyPercentage(void * spThing, int accuracy);
void EntityDropGenericBox(void * spThing);
void EntitySheatheWeapons(void * spThing, void * bUnknown);
void EntityUnsheatheWeapons(void * spThing, void * bUnknown);
void EntityUnsheatheMeleeWeapon(void * spThing, void * bUnknown);
void EntityUnsheatheRangedWeapon(void * spThing, void * bUnknown);
void EntitySetAlpha(void * spThing, float alpha, void * bUnknown);
void EntitySetAsAbleToWalkThroughSolidObjects(void * spThing, bool bCanWalkThrough);
void EntitySetAsRespondToHit(void * spThing, bool bDoesRespond);
void EntitySetAsLocked(void * spThing, bool bIsLocked);
void EntityDecapitate(void * spThing);
void EntityGiveGold(void * spThing, int amount);
void EntitySetAllowBossPhaseChanges(void * spThing, bool bAllow);
void EntitySetBossPhase(void * spThing, int phase);
void EntityResetCreatureMode(void * spThing);
void EntitySetAsReceivingEvents(void * spThing, bool bReceivesEvents);
void EntitySetAsToAddToStatChangesWhenHit(void * spThing, bool bAddsToStats);
void EntityLeaveCombatStance(void * spThing);
void EntitySetAsUseMovementInActions(void * spThing, bool bUseMovement);
void EntitySetAsDisplayingEmoteIcon(void * spThing, bool bDisplaysIcon);
void EntitySetAsCollidableToThings(void * spThing, bool bIsCollidable);
void EntityEnableGravity(void * spThing, bool bIsEnabled);
void EntitySetLightAsOn(void * spThing, bool bIsOn);
void EntityFadeIn(void * spThing, float duration);
void EntityBeginLoadingAnimation(void * spThing, void * pAnimName);
void EntityBeginLoadingBasicAnimations(void * spThing);
void EntityCastLightningAtTarget(void * spCaster, void * spTarget);
void BeginLoadingMesh(void * pMeshName);
void EntityStartScreamerSuperAttackThing(void * spScreamer, void * spTarget);
void EntityEndScreamerSuperAttackThing(void * spScreamer);
void SetLightColour(void * spLight, sol::table color);
void CreatureGeneratorSetFamily(void * spGenerator, void * familyName);
void CreatureGeneratorTrigger(void * spGenerator);
void CreatureGeneratorSetAlwaysCreateCreaturesOnTrigger(void * spGenerator, bool bAlwaysCreate);
void CreatureGeneratorSetGeneratedCreatureScriptName(void * spGenerator, void * scriptName);
void CreatureGeneratorSetNumTriggers(void * spGenerator, int numTriggers);
void CreatureGeneratorAddTriggerer(void * spGenerator, void * spTriggerer);
void CreatureGeneratorRemoveTriggerer(void * spGenerator, void * spTriggerer);
void SetCreatureGeneratorEnabled(void * spGenerator, bool bIsEnabled);
void SetCreatureGeneratorsEnabledDuringScript(void * regionName, bool bIsEnabled);
void SetCreatureGeneratorsCreatureGroupAsEnabled(int eGroup, bool bIsEnabled);
void SetTeleporterAsActive(void * spTeleporter, bool bIsActive);
void SetTeleportingAsActive(bool bIsActive);
void SetRegionEntranceAsActive(void * spEntrance, bool bIsActive);
void SetRegionTextDisplayAsActive(bool bIsActive);
void SetHeroSleepingAsEnabled(bool bIsEnabled);
void SetExperienceSpendingAsEnabled(bool bIsEnabled);
void SetMoralityChangingAsEnabled(bool bIsEnabled);
void SetSummonerDeathExplosionAffectsHero(bool bDoesAffect);
void SetDiggingSpotAsHidden(void * spSpot, bool bIsHidden);
void WaitForCameraMessage(void * message);
void SetThingAsConscious(void * spThing, bool bIsConscious, void * animName);
void SetFireToThing(void * spThing);
void ExtinguishFiresOnThing(void * spThing);
void AddItemToContainer(void * spContainer, void * itemDefName);
void RemoveItemFromContainer(void * spContainer, void * itemDefName);
void EntitySetDeathContainerAsEnabled(void * spThing, bool bIsEnabled);
void EntitySetStategroupEnabled(void * spThing, void * stateGroupName, bool bEnabled);
void EntitySetCombatEnabled(void * spThing, bool bIsEnabled);
void EntitySetSleepEnabled(void * spThing, bool bIsEnabled);
void EntitySetOpinionReactionsEnabled(void * spThing, bool bEnabled);
void EntitySetDeedReactionsEnabled(void * spThing, bool bEnabled);
void EntityUnsetThingAsEnemyOfThing(void * spThing1, void * spThing2);
void EntitySetThingAsAllyOfThing(void * spThing1, void * spThing2);
void EntityUnsetThingAsAllyOfThing(void * spThing1, void * spThing2);
void SetFactionAsAlliedToFaction(void * faction1, void * faction2);
void SetFactionAsNeutralToFaction(void * faction1, void * faction2);
void SetFactionAsEnemyToFaction(void * faction1, void * faction2);
void EntitySetOpinionReactionMaskByInt(void * spThing, int mask);
void EntitySetOpinionDeedMaskByString(void * spThing, void * maskName);
void EntitySetOpinionDeedMaskByInt(void * spThing, int mask);
void EntitySetOpinionDeedTypeEnabled(void * spThing, int eDeed, bool bIsEnabled);
void EntitySetOpinionAttitudeEnabled(void * spThing, int eAttitude, bool bIsEnabled);
void EntitySetOpinionReactionEnabled(void * spThing, int eReaction, bool bIsEnabled);
void EntitySetPersonalityOverrideByInt(void * spThing, int personality);
void EntitySetPersonalityOverrideByString(void * spThing, void * personalityName);
void EntityClearPersonalityOverride(void * spThing);
void EntitySetAsOpinionSourceByInt(void * spThing, int sourceID);
void EntitySetAsOpinionSourceByString(void * spThing, void * sourceName);
void EntityUnsetAsOpinionSource(void * spThing, void * bUnknown);
void OpinionSourceSetAsExclusive(void * spSource, bool bIsExclusive);
void OpinionSourceSetAsAttentionGrabbing(void * spSource, bool bIsGrabbing);
void EntityPostOpinionDeedToAll(void * spActor, int eDeed);
void EntityPostOpinionDeedToRecipient(void * spActor, int eDeed, void * spRecipient);
void EntityPostOpinionDeedToRecipientVillage(void * spActor, int eDeed, void * spVillage);
void RemoveOpinionDeedStillSearchingForWitnesses(void * spActor, int deedID);
void EntitySetAsAwareOfThing(void * spThing1, void * spThing2);
void EntitySetSoundRadius(void * spThing, float radius);
void EntitySetSmellRadius(void * spThing, float radius);
void EntitySetSightRadius(void * spThing, float radius);
void EntitySetExtendedSightRadius(void * spThing, float radius);
void EntitySetGiveUpChaseRadius(void * spThing, float radius);
void SetTimeOfDay(float time);
void SetTimeAsStopped(bool bIsStopped);
void FastForwardTimeTo(float time, float duration);
void TransitionToTheme(void * themeName, float duration);
void ResetToDefaultTheme(float duration);
void TransitionToThemeAllInternals(void * themeName, float duration);
void ResetToDefaultThemeAllInternals(float duration);
void TransitionToThemeExternals(void * themeName, float duration);
void ResetToDefaultThemeExternals(float duration);
void SetEnvironmentThemeWeightAllChannels(void * themeName, float weight);
void SetEnvironmentThemeWeightAllInternals(void * themeName, float weight);
void SetEnvironmentThemeWeightExternals(void * themeName, float weight);
void SetSoundThemesAsEnabledForRegion(void * regionName, bool bIsEnabled);
void SetAllSoundsAsMuted(bool bIsMuted);
void* RadialBlurFadeTo_NoPos(float f1, float f2, float f3, float f4, float f5, float f6, float f7);
void* RadialBlurFadeTo_WithPos(float f1, sol::table v1, float f2, sol::table v2, float f3, float f4, float f5);
void RadialBlurFadeOut(float duration, void* pBlur);
void CancelRadialBlurFade(void);
void RadialBlurSetCenterWorldPos(void* pBlur, sol::table pos);
void* DisplacementMonochromeEffectColourFadeTo(float duration, sol::table color);
void DisplacementMonochromeEffectColourFadeOut(float duration, void* pEffect);
void* ScreenFilterFadeTo(float f1, float f2, float f3, float f4, float f5, sol::table color);
void ScreenFilterFadeOut(float duration, void* pFilter);
void SetThingAndCarriedItemsNotAffectedByScreenFilter(void * spThing, void* pFilter);
void UnSetThingAndCarriedItemsNotAffectedByScreenFilter(void * spThing);
void ApplyScriptBrush(void * brushName);
void EnableDecals(bool bIsEnabled);
void EnableSounds(bool bIsEnabled);
void StopSound(unsigned int soundID);
void CacheMusicSet(int eType);
void EnableDangerMusic(bool bIsEnabled);
void StartCountdownTimer(float time);
void AutoSaveCheckPoint(void);
void AutoSaveQuestStart(void);
void AutoSave(void);
void SetSavingAsEnabled(bool bIsEnabled);
void SetSaveGameMarkerPos(sol::table pos);
void ResetToFrontEnd(void);
void SetGuildSealRecallLocation(sol::table pos, float angle);
void SetReadableObjectText(void * spThing, void * text);
void SetReadableObjectTextTag(void * spThing, void * textTag);
void RemoveRumourCategory(void * categoryName);
void SetCategoryActivity(void * categoryName, bool bIsActive);
void AddGossipVillage(void * categoryName, void * villageName);
void SetIsGossipForPlayer_ByObject(void * categoryName, bool bIsForPlayer);
void SetIsGossipForPlayer_ByName(void * categoryName, bool bIsForPlayer);
void StartSneaking(void);
void SetUseableByHero(void * spThing, bool bIsUseable);
void SetOwnedByHero(void * spThing, bool bIsOwned);
void SetTavernTableAvailableForUse(void * spTable, bool bIsAvailable);
void SetIsThingTurncoatable(void * spThing, bool bIsTurncoatable);
void SetIsThingForcePushable(void * spThing, bool bIsPushable);
void SetIsThingLightningable(void * spThing, bool bIsLightningable);
void SetIsThingEpicSpellable(void * spThing, bool bIsSpellable);
void AddCreatureScriptedMode(void * spCreature, void * mode);
void RemoveCreatureScriptedMode(void * spCreature);
void ForceShipsVisible(void);
void SetBedAvailability(void * spBed, bool bIsAvailable);
void RepopulateVillage(void * spVillage);
void SmashAllWindowsWithinRadiusOfPoint(sol::table pos, float radius);
void SetThankingPhrase(void * spThing, unsigned int phraseID);
void EntityPlayObjectAnimation(void * spThing, void * animName, void * bUnknown);
void ResetThankingPhrase(void * spThing);
void SetIgnoringPhrase(void * spThing, unsigned int phraseID);
void ResetIgnoringPhrase(void * spThing);
void SetWanderCentrePoint(void * spThing, sol::table pos);
void ResetWanderCentrePoint(void * spThing);
void SetWanderMinDistance(void * spThing, float distance);
void ResetWanderMinDistance(void * spThing);
void SetWanderMaxDistance(void * spThing, float distance);
void ResetWanderMaxDistance(void * spThing);
void SetGossipCounter(void * spThing, int count);
void ResetGossipCounter(void * spThing);
void SetMaxGossipPhrase(void * spThing, int max);
void ResetMaxGossipPhrase(void * spThing);
void SetWarningPhrase(void * spThing, unsigned int phraseID);
void ResetWarningPhrase(void * spThing);
void SetGossipVillages(void * category, void * village, int index);
void ClearGossipVillages(void * category);
void RemoveGossipVillages(void * category);
void AddGossipVillages(void * category);
void SetGossipFactions(void * category, void * faction, int index);
void ClearGossipFactions(void * category);
void RemoveGossipFactions(void * category);
void AddGossipFactions(void * category);
void SetTrapAsActive(void * spTrap, bool bIsActive);
void SetCreatureCreationDelayFrames(int frames);
void ResetCreatureCreationDelayFrames(void);
void RemoveBoastMessage(void);
void RemoveAllCutSceneSkippedMessages(void);
void RespawnHero(bool bUnknown);
void CancelHeroTeleportEffects(void);
void EntityFollowThing(void * spFollower, void * spTarget, float distance, bool bUnknown);
void EntityStopFollowing(void * spFollower);
void SetCreatureBrain(void * spCreature, void * brainName);
bool NewScriptFrame(void);
bool IsRegionLoaded(void * regionName);
bool IsDistanceBetweenThingsUnder(void * spThing1, void * spThing2, float distance);
bool IsLevelLoaded(void * levelName);
bool IsObjectInHeroPossession(void * objectDefName);
bool GiveHeroTutorial(int category);
bool GetHeroHasMarried(void);
bool GetHeroHasMurderedWife(void);
bool GetFaceHeroForAction(void * spThing);
bool GetAttackHeroOnSight(void * spThing);
bool GetStealStealableItems(void * spThing);
bool GetRecoverStealableItems(void * spThing);
bool GetTakeStealableItemToRandomDestination(void * spThing);
bool GetKillSelfAndStealableItemAfterReachingDestination(void * spThing);
bool GetAllowedToFollow(void * spThing);
bool GetDisableHeadLooking(void * spThing);
bool GetIsPushableByHero(void * spThing);
bool GetLookForFiniteTime(void * spThing);
bool GetAvoidRegionExits(void * spThing);
bool GetPlayerUsingMeleeDummies(void);
bool GetPlayerUsingRangedDummies(void);
bool GetPlayerUsingWillDummies(void);
bool GetCheapHeadLooking(void);
bool GetQuitTavernGame(void);
bool GetPrizeTavernTable(void);
bool GetBettingActive(void);
bool GetBettingAccept(void);
bool GetCountBetMoneyDown(void);
bool GetSpotTheAdditionBeaten(void);
bool GetBoastingEnabled(void);
bool GetStateBool(void * key);
bool GetGlobalBool(void * key);
bool PersistTransferBool(void* pContext, void * name, bool value);
bool IsConversationActive(int conversationID);
bool MsgIsLevelLoaded(void * levelName);
bool MsgIsLevelUnloaded(void * levelName);
bool MsgOnQuestCompleted(void * questName);
bool MsgOnQuestFailed(void * questName);
bool IsHeroAllowedHenchmenInCurrentRegion(void);
bool IsHeroAllowedHenchmenInRegion(void * regionName);
bool MsgOnHeroUsedGuildSeal(void);
bool MsgOnGameSavedManually(void);
bool MsgOnHeroFiredRangedWeapon(void);
bool IsSafeToDisplayGameInfo(void);
bool DisplayTutorial(int category);
bool IsTutorialSystemEnabled(void);
bool GiveHeroItemsFromContainer(void * spContainerThing, bool bShowUI);
bool IsReportedOrUnreportedCrimeKnown(void * spVillage);
bool IsPlayerZTargetingThing(void * spThing);
bool IsPlayerCreatureBlocking(void);
bool IsHeroRenownLevelFull(void);
bool IsPlayerCreatureFlourishEnabled(void);
bool IsHeroHandLampLit(void);
bool IsWearingClothingItem(void * spThing, void * clothingDefName);
bool IsHeroNaked(void);
bool IsWearingHairstyle(void * spThing, void * hairstyleDefName);
bool IsPlayerCarryingItemOfType(void * defName);
bool IsPlayerWieldingWeapon(void);
bool IsEntityWieldingWeapon(void * spThing);
bool IsEntityWieldingMeleeWeapon(void * spThing);
bool IsEntityWieldingRangedWeapon(void * spThing);
bool IsEntityMarriedToHero(void * spThing);
bool IsEntityMarriable(void * spThing);
bool HeroHasExpression(void * pExpressionName);
bool IsHeroPerformingExpression(void * pExpressionName);
bool IsHeroOnQuest(void);
bool IsQuestActive(void * questName);
bool IsQuestRegistered(void * questName);
bool IsQuestCompleted(void * questName);
bool IsQuestFailed(void * questName);
bool IsToFailQuestOnDeath(void);
bool IsEntityPickPocketable(void * spThing);
bool IsEntityPickLockable(void * spThing);
bool IsEntityStealable(void * spThing);
bool IsScreenFadingOut(void);
bool IsCameraPosOnScreen(sol::table pos);
bool IsChestOpen(void * spChest);
bool OpenChest(void * spChest, void * bUnknown);
bool IsSleepingTime(void * spThing);
bool IsEntityInLimbo(void * spThing);
bool EntityCastForcePush(void * spCaster, void * bUnknown);
bool EntityWillTeleportToArea(void * spThing, sol::table pos, float f1, float f2);
bool CreatureGeneratorIsDepleted(void * spGenerator);
bool CreatureGeneratorIsDestroyed(void * spGenerator);
bool CreatureGeneratorAreAllCreaturesAlive(void * spGenerator);
bool IsCreatureGenerationEnabledForRegion(void * regionName);
bool IsCreatureFlying(void * spCreature);
bool IsTeleporterActive(void * spTeleporter);
bool IsTeleportingActive(void);
bool IsHeroSleepingEnabled(void);
bool IsBoastTaken(int boastID, void * questName);
bool IsCameraInScriptedMode(void);
bool MsgOnLeavingExperienceSpendingScreen(void);
bool MsgIsBoastMade(int boastID);
bool AreEntitiesEnemies(void * spThing1, void * spThing2);
bool IsThingOnFire(void * spThing);
bool IsDiggingSpotEnabled(void * spSpot);
bool IsDiggingSpotHidden(void * spSpot);
bool CheckForCameraMessage(void * message);
bool IsDeedWitnessed(int deedID);
bool CanThingBe_Seen_ByOtherThing(void * spThing1, void * spThing2);
bool CanThingBe_NearlySeen_ByOtherThing(void * spThing1, void * spThing2);
bool CanThingBe_Smelled_ByOtherThing(void * spThing1, void * spThing2);
bool CanThingBe_Heard_ByOtherThing(void * spThing1, void * spThing2);
bool IsThingAwareOfOtherThingInAnyWay(void * spThing1, void * spThing2);
bool IsRadialBlurFadeActive(void);
bool IsGiftRomantic(void * giftName);
bool IsGiftFriendly(void * giftName);
bool IsGiftOffensive(void * giftName);
bool IsThingABed(void * spThing);
bool IsThingAChest(void * spThing);
bool IsThingADoor(void * spThing);
bool IsThingSmashable(void * spThing);
bool IsThingSearchable(void * spThing);
bool IsSoundPlaying(unsigned int soundID);
bool IsDangerMusicEnabled(void);
bool IsSavingEnabled(void);
bool IsHeroInTavernGame(void);
bool IsThingTurncoated(void * spThing);
bool MsgIsGameInfoClickedPast(void);
bool MsgIsTutorialClickedPast(void);
bool MsgIsActionModeButtonPressed(void);
bool MsgIsCutSceneSkipped(void);
bool GetHeroHasCurrentMarriage(void);
bool GetHeroHasDivorcedMarriage(void);
bool GetHeroHasChildren(void);
bool IsHeroChild(void);
bool MsgOnChestOpeningCancelled(void);
bool IsEntityFollowingHero(void * spThing);
bool IsEntityAbleToAttack(void * spThing);
bool IsInCutscene(void);
bool IsTimeOfDayBetween(int startTime, int endTime);
bool ManuallyTriggerTrap(void * spTrap);
bool ManuallyResetTrap(void * spTrap);
int EntityGetStockItemPrice(CScriptThing* pThing);
int GetWorldFrame(void);
int GiveHeroYesNoQuestion(void * question, void * button1, void * button2, void * button3);
int RegisterTimer(void);
int GetTimer(int timerId);
int EntityGetBossPhase(CScriptThing* pThing);
int GetHeroGold(void);
int GetHeroRenownLevel(void);
int GetHeroTitle(void);
int AddQuestInfoTimer(int timerId, void * text, float scale);
int AddQuestInfoCounterList(void * text, int count, float scale);
int AddQuestInfoTickByAction(int gameAction, bool bState, float scale);
int AddQuestInfoTickByText(void * text, bool bState, float scale);
int GetHeroWillEnergy(void);
int GetHeroWillEnergyMax(void);
int GetHeroWillEnergyPercentage(void);
int GetHeroRoughExperienceLevel(void);
int GetHeroExperienceAvailableToSpend(void);
int GetHeroMoralityCategory(void);
int GetPlayerCreatureCombatMultiplier(void);
int GetPlayerCreatureCombatMultiplierRunningNumHits(void);
int GetActiveGossipCategoriesSize(void);
int GetScriptingStateGroup(void * spThing);
int GetTimeToSpendHarassingHero(void * spThing);
int GetActionFrequency(void * spThing);
int GetBettingAmount(void);
int GetIsGossipForPlayerSize(void);
int GetGossipSize(void * category);
int GetStateInt(void * key);
int GetGlobalInt(void * key);
int PersistTransferInt(void* pContext, void * name, int value);
int AddQuestInfoBar(float current, float max, sol::table color1, sol::table color2, void * texture, void * text, float scale);
int AddQuestInfoBarHealth(void * spThing, sol::table color, void * texture, float scale);
int AddQuestInfoCounter(void * text, int count, float scale);
int GetHeroStrengthLevel(void);
int GetHeroSkillLevel(void);
int GetHeroWillLevel(void);
int GetHeroStatLevel(int statType);
int GetHeroStatMax(int statType);
int GetNumberOfItemsOfTypeInInventory(void * defName);
int GetNumberOfTimesHeroHasHadSex(void);
int EntityGetSex(void * spThing);
int CreatureGeneratorGetNumGeneratedCreatures(void * spGenerator);
int GetNextInOpinionAttitudeGraph(int eCurrent);
int EntityGetOpinionAttitudeToPlayer(void * spThing);
int EntityPostOpinionDeedKeepSearchingForWitnesses(void * spActor, int eDeed, void * spRecipient);
int GetTimeOfDay(void);
int GetDayOfWeek(void);
int GetDayCount(void);
int GetConstantFPS(void);
int GetBestScoreBlackjack(void);
int GetBestScoreCoinGolfOakVale(void);
int GetBestScoreCoinGolfSnowSpire(void);
int GetBestScoreShoveHaPenny(void);
int GetNumHousesOwned(void);
int GetStealDuration(void * spThing);
int GetGossipCounter(void * spThing);
int GetMaxGossipPhrase(void * spThing);
int GetGossipVillagesSize(void * category);
int GetGossipFactionsSize(void * category);
int MsgIsQuestionAnsweredYesOrNo(void);
unsigned int GetThankingPhrase(void * spThing);
unsigned int PlayCriteriaSoundOnThing(void * spThing, void * soundName);
unsigned int PersistTransferUInt(void* pContext, void * name, unsigned int value);
unsigned int GetBeerRequestPhrase(void * spThing);
unsigned int EntityGetAppearanceSeed(void * spThing);
unsigned int GetIgnoringPhrase(void * spThing);
unsigned int GetWarningPhrase(void * spThing);
unsigned int PlaySoundOnThing(void * pThing, void * soundName);
unsigned int Play2DSound(void * soundName);
unsigned int PlaySoundAtPos(sol::table position, void * soundName);
float GetHeroAge(void);
float GetHealth(CScriptThing* pThing);
float GetHeroFatness(void);
float GetActionFrequencyVariation(void * spThing);
float GetMaxHeroReactionDistance(void * spThing);
float GetFollowDistance(void * spThing);
float GetCombatNearbyEnemyFleeingBreakOffRange(void * spThing);
float GetCombatNearbyBreakOffRange(void * spThing);
float GetTargetingDistanceOffset(void * spThing);
float PersistTransferFloat(void* pContext, void * name, float value);
float GetGlobalTargetingDistanceOffset(void);
float GetTradingPriceMult(void);
float GetHeroMorality(void);
float GetDistanceHeroCanBeHeardFrom(void);
float GetHeroScariness(void);
float GetHeroAttractiveness(void);
float GetHeroWillEnergyLevel(void);
float GetWaterHeightAtPosition(sol::table position);
float GetHeroHealthMax(void);
float GetHeroHealthPercentage(void);
float GetGameAngleXY(void);
float EntityGetOpinionOfPlayer(void * spThing, int eOpinion);
float EntityGetHearingRadius(void * spThing);
float GetCountdownTimer(void);
float GetGuildSealRecallAngleXY(void);
float GetBestTimePairs(void);
float GetBestTimeSorting(void);
float GetBestTimeGuessTheAddition(void);
float GetWanderMinDistance(void * spThing);
float GetWanderMaxDistance(void * spThing);
float GetHeroHealth(void);
sol::object MsgOnHeroCastSpell(sol::this_state s);
sol::object GetMasterGameState(void * flagName, sol::this_state s);
sol::object GetActiveGossipCategories(sol::this_state s);
sol::object GetIsGossipForPlayer(sol::this_state s);
sol::object GetGossip(void * category, sol::this_state s);
sol::object MsgOnQuestAccepted(sol::this_state s);
sol::object MsgOnHeroPickedPocket(sol::this_state s);
sol::object MsgOnHeroPickedLock(sol::this_state s);
sol::object MsgOnFishingGameFinished(sol::this_state s);
sol::object MsgOnTavernGameFinished(sol::this_state s);
sol::object MsgOnHeroRewardedWithItemsFrom(sol::this_state s);
sol::object MsgOnHeroHairTypeChanged(int area, sol::this_state s);
sol::object MsgOnHeroUsedTeleporter(sol::this_state s);
sol::object MsgOnHeroSlept(sol::this_state s);
sol::object GetPreviouslyWieldedMeleeWeaponName(sol::this_state s);
sol::object GetPreviouslyWieldedRangedWeaponName(sol::this_state s);
sol::object GetNumberOfKeysNeededToUnlockChest(void * spChest, sol::this_state s);
sol::object MsgOnExpressionPerformed(sol::this_state s);
sol::object IsQuestStartScreenActive(sol::this_state s);
sol::object MsgOnLeavingQuestStartScreen(sol::this_state s);
sol::object MsgOnFeatAccepted(sol::this_state s);
sol::object IsPlayerCreatureReadyToFireProjectileWeapon(sol::this_state s);
sol::object EntityGetShotStrikePos(void * spThing, sol::this_state s);
sol::object GetGossipVillages(void * category, sol::this_state s);
sol::object GetGossipFactions(void * category, sol::this_state s);
void * GetHero(void);
void * GetThingWithScriptName(void * scriptName);
void * GetThingWithUID(void * uid_str);
void * GetThingWithScriptNameAtRegion(void * scriptName, void * regionName);
void * GetNearestWithDefName(void * spRelativeTo, void * defName);
void * GetHeroTargetedThing(void);
void * GetNearestWithScriptName(void * spRelativeTo, void * scriptName);
void * GetFurthestWithScriptName(void * spRelativeTo, void * scriptName);
void * GetFurthestWithDefName(void * spRelativeTo, void * defName);
void * CreateLight(sol::table position, sol::table color, void * scriptName, float innerRadius, float outerRadius, void * flicker);
void * CreateObjectOnEntity(void * defName, void * spOnThing, void * scriptName);
void * CreateCreatureOnEntity(void * defName, void * spOnThing, void * scriptName);
void * TurnCreatureInto(void * spTarget, void * newDefName);
void * CreateCreature(void * defName, sol::table position, void * scriptName);
void * CreateObjectWithRotation(void * defName, sol::table position, float rotation, void * scriptName);
void * CreateObject(void * defName, sol::table position, void * scriptName);
void * CreateCreatureNearby(void * defName, sol::table position, float radius, void * scriptName);
void * CreateEffectAtPos(void * effectName, sol::table position, void * angle, void * independent, void * alwaysUpdate);
void * CreateEffectOnThing(void * effectName, CScriptThing* pTarget, void * boneName, void * independent, void * alwaysUpdate);
void * CreateExperienceOrb(sol::table position, int amount);
void * CreateExplosion(void * defName, sol::table position, sol::table direction, void * scriptName);
void * CreatePhysicalBarrier(float size, sol::table position, sol::table direction, void * scriptName);
void * CreateRumble(sol::table position, float f1, float f2, void * scriptName);
void * TryToRespawnDefNamed(void * spThing, void * defName, sol::table pos);
void * GetMostRecentValidUsedTarget(void);
void * EntityGetStandingOnThing(void * spThing);
void * EntityGetStandingInsideBuilding(void * spThing);
void * GetNearestEnabledDiggingSpot(void * spRelativeTo);
void * SetResidency(void * spThing, bool bIsResident);
void * GetRandomThingWithScriptName(void * scriptName);
void * EntityGetThingInPrimarySlot(void * spThing);
sol::table GetItemDefNamesFromContainer(void * spContainer, sol::this_state s);
sol::table GetAllThingsWithDefName(void * defName, sol::this_state s);
sol::table GetAllThingsWithScriptName(void * scriptName, sol::this_state s);
sol::table GetFollowingEntityList(void * spTarget, sol::this_state s);
sol::table GetHeroSummonedCreaturesList(sol::this_state s);
sol::table GetPerceivingHeroEntityList(sol::this_state s);
sol::table GetAllCreaturesExcludingHero(sol::this_state s);
sol::table GetAllThingsWithDefNameByDistanceFrom(void * spRelativeTo, void * defName, sol::this_state s);
sol::table GetAllCreaturesInAreaWithScriptName(void * scriptName, sol::table position, float radius, sol::this_state s);
sol::table GetWanderCentrePoint(void * spThing, sol::this_state s);
sol::table DebugGetAllTextEntriesForTargetedThing(sol::this_state s);
sol::table GetThingDebugInfo(CScriptThing* pThing, sol::this_state s);
sol::table MsgOnBoastsMade(sol::this_state s);
sol::table GetSleepingPositionAndOrientationFromBed(void * spBed, void * spSleeper, sol::this_state s);
sol::table GetAllActiveQuestInfo(sol::this_state s);
sol::table GetGuildSealRecallPos(sol::this_state s);
void * GetActiveQuestName(void);
void * GetAction(void * spThing);
void * GetTargetName(void * spThing);
void * GetTableName(void * spThing);
void * GetSeatName(void * spThing);
void * GetStateString(void * key);
void * GetGlobalString(void * key);
void * PersistTransferString(void* pContext, void * name, void * value);
void * GetRegionName(void);
void * GetExclusiveQuestScriptName(void);
void * GetDeathRecoveryMarkerName(void);
void * GetMostRecentValidUsedTargetName(void);
void * GetOpinionAttitudeAsString(int eAttitude);
void * EntityGetOpinionAttitudeToPlayerAsString(void * spThing);