extern "C" __declspec(naked) void cand_0043f400(void)
{
    __asm
    {
        _emit 0x56
        _emit 0x8B
        _emit 0xF1
        _emit 0x85
        _emit 0xF6
        _emit 0x57
        _emit 0x8B
        _emit 0xFA
        _emit 0x74
        _emit 0x18
        _emit 0x57
        _emit 0xE8
        _emit 0x10
        _emit 0xC3
        _emit 0x55
        _emit 0x00
        _emit 0x8B
        _emit 0x47
        _emit 0x04
        _emit 0x89
        _emit 0x46
        _emit 0x04
        _emit 0x8B
        _emit 0x4F
        _emit 0x08
        _emit 0x89
        _emit 0x4E
        _emit 0x08
        _emit 0x8B
        _emit 0x57
        _emit 0x0C
        _emit 0x89
        _emit 0x56
        _emit 0x0C
        _emit 0x5F
        _emit 0x5E
        _emit 0xC3
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xC3
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xCC
        _emit 0xC3
    }
}