/* Ghidra project FableTLC/Fable.exe; function entry 0x00DAADA0; generated by DecompFuncsToDirectory.java. */


void __thiscall FUN_00daada0(uint param_1,CPersistContext *param_2)

{
  undefined4 uStack_4;
  
  uStack_4 = param_1 & 0xffffff;
  CPersistContext::Transfer<signed_char>
            (param_2,"AttackOver",(char *)(param_1 + 0x50),(char *)((int)&uStack_4 + 3));
  return;
}


