/* Ghidra project FableTLC/Fable.exe; function entry 0x00DB8300; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.6433479755893675 <- ego_r]
   private: virtual void __thiscall NScript::CQ_NewOakValeIntroScript::COVI_DeadFather::Main(void)
    */

void __thiscall NScript::CQ_NewOakValeIntroScript::COVI_DeadFather::Main(COVI_DeadFather *this)

{
  CScriptThing *pCVar1;
  int iVar2;
  char extraout_AL;
  bool bVar3;
  char cVar4;
  char extraout_AL_00;
  char extraout_AL_01;
  char extraout_AL_02;
  char extraout_AL_03;
  char extraout_AL_04;
  undefined4 uVar5;
  int *piVar6;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_01;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *unaff_EBP;
  float10 fVar7;
  CScriptThing *pCVar8;
  undefined **local_20;
  CScriptThing local_1c [12];
  undefined **appuStack_10 [2];
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  pCVar1 = (CScriptThing *)(this + 8);
  local_20 = &PTR_LAB_012c32f0;
  CScriptThing::CScriptThing(local_1c,pCVar1);
  CWorldMap::AllocateMapThingUID((CWorldMap *)this,(long)&local_20);
  local_20 = &PTR_LAB_012c32f0;
  C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)local_1c);
  (**(code **)(**(int **)(this + 4) + 0x1c))();
  CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)this);
  if (extraout_AL == '\0') {
    CBaseIntelligentPointer::CBaseIntelligentPointer((CBaseIntelligentPointer *)appuStack_10);
    appuStack_10[0] = &PTR__scalar_deleting_destructor__0127094c;
    uStack_8 = 0;
    uStack_4 = 0;
    bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)appuStack_10);
    if (bVar3) {
      CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)appuStack_10);
    }
    cVar4 = (**(code **)(**(int **)(this + 4) + 0x20))();
    while (cVar4 == '\0') {
      (**(code **)(**(int **)(this + 4) + 0x1c))();
      CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)this)
      ;
      if (extraout_AL_00 != '\0') goto LAB_00db8507;
      cVar4 = (**(code **)(**(int **)(this + 4) + 0x20))();
    }
    CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)this);
    if (extraout_AL_01 == '\0') {
      CCharString::CCharString((CCharString *)&stack0xffffffd0,"MK_OVID_DAD",-1);
      iVar2 = **(int **)(this + 4);
      uVar5 = (**(code **)(**(int **)(this + 4) + 0x120))(&stack0xffffffd4);
      pCVar8 = pCVar1;
      (**(code **)(iVar2 + 0x760))(pCVar1,uVar5);
      C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&stack0xffffffc0);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffbc,
                 extraout_EDX,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar8);
      CCharString::CCharString((CCharString *)&stack0xffffffbc,"MK_OVID_DAD",-1);
      piVar6 = (int *)(**(code **)(**(int **)(this + 4) + 0x120))(&stack0xffffffc0,&stack0xffffffbc)
      ;
      iVar2 = **(int **)(this + 4);
      fVar7 = (float10)(**(code **)(*piVar6 + 0x28))(1);
      (**(code **)(iVar2 + 0x768))(pCVar1,(float)fVar7);
      C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&stack0xffffffd4);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffd0,
                 extraout_EDX_00,unaff_EBP);
      CCharString::CCharString((CCharString *)&stack0xffffffd0,"CS_DEAD_DAD",-1);
      CScriptGameResourceObjectScriptedThingBase::
      _PlayLoopingAnimation_CScriptGameResourceObjectScriptedThingBase__UAEXABVCCharString__J_N111111_Z
                ((CScriptGameResourceObjectScriptedThingBase *)local_1c,
                 (CScriptThing *)&stack0xffffffd0,(char *)0xffffffff,(CCharString *)0x0,
                 (CCharString *)0x1,(CCharString *)0x0,true,(bool)DAT_01375748);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffd0,
                 extraout_EDX_01,unaff_EBP);
      cVar4 = *(char *)(*(int *)(this + 0x14) + 0x51);
      while (cVar4 == '\0') {
        (**(code **)(**(int **)(this + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)this);
        if (extraout_AL_02 != '\0') goto LAB_00db8507;
        cVar4 = *(char *)(*(int *)(this + 0x14) + 0x51);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)this)
      ;
      if (extraout_AL_03 == '\0') {
        (**(code **)(**(int **)(this + 4) + 0x580))();
        do {
          (**(code **)(**(int **)(this + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)this);
        } while (extraout_AL_04 == '\0');
      }
    }
LAB_00db8507:
    CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase
              ((CScriptGameResourceObjectMovieBase *)local_1c);
  }
  return;
}


