/* Ghidra project FableTLC/Fable.exe; function entry 0x00DBDE40; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.6823340928944595 <- ego_r]
   public: void __thiscall NScript::CQ_NewOakValeIntroScript::DoMission(void) */

void __thiscall NScript::CQ_NewOakValeIntroScript::DoMission(CQ_NewOakValeIntroScript *this)

{
  CQ_NewOakValeIntroScript CVar1;
  int iVar2;
  char cVar3;
  bool bVar4;
  _func_void *p_Var5;
  CSpawnedFunc<NScript::CExpression_FollowScript> *pCVar6;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar7;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_01;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_02;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_03;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_04;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_05;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_06;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_07;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_08;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_09;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_10;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_11;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_12;
  undefined1 *puStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_70;
  undefined1 *puStack_68;
  undefined4 uStack_64;
  undefined4 uStack_58;
  undefined4 uStack_3c;
  uint uVar8;
  CCharString *pCVar9;
  CCharString local_24 [4];
  undefined4 local_20;
  C3DClothPrimitive aCStack_1c [4];
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> apStack_18 [24];
  
  local_20 = 0;
  CCharString::CCharString(local_24,"StartOakVale",-1);
  pCVar9 = local_24;
  cVar3 = (**(code **)(**(int **)(this + 0x40) + 0x30))();
  std::
  _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
            ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffd8,
             extraout_EDX,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar9);
  while (cVar3 == '\0') {
    (**(code **)(**(int **)(this + 0x40) + 0x1c))();
    bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
    if (bVar4) {
      return;
    }
    uStack_3c = 0xdbdea8;
    CCharString::CCharString((CCharString *)&stack0xffffffd8,"StartOakVale",-1);
    cVar3 = (**(code **)(**(int **)(this + 0x40) + 0x30))();
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffd8,
               extraout_EDX_00,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar9);
  }
  bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
  if (bVar4) {
    return;
  }
  if (this[0x50] == (CQ_NewOakValeIntroScript)0x0) {
    bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
    if (bVar4) {
      return;
    }
    uVar8 = 0;
    uStack_3c = 0x40000000;
    (**(code **)(**(int **)(this + 0x40) + 0x5d0))();
    CCharString::CCharString((CCharString *)&stack0xffffffd0,"CREATURE_HERO_CHILD",-1);
    iVar2 = **(int **)(this + 0x40);
    p_Var5 = (_func_void *)(**(code **)(**(int **)(this + 0x40) + 0x118))();
    ppVar7 = apStack_18;
    (**(code **)(iVar2 + 0x178))();
    C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)local_24);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_3c,
               extraout_EDX_01,ppVar7);
    pCVar6 = ::operator_new(0x3c);
    if (pCVar6 == (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0) {
      pCVar6 = (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0;
    }
    else {
      CCharString::CCharString((CCharString *)&uStack_3c,"WatchBarrels",-1);
      uVar8 = 1;
      CSpawnedFunc<NScript::CExpression_FollowScript>::
      CSpawnedFunc<NScript::CExpression_FollowScript>
                (pCVar6,(CCharString *)&uStack_3c,0,(CExpression_FollowScript *)ppVar7,p_Var5);
      *(undefined ***)pCVar6 = &PTR__vector_deleting_destructor__012d7a3c;
      *(code **)(pCVar6 + 0x34) = FUN_00dbe890;
      *(CQ_NewOakValeIntroScript **)(pCVar6 + 0x38) = this;
    }
    CCharString::CCharString((CCharString *)&stack0xffffffcc,"",-1);
    CGuiVarTransferStruct::Add((CGuiVarTransferStruct *)this,(CGuiVarTransferBase *)pCVar6);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffcc,
               extraout_EDX_02,ppVar7);
    if ((uVar8 & 1) != 0) {
      uVar8 = uVar8 & 0xfffffffe;
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_3c,
                 extraout_EDX_03,ppVar7);
    }
    pCVar6 = ::operator_new(0x3c);
    if (pCVar6 == (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0) {
      pCVar6 = (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0;
    }
    else {
      CCharString::CCharString((CCharString *)&stack0xffffffc8,"WatchForGotGold",-1);
      uVar8 = uVar8 | 2;
      CSpawnedFunc<NScript::CExpression_FollowScript>::
      CSpawnedFunc<NScript::CExpression_FollowScript>
                (pCVar6,(CCharString *)&stack0xffffffc8,0,(CExpression_FollowScript *)ppVar7,p_Var5)
      ;
      *(undefined ***)pCVar6 = &PTR__vector_deleting_destructor__012d7a3c;
      *(code **)(pCVar6 + 0x34) = CQ_FireHeartScript::CheckGameEnding;
      *(CQ_NewOakValeIntroScript **)(pCVar6 + 0x38) = this;
    }
    CCharString::CCharString((CCharString *)&stack0xffffffcc,"",-1);
    CGuiVarTransferStruct::Add((CGuiVarTransferStruct *)this,(CGuiVarTransferBase *)pCVar6);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffcc,
               extraout_EDX_04,ppVar7);
    if ((uVar8 & 2) != 0) {
      uVar8 = uVar8 & 0xfffffffd;
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffc8,
                 extraout_EDX_05,ppVar7);
    }
    pCVar6 = ::operator_new(0x3c);
    if (pCVar6 == (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0) {
      pCVar6 = (CSpawnedFunc<NScript::CExpression_FollowScript> *)0x0;
    }
    else {
      CCharString::CCharString((CCharString *)&stack0xffffffc8,"ManageQuestCoreMarkers",-1);
      uVar8 = uVar8 | 4;
      CSpawnedFunc<NScript::CExpression_FollowScript>::
      CSpawnedFunc<NScript::CExpression_FollowScript>
                (pCVar6,(CCharString *)&stack0xffffffc8,0,(CExpression_FollowScript *)ppVar7,p_Var5)
      ;
      *(undefined ***)pCVar6 = &PTR__vector_deleting_destructor__012d7a3c;
      *(code **)(pCVar6 + 0x34) = ManageQuestCoreMarkers;
      *(CQ_NewOakValeIntroScript **)(pCVar6 + 0x38) = this;
    }
    CCharString::CCharString((CCharString *)&stack0xffffffcc,"",-1);
    CGuiVarTransferStruct::Add((CGuiVarTransferStruct *)this,(CGuiVarTransferBase *)pCVar6);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffcc,
               extraout_EDX_06,ppVar7);
    if ((uVar8 & 4) != 0) {
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffc8,
                 extraout_EDX_07,ppVar7);
    }
    (**(code **)(**(int **)(this + 0x40) + 0xae8))();
    uStack_58 = 0xdbe0d6;
    CCharString::CCharString((CCharString *)&uStack_3c,"Q_NewOakValeIntro_PreAttack",-1);
    ppVar7 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&uStack_3c;
    (**(code **)(**(int **)(this + 0x40) + 0x450))();
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffc0,
               extraout_EDX_08,ppVar7);
    (**(code **)(**(int **)(this + 0x40) + 0x1c))();
    bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
    if (bVar4) {
      return;
    }
    iVar2 = **(int **)(this + 0x40);
    uStack_58 = 0;
    (**(code **)(**(int **)(this + 0x40) + 0x118))();
    (**(code **)(iVar2 + 0x814))();
    uStack_64 = 1;
    puStack_68 = (undefined1 *)0xdbe134;
    (**(code **)(**(int **)(this + 0x40) + 0xa20))();
    puStack_68 = (undefined1 *)0x41400000;
    (**(code **)(**(int **)(this + 0x40) + 0xa18))();
    uStack_70 = 0xdbe151;
    (**(code **)(**(int **)(this + 0x40) + 0x8e8))();
    uStack_70 = 1;
    (**(code **)(**(int **)(this + 0x40) + 0x554))();
    uStack_7c = 0xdbe16e;
    CCharString::CCharString((CCharString *)&stack0xffffffa0,"HerosOldHouse",-1);
    ppVar7 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&uStack_58;
    uStack_7c = 0xdbe183;
    (**(code **)(**(int **)(this + 0x40) + 0x120))();
    uStack_7c = 0xdbe18c;
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&puStack_68,
               extraout_EDX_09,ppVar7);
    uStack_7c = 1;
    puStack_80 = &stack0xffffffa0;
    (**(code **)(**(int **)(this + 0x40) + 0x6bc))();
    (**(code **)(**(int **)(this + 0x40) + 0x6ac))(&puStack_68);
    iVar2 = **(int **)(this + 0x40);
    ppVar7 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
             (**(code **)(**(int **)(this + 0x40) + 0xa3c))(&uStack_70,0,1);
    (**(code **)(iVar2 + 0x4d4))();
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&puStack_80,
               extraout_EDX_10,ppVar7);
    (**(code **)(**(int **)(this + 0x40) + 0xae0))(0x13,0,1);
    C3DClothPrimitive::~C3DClothPrimitive(aCStack_1c);
    CVar1 = this[0x50];
    while (CVar1 == (CQ_NewOakValeIntroScript)0x0) {
      (**(code **)(**(int **)(this + 0x40) + 0x1c))();
      bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
      if (bVar4) {
        return;
      }
      CVar1 = this[0x50];
    }
  }
  bVar4 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
  if (!bVar4) {
    AttackStuff(this);
    PostAttackStuff(this);
    uStack_3c = 0x3f000000;
    (**(code **)(**(int **)(this + 0x40) + 0x5d0))();
    iVar2 = **(int **)(this + 0x40);
    (**(code **)(**(int **)(this + 0x40) + 0x118))();
    (**(code **)(iVar2 + 0x814))();
    (**(code **)(**(int **)(this + 0x40) + 0x8e8))();
    iVar2 = **(int **)(this + 0x40);
    uStack_58 = 0;
    ppVar7 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
             (**(code **)(**(int **)(this + 0x40) + 0xa3c))();
    uStack_64 = 0xdbe29b;
    (**(code **)(iVar2 + 0x480))();
    uStack_64 = 0xdbe2a4;
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffb4,
               extraout_EDX_11,ppVar7);
    iVar2 = **(int **)(this + 0x40);
    uStack_64 = 0;
    puStack_68 = &stack0xffffffb4;
    ppVar7 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
             (**(code **)(**(int **)(this + 0x40) + 0xa3c))();
    uStack_70 = 0xdbe2c4;
    (**(code **)(iVar2 + 0x464))();
    uStack_70 = 0xdbe2cd;
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_58,
               extraout_EDX_12,ppVar7);
  }
  return;
}


