/* Ghidra project FableTLC/Fable.exe; function entry 0x00DB5330; generated by DecompFuncsToDirectory.java. */


/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void __fastcall FUN_00db5330(CWorldMap *param_1)

{
  CScriptThing *pCVar1;
  char extraout_AL;
  char extraout_AL_00;
  char extraout_AL_01;
  char extraout_AL_02;
  char extraout_AL_03;
  char extraout_AL_04;
  char extraout_AL_05;
  char extraout_AL_06;
  char extraout_AL_07;
  char extraout_AL_08;
  char extraout_AL_09;
  char extraout_AL_10;
  char extraout_AL_11;
  char extraout_AL_12;
  char extraout_AL_13;
  char extraout_AL_14;
  char extraout_AL_15;
  char extraout_AL_16;
  char extraout_AL_17;
  char extraout_AL_18;
  char extraout_AL_19;
  char extraout_AL_20;
  char extraout_AL_21;
  char extraout_AL_22;
  char extraout_AL_23;
  char extraout_AL_24;
  char extraout_AL_25;
  char cVar2;
  char extraout_AL_26;
  bool bVar3;
  char extraout_AL_27;
  char extraout_AL_28;
  undefined1 uVar4;
  char extraout_AL_29;
  char extraout_AL_30;
  char extraout_AL_31;
  char extraout_AL_32;
  char extraout_AL_33;
  char extraout_AL_34;
  char extraout_AL_35;
  char extraout_AL_36;
  char extraout_AL_37;
  char extraout_AL_38;
  char extraout_AL_39;
  char extraout_AL_40;
  char extraout_AL_41;
  char extraout_AL_42;
  char extraout_AL_43;
  char extraout_AL_44;
  char extraout_AL_45;
  char extraout_AL_46;
  char extraout_AL_47;
  char extraout_AL_48;
  char extraout_AL_49;
  char extraout_AL_50;
  char extraout_AL_51;
  char extraout_AL_52;
  char extraout_AL_53;
  char extraout_AL_54;
  char extraout_AL_55;
  char extraout_AL_56;
  undefined4 *puVar5;
  undefined4 uVar6;
  CScriptThing *pCVar7;
  int *piVar8;
  C3DVector *pCVar9;
  int *piVar10;
  int iVar11;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar12;
  undefined4 uVar13;
  undefined *puVar14;
  C3DClothPrimitive *this;
  CScriptGameResourceObjectMovieBase *pCVar15;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_01;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_02;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_03;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_04;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_05;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_06;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_07;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_08;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_09;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_10;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_11;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_12;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_13;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_14;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_15;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_16;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_17;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *ppVar16;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_18;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_19;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_20;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_21;
  undefined **ppuVar17;
  undefined **ppuVar18;
  float10 fVar19;
  float10 fVar20;
  char *pcVar21;
  CCharString *pCVar22;
  CCharString *pCVar23;
  CCharString *pCVar24;
  float fVar25;
  CCharString *pCVar26;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar27;
  undefined4 *puVar28;
  undefined **ppuStack_1f4;
  int *piStack_1f0;
  undefined4 uStack_1ec;
  undefined **ppuStack_1e8;
  undefined **ppuStack_1e4;
  int *piStack_1e0;
  int *piStack_1dc;
  undefined **ppuStack_1d8;
  undefined **ppuStack_1d4;
  int *piStack_1d0;
  undefined4 uStack_1cc;
  undefined **ppuStack_1c8;
  undefined4 uStack_1c4;
  int *piStack_1c0;
  undefined1 *puStack_1bc;
  CCharString aCStack_1b8 [8];
  undefined **ppuStack_1b0;
  allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> aaStack_194 [4];
  undefined **ppuStack_190;
  CCharString aCStack_18c [4];
  undefined4 uStack_188;
  undefined4 uStack_184;
  CCharString aCStack_180 [8];
  allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> aaStack_178 [4];
  CCharString aCStack_174 [4];
  allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> aaStack_170 [4];
  CCharString aCStack_16c [4];
  CCharString aCStack_168 [4];
  undefined4 uStack_164;
  C3DClothPrimitive aCStack_15c [4];
  int *piStack_158;
  undefined4 uStack_150;
  undefined **ppuStack_14c;
  undefined4 uStack_148;
  int *piStack_144;
  undefined4 uStack_140;
  undefined4 uStack_13c;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> apStack_138 [4];
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> apStack_134 [8];
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> apStack_12c [12];
  C3DClothPrimitive aCStack_120 [8];
  CCarriedReadableDef aCStack_118 [4];
  C3DClothPrimitive aCStack_114 [12];
  CCarriedReadableDef aCStack_108 [16];
  CScriptGameResourceObjectMovieBase aCStack_f8 [4];
  C3DClothPrimitive aCStack_f4 [12];
  CCarriedReadableDef aCStack_e8 [8];
  C3DClothPrimitive aCStack_e0 [4];
  C3DClothPrimitive aCStack_dc [12];
  C3DClothPrimitive aCStack_d0 [8];
  C3DClothPrimitive aCStack_c8 [16];
  C3DClothPrimitive aCStack_b8 [4];
  C3DClothPrimitive aCStack_b4 [8];
  C3DClothPrimitive aCStack_ac [8];
  undefined1 auStack_a4 [4];
  C3DClothPrimitive aCStack_a0 [4];
  C3DClothPrimitive aCStack_9c [20];
  CCarriedReadableDef aCStack_88 [136];
  
  pCVar1 = (CScriptThing *)(param_1 + 8);
  uStack_164 = 0;
  ppuStack_14c = &PTR_LAB_012c2fe8;
  CScriptThing::CScriptThing((CScriptThing *)&uStack_148,pCVar1);
  CWorldMap::AllocateMapThingUID(param_1,(long)&ppuStack_14c);
  ppuStack_14c = &PTR_LAB_012c2fe8;
  C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&uStack_148);
  (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
  CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)param_1);
  if (extraout_AL != '\0') {
    return;
  }
  CBaseIntelligentPointer::CBaseIntelligentPointer((CBaseIntelligentPointer *)&ppuStack_190);
  ppuStack_190 = &PTR__scalar_deleting_destructor__0127094c;
  uStack_188 = 0;
  uStack_184 = 0;
  ppuStack_1b0 = (undefined **)0xdb53b1;
  CCharString::CCharString(aCStack_168,"BRAIN_PASSIVE_OVERRIDE",-1);
  ppuStack_1b0 = (undefined **)0xdb53c2;
  pCVar7 = pCVar1;
  (**(code **)(**(int **)(param_1 + 4) + 0x934))();
  ppuStack_1b0 = (undefined **)0xdb53cb;
  std::
  _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
            (aaStack_170,extraout_EDX,
             (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar7);
  puStack_1bc = aCStack_1b8;
  piStack_1c0 = (int *)0xdb53d6;
  (**(code **)(*(int *)pCVar1 + 0x1c))();
  ppuStack_1c8 = &PTR__scalar_deleting_destructor__01238c8c;
  uStack_1c4 = *(undefined4 *)(param_1 + 0xc);
  piStack_1c0 = *(int **)(param_1 + 0x10);
  if (piStack_1c0 != (int *)0x0) {
    *piStack_1c0 = *piStack_1c0 + 1;
  }
  uStack_1cc = 0xdb5404;
  (**(code **)(**(int **)(param_1 + 4) + 0xbec))();
  uStack_1cc = 0;
  ppuStack_1d8 = &PTR__scalar_deleting_destructor__01238c8c;
  ppuStack_1d4 = *(undefined ***)(param_1 + 0xc);
  piStack_1d0 = *(int **)(param_1 + 0x10);
  if (piStack_1d0 != (int *)0x0) {
    *piStack_1d0 = *piStack_1d0 + 1;
  }
  piStack_1dc = (int *)0xdb5433;
  (**(code **)(**(int **)(param_1 + 4) + 0xbf8))();
  piStack_1dc = (int *)&DAT_3f800000;
  ppuStack_1e8 = &PTR__scalar_deleting_destructor__01238c8c;
  ppuStack_1e4 = *(undefined ***)(param_1 + 0xc);
  piStack_1e0 = *(int **)(param_1 + 0x10);
  if (piStack_1e0 != (int *)0x0) {
    *piStack_1e0 = *piStack_1e0 + 1;
  }
  uStack_1ec = 0xdb5466;
  (**(code **)(**(int **)(param_1 + 4) + 0xc04))();
  uStack_1ec = 4;
  ppuStack_1f4 = *(undefined ***)(param_1 + 0xc);
  piStack_1f0 = *(int **)(param_1 + 0x10);
  if (piStack_1f0 != (int *)0x0) {
    *piStack_1f0 = *piStack_1f0 + 1;
  }
  (**(code **)(**(int **)(param_1 + 4) + 0xc40))();
  CCharString::CCharString((CCharString *)&puStack_1bc,"M_WHouse_ManStart",-1);
  ppVar27 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&ppuStack_1d4;
  (**(code **)(**(int **)(param_1 + 4) + 0x120))();
  std::
  _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
            ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_1c4,
             extraout_EDX_00,ppVar27);
  CCharString::CCharString((CCharString *)&uStack_1c4,"M_WHouse_GuardPoint",-1);
  puVar28 = &uStack_1c4;
  ppVar27 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&piStack_1d0;
  (**(code **)(**(int **)(param_1 + 4) + 0x120))();
  std::
  _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
            ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_1cc,
             extraout_EDX_01,ppVar27);
  CCreatureAction_TrollWhackGroundBase::Initialise((CCreatureAction_TrollWhackGroundBase *)param_1);
  cVar2 = extraout_AL_00;
  do {
    if (cVar2 != '\0') {
      ppuStack_1d8 = &PTR__scalar_deleting_destructor__01238c8c;
      if ((piStack_1d0 != (int *)0x0) && (*piStack_1d0 = *piStack_1d0 + -1, *piStack_1d0 == 0)) {
        (*(code *)piStack_1d0[1])();
        operator_delete(piStack_1d0);
      }
      ppuStack_1d4 = (undefined **)0x0;
      piStack_1d0 = (int *)0x0;
      NHeroInformationScreens::CBase::CBase((CBase *)&ppuStack_1d8);
      ppuStack_1e4 = &PTR__scalar_deleting_destructor__01238c8c;
      if ((piStack_1dc != (int *)0x0) && (*piStack_1dc = *piStack_1dc + -1, *piStack_1dc == 0)) {
        (*(code *)piStack_1dc[1])();
        operator_delete(piStack_1dc);
      }
      piStack_1e0 = (int *)0x0;
      piStack_1dc = (int *)0x0;
      NHeroInformationScreens::CBase::CBase((CBase *)&ppuStack_1e4);
      if ((ppuStack_1e8 != (undefined **)0x0) &&
         (*ppuStack_1e8 = *ppuStack_1e8 + -1, *ppuStack_1e8 == (undefined *)0x0)) {
        (*(code *)ppuStack_1e8[1])();
        operator_delete(ppuStack_1e8);
      }
      uStack_1ec = 0;
      ppuStack_1e8 = (undefined **)0x0;
      ppuStack_1f4 = &PTR__vector_deleting_destructor__0126008c;
      CPhysicsMeshInfo::~CPhysicsMeshInfo((CPhysicsMeshInfo *)&ppuStack_1f4);
      return;
    }
    if (*(int *)(param_1 + 0x20) == 0) goto switchD_00db5526_default;
    CCreatureAction_TrollWhackGroundBase::Initialise
              ((CCreatureAction_TrollWhackGroundBase *)param_1);
    if (extraout_AL_01 != '\0') goto LAB_00db6afd;
    switch(*(undefined4 *)(param_1 + 0x20)) {
    case 1:
      (**(code **)(*DAT_0143e8f8 + 0x164))(*(undefined4 *)(*(int *)(param_1 + 0x14) + 0x108),0x2d);
      (**(code **)(**(int **)(param_1 + 4) + 0x754))(pCVar1,0);
      bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&stack0xfffffdfc);
      if (bVar3) {
        CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&stack0xfffffdfc);
      }
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&stack0xfffffdfc,4);
      while (cVar2 == '\0') {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_02 != '\0') goto LAB_00db6afd;
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_03 != '\0') goto LAB_00db6afd;
      CCharString::CCharString(aCStack_168,"M_BarrelManWalkOff",-1);
      (**(code **)(**(int **)(param_1 + 4) + 0x120))(aCStack_15c,aCStack_168);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)aCStack_168,
                 extraout_EDX_02,ppVar27);
      if (piStack_158 == (int *)0x0) {
        puVar5 = &DAT_0143e8e0;
      }
      else {
        puVar5 = (undefined4 *)(**(code **)(*piStack_158 + 0x18))();
      }
      uStack_150 = *puVar5;
      ppuStack_14c = (undefined **)puVar5[1];
      fVar25 = 2.0;
      uStack_148 = puVar5[2];
      pCVar7 = (CScriptThing *)
               CScriptGameResourceObjectScriptedThingBase::
               _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                         ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4);
      bVar3 = IsDistanceFromThingToPositionOver(pCVar7,(C3DVector *)&uStack_150,fVar25);
      C3DClothPrimitive::~C3DClothPrimitive(aCStack_120);
      if (bVar3) {
        do {
          (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_04 != '\0') {
LAB_00db6a0e:
            C3DClothPrimitive::~C3DClothPrimitive(aCStack_15c);
            goto LAB_00db6afd;
          }
          CScriptGameResourceObjectScriptedThingBase::
          _MoveToPosition_CScriptGameResourceObjectScriptedThingBase__UAEXABVC3DVector__MW4EScriptEntityMoveType___N2_Z
                    ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4,
                     (CScriptThing *)&uStack_150,(char *)0x0,(CCharString *)0x1,(CCharString *)0x0,
                     (CCharString *)0x0,SUB41(ppVar27,0),(bool)SUB41(puVar28,0));
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&ppuStack_1f4);
          if (bVar3) {
            do {
              (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_05 != '\0') goto LAB_00db6a0e;
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&ppuStack_1f4);
            } while (bVar3);
          }
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_06 != '\0') goto LAB_00db6a0e;
          fVar25 = 2.0;
          pCVar7 = (CScriptThing *)
                   CScriptGameResourceObjectScriptedThingBase::
                   _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                             ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4);
          bVar3 = IsDistanceFromThingToPositionOver(pCVar7,(C3DVector *)&uStack_150,fVar25);
          C3DClothPrimitive::~C3DClothPrimitive(aCStack_120);
        } while (bVar3);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      this = aCStack_15c;
      if (extraout_AL_07 != '\0') {
LAB_00db6a32:
        C3DClothPrimitive::~C3DClothPrimitive(this);
        goto LAB_00db6afd;
      }
      *(undefined4 *)(param_1 + 0x20) = 2;
      C3DClothPrimitive::~C3DClothPrimitive(this);
      break;
    case 2:
      iVar11 = (**(code **)(*DAT_0143e8f8 + 0x168))
                         (*(undefined4 *)(*(int *)(param_1 + 0x14) + 0x108));
      while (iVar11 != 0xf) {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_08 != '\0') goto LAB_00db6afd;
        iVar11 = (**(code **)(*DAT_0143e8f8 + 0x168))
                           (*(undefined4 *)(*(int *)(param_1 + 0x14) + 0x108));
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_09 != '\0') goto LAB_00db6afd;
      CCharString::CCharString((CCharString *)aaStack_170,"M_BarrelManWalkOff",-1);
      ppVar12 = apStack_138;
      (**(code **)(**(int **)(param_1 + 4) + 0x120))(ppVar12,aaStack_170);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                (aaStack_178,extraout_EDX_03,ppVar12);
      CCharString::CCharString(aCStack_18c,"M_BarrelManWalkOffAlt",-1);
      ppVar12 = apStack_134;
      (**(code **)(**(int **)(param_1 + 4) + 0x120))(ppVar12,aCStack_18c);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                (aaStack_194,extraout_EDX_04,ppVar12);
      if (piStack_144 == (int *)0x0) {
        puVar5 = &DAT_0143e8e0;
      }
      else {
        puVar5 = (undefined4 *)(**(code **)(*piStack_144 + 0x18))();
      }
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x694))(puVar5);
      if (cVar2 == '\0') {
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_10 != '\0') {
LAB_00db6a1f:
          C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)apStack_12c);
          this = (C3DClothPrimitive *)apStack_138;
          goto LAB_00db6a32;
        }
        ppVar12 = apStack_138;
      }
      else {
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_11 != '\0') goto LAB_00db6a1f;
        ppVar12 = apStack_12c;
      }
      (**(code **)(**(int **)(param_1 + 4) + 0x760))(pCVar1,ppVar12,0);
      *(undefined4 *)(param_1 + 0x20) = 3;
      C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)apStack_12c);
      C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)apStack_138);
      break;
    case 3:
      bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&ppuStack_1f4);
      if (bVar3) {
        CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&ppuStack_1f4);
      }
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      while (cVar2 == '\0') {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_12 != '\0') goto LAB_00db6afd;
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_13 != '\0') goto LAB_00db6afd;
      (**(code **)(**(int **)(param_1 + 4) + 0x800))(pCVar1,1);
      (**(code **)(**(int **)(param_1 + 4) + 0x754))(pCVar1,0);
      if (piStack_1e0 == (int *)0x0) {
        puVar5 = &DAT_0143e8e0;
      }
      else {
        puVar5 = (undefined4 *)(**(code **)(*piStack_1e0 + 0x18))();
      }
      piStack_144 = (int *)*puVar5;
      uStack_140 = puVar5[1];
      fVar25 = 2.0;
      uStack_13c = puVar5[2];
      pCVar7 = (CScriptThing *)
               CScriptGameResourceObjectScriptedThingBase::
               _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                         ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4);
      bVar3 = IsDistanceFromThingToPositionOver(pCVar7,(C3DVector *)&piStack_144,fVar25);
      C3DClothPrimitive::~C3DClothPrimitive(aCStack_114);
      if (bVar3) {
        do {
          (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_14 != '\0') goto LAB_00db6afd;
          CScriptGameResourceObjectScriptedThingBase::
          _MoveToPosition_CScriptGameResourceObjectScriptedThingBase__UAEXABVC3DVector__MW4EScriptEntityMoveType___N2_Z
                    ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4,
                     (CScriptThing *)&piStack_144,(char *)0x0,(CCharString *)0x1,(CCharString *)0x0,
                     (CCharString *)0x0,SUB41(ppVar27,0),(bool)SUB41(puVar28,0));
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&ppuStack_1f4);
          if (bVar3) {
            do {
              (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_15 != '\0') goto LAB_00db6afd;
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&ppuStack_1f4);
            } while (bVar3);
          }
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_16 != '\0') goto LAB_00db6afd;
          fVar25 = 2.0;
          pCVar7 = (CScriptThing *)
                   CScriptGameResourceObjectScriptedThingBase::
                   _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                             ((CScriptGameResourceObjectScriptedThingBase *)&ppuStack_1f4);
          bVar3 = IsDistanceFromThingToPositionOver(pCVar7,(C3DVector *)&piStack_144,fVar25);
          C3DClothPrimitive::~C3DClothPrimitive(aCStack_114);
        } while (bVar3);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_17 != '\0') goto LAB_00db6afd;
      *(undefined4 *)(param_1 + 0x20) = 4;
      break;
    case 4:
      *(undefined1 *)(*(int *)(param_1 + 0x14) + 0x73) = 1;
      iVar11 = **(int **)(param_1 + 4);
      uVar6 = (**(code **)(iVar11 + 0x118))(0);
      (**(code **)(iVar11 + 0x76c))(pCVar1,uVar6);
      (**(code **)(**(int **)(param_1 + 4) + 0x800))(pCVar1,2);
      (**(code **)(**(int **)(param_1 + 4) + 0x754))(pCVar1,1);
      iVar11 = **(int **)(param_1 + 4);
      uVar6 = (**(code **)(iVar11 + 0x118))(pCVar1);
      cVar2 = (**(code **)(iVar11 + 0x9e0))(uVar6);
      if (cVar2 != '\0') {
LAB_00db5c28:
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_21 != '\0') goto LAB_00db6afd;
        bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&ppuStack_1f4);
        if (bVar3) {
          CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&ppuStack_1f4);
        }
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
        while (cVar2 == '\0') {
          (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_22 != '\0') goto LAB_00db6afd;
          cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
        }
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_23 != '\0') goto LAB_00db6afd;
        CCarriedReadableDef::CCarriedReadableDef(aCStack_108);
        CCharString::CCharString((CCharString *)&stack0xfffffe68,"",-1);
        ppVar12 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&stack0xfffffe68;
        (**(code **)(**(int **)(param_1 + 4) + 0x5c8))(ppVar12,aCStack_108);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xfffffe60
                   ,extraout_EDX_08,ppVar12);
        piVar8 = *(int **)(param_1 + 4);
        (**(code **)(*piVar8 + 0x5ec))(1);
        iVar11 = **(int **)(param_1 + 4);
        uVar4 = CScriptGameResourceObjectScriptedThingBase::
                _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                          ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
        fVar19 = (float10)(**(code **)(iVar11 + 0x420))();
        fVar20 = (float10)_DAT_0122dedc;
        C3DClothPrimitive::~C3DClothPrimitive(aCStack_e0);
        if (fVar20 < fVar19) {
          bVar3 = false;
          pCVar24 = (CCharString *)0x1;
          pCVar23 = (CCharString *)0x0;
          pCVar22 = (CCharString *)0x0;
          pcVar21 = "TEXT_QST_048_BARRELMAN_THANKS";
          pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
          CScriptGameResourceObjectScriptedThingBase::
          _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                    ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffdfc,pCVar7,pcVar21,
                     pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&stack0xfffffdfc);
          if (bVar3) {
            do {
              (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_24 != '\0') {
                (**(code **)(*piVar8 + 0x5ec))(0);
                pCVar15 = (CScriptGameResourceObjectMovieBase *)aCStack_108;
                goto LAB_00db6af8;
              }
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&stack0xfffffdfc);
            } while (bVar3);
          }
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_25 != '\0') {
            (**(code **)(*piVar8 + 0x5ec))(0);
            pCVar15 = (CScriptGameResourceObjectMovieBase *)aCStack_108;
            goto LAB_00db6af8;
          }
        }
        NScript::CQ_NewOakValeIntroScript::AddGoodDeed
                  (*(CQ_NewOakValeIntroScript **)(param_1 + 0x14));
        (**(code **)(*piVar8 + 0x5ec))(0);
        pCVar15 = (CScriptGameResourceObjectMovieBase *)&uStack_13c;
LAB_00db5daf:
        CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase(pCVar15);
        CCharString::CCharString((CCharString *)&stack0xfffffe54,"BRAIN_GOOD_VILLAGER_BASE",-1);
        (**(code **)(**(int **)(param_1 + 4) + 0x934))(pCVar1,&stack0xfffffe54);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  (aaStack_178,extraout_EDX_09,ppVar27);
        *(undefined4 *)(param_1 + 0x20) = 5;
        break;
      }
      fVar25 = 10.0;
      pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
      bVar3 = IsDistanceBetweenThingsUnder(pCVar1,pCVar7,fVar25);
      if (bVar3) goto LAB_00db5c28;
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_18 != '\0') goto LAB_00db6afd;
      ppVar12 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
                (**(code **)(**(int **)(param_1 + 4) + 0x5b0))(pCVar1,0,0);
      CCharString::CCharString
                ((CCharString *)&uStack_188,"TEXT_QST_048_SCRMSG_BARRELMAN_WHERE_GONE",-1);
      iVar11 = **(int **)(param_1 + 4);
      uVar6 = CCarriedReadableDef::CCarriedReadableDef(aCStack_88);
      (**(code **)(iVar11 + 0x5b8))(ppVar12,&uStack_188,0,pCVar1,uVar6);
      C3DClothPrimitive::~C3DClothPrimitive(aCStack_9c);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xfffffe64,
                 extraout_EDX_05,ppVar12);
      param_1[0x1d] = (CWorldMap)0x1;
      CCarriedReadableDef::CCarriedReadableDef(aCStack_118);
      CCharString::CCharString(aCStack_180,"",-1);
      pCVar22 = aCStack_180;
      (**(code **)(**(int **)(param_1 + 4) + 0x5c8))(pCVar22,aCStack_118);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_188,
                 extraout_EDX_06,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar22)
      ;
      piVar8 = *(int **)(param_1 + 4);
      (**(code **)(*piVar8 + 0x5ec))(1);
      CCharString::CCharString
                ((CCharString *)&ppuStack_190,"TEXT_QST_048_INSTRUCTION_LEFT_WAREHOUSE_UNATTENDED",
                 -1);
      ppVar12 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&ppuStack_190;
      (**(code **)(**(int **)(param_1 + 4) + 0x1cc))();
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                (aaStack_194,extraout_EDX_07,ppVar12);
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0xa0))();
      while (cVar2 == '\0') {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_19 != '\0') {
          (**(code **)(*piVar8 + 0x5ec))(0);
          pCVar15 = aCStack_f8;
          goto LAB_00db6af8;
        }
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0xa0))();
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_20 == '\0') {
        NScript::CQ_NewOakValeIntroScript::AddBadDeed
                  (*(CQ_NewOakValeIntroScript **)(param_1 + 0x14),1);
        (**(code **)(*piVar8 + 0x5ec))(0);
        pCVar15 = (CScriptGameResourceObjectMovieBase *)apStack_12c;
        goto LAB_00db5daf;
      }
      (**(code **)(*piVar8 + 0x5ec))(0);
      pCVar15 = aCStack_f8;
      goto LAB_00db6af8;
    }
switchD_00db5526_default:
    CCharString::CCharString((CCharString *)&uStack_188,"SCRIPT_NAME_HERO",-1);
    ppuVar18 = ppuStack_1c8;
    ppuVar17 = (undefined **)((uint)ppuStack_1c8 | 1);
    ppuStack_1c8 = ppuVar17;
    cVar2 = (**(code **)(*(int *)pCVar1 + 0x54))(&uStack_188);
    ppVar16 = extraout_EDX_10;
    if (cVar2 == '\0') {
      CCharString::CCharString(aCStack_174,"SCRIPT_NAME_HERO",-1);
      ppuVar17 = (undefined **)((uint)ppuVar18 | 3);
      ppuStack_1c8 = ppuVar17;
      cVar2 = (**(code **)(*(int *)pCVar1 + 0xa8))(aCStack_174);
      ppVar16 = extraout_EDX_11;
      if (cVar2 != '\0') {
        CCharString::CCharString((CCharString *)&ppuStack_190,"SCRIPT_NAME_HERO",-1);
        ppuVar17 = (undefined **)((uint)ppuVar18 | 7);
        ppuStack_1c8 = ppuVar17;
        cVar2 = (**(code **)(*(int *)pCVar1 + 0xa4))(0xe,&ppuStack_190);
        ppVar16 = extraout_EDX_12;
        if (cVar2 == '\0') goto LAB_00db5e85;
      }
      bVar3 = false;
    }
    else {
LAB_00db5e85:
      bVar3 = true;
    }
    if (((uint)ppuVar17 & 4) != 0) {
      ppuVar17 = (undefined **)((uint)ppuVar17 & 0xfffffffb);
      ppuStack_1c8 = ppuVar17;
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&ppuStack_190,
                 ppVar16,ppVar27);
      ppVar16 = extraout_EDX_13;
    }
    if (((uint)ppuVar17 & 2) != 0) {
      ppuVar17 = (undefined **)((uint)ppuVar17 & 0xfffffffd);
      ppuStack_1c8 = ppuVar17;
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)aCStack_174,
                 ppVar16,ppVar27);
      ppVar16 = extraout_EDX_14;
    }
    if (((uint)ppuVar17 & 1) != 0) {
      ppuVar17 = (undefined **)((uint)ppuVar17 & 0xfffffffe);
      ppuStack_1c8 = ppuVar17;
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_188,
                 ppVar16,ppVar27);
    }
    if (bVar3) {
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_26 != '\0') goto LAB_00db6afd;
      iVar11 = **(int **)(param_1 + 4);
      uVar6 = (**(code **)(iVar11 + 0x118))();
      (**(code **)(iVar11 + 0x95c))(pCVar1,uVar6);
      iVar11 = **(int **)(param_1 + 4);
      uVar6 = (**(code **)(iVar11 + 0x118))(pCVar1);
      (**(code **)(iVar11 + 0x95c))(uVar6);
      NScript::CQ_NewOakValeIntroScript::AddBadDeed
                (*(CQ_NewOakValeIntroScript **)(param_1 + 0x14),2);
      bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&stack0xfffffdfc);
      if (bVar3) {
        CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&stack0xfffffdfc);
      }
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&stack0xfffffdfc,4);
      while (cVar2 == '\0') {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_27 != '\0') goto LAB_00db6afd;
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_28 != '\0') goto LAB_00db6afd;
      CBaseIntelligentPointer::CBaseIntelligentPointer((CBaseIntelligentPointer *)&ppuStack_1b0);
      ppuStack_1b0 = &PTR__scalar_deleting_destructor__01260ef4;
      CCharString::CCharString((CCharString *)&stack0xfffffe60,"",-1);
      ppVar12 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&stack0xfffffe60;
      (**(code **)(**(int **)(param_1 + 4) + 0x5c8))(ppVar12,&ppuStack_1b0);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xfffffe58,
                 extraout_EDX_15,ppVar12);
      piVar8 = *(int **)(param_1 + 4);
      (**(code **)(*piVar8 + 0x5ec))(1);
      iVar11 = **(int **)(param_1 + 4);
      uVar4 = CScriptGameResourceObjectScriptedThingBase::
              _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                        ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
      fVar19 = (float10)(**(code **)(iVar11 + 0x420))();
      fVar20 = (float10)_DAT_0122dedc;
      C3DClothPrimitive::~C3DClothPrimitive(aCStack_c8);
      if (fVar19 <= fVar20) {
LAB_00db6088:
        (**(code **)(*piVar8 + 0x5ec))(0);
        CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase
                  ((CScriptGameResourceObjectMovieBase *)&ppuStack_1b0);
        goto LAB_00db6933;
      }
      bVar3 = false;
      pCVar24 = (CCharString *)0x1;
      pCVar23 = (CCharString *)0x0;
      pCVar22 = (CCharString *)0x0;
      pcVar21 = "TEXT_QST_048_BARRELMAN_CAREFUL";
      pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
      CScriptGameResourceObjectScriptedThingBase::
      _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffdfc,pCVar7,pcVar21,
                 pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
      bVar3 = CScriptThing::
              _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                        ((CScriptThing *)&stack0xfffffdfc);
      if (bVar3) {
        do {
          (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_29 != '\0') {
            (**(code **)(*piVar8 + 0x5ec))(0);
            pCVar15 = (CScriptGameResourceObjectMovieBase *)&ppuStack_1b0;
            goto LAB_00db6af8;
          }
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&stack0xfffffdfc);
        } while (bVar3);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_30 == '\0') goto LAB_00db6088;
      (**(code **)(*piVar8 + 0x5ec))(0);
      pCVar15 = (CScriptGameResourceObjectMovieBase *)&ppuStack_1b0;
      goto LAB_00db6af8;
    }
    if (*(int *)(param_1 + 0x20) == 0) {
      fVar25 = DAT_013ac858;
      pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
      bVar3 = IsDistanceBetweenThingsUnder(pCVar1,pCVar7,fVar25);
      ppVar16 = extraout_EDX_16;
      if (!bVar3) goto LAB_00db60c9;
LAB_00db60fb:
      bVar3 = true;
    }
    else {
LAB_00db60c9:
      CCharString::CCharString(aCStack_180,"SCRIPT_NAME_HERO",-1);
      ppuVar17 = (undefined **)((uint)ppuVar17 | 8);
      ppuStack_1c8 = ppuVar17;
      cVar2 = (**(code **)(*(int *)pCVar1 + 0x6c))(aCStack_180);
      bVar3 = false;
      ppVar16 = extraout_EDX_17;
      if (cVar2 != '\0') goto LAB_00db60fb;
    }
    if (((uint)ppuVar17 & 8) != 0) {
      ppuStack_1c8 = (undefined **)((uint)ppuVar17 & 0xfffffff7);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)aCStack_180,
                 ppVar16,ppVar27);
    }
    if (bVar3) {
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_31 != '\0') goto LAB_00db6afd;
      bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&ppuStack_1f4);
      if (bVar3) {
        CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&ppuStack_1f4);
      }
      cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      while (cVar2 == '\0') {
        (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_32 != '\0') goto LAB_00db6afd;
        cVar2 = (**(code **)(**(int **)(param_1 + 4) + 0x20))(pCVar1,&ppuStack_1f4,4);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_33 != '\0') goto LAB_00db6afd;
      CCarriedReadableDef::CCarriedReadableDef((CCarriedReadableDef *)&piStack_1c0);
      CCharString::CCharString(aCStack_16c,"",-1);
      pCVar22 = aCStack_16c;
      (**(code **)(**(int **)(param_1 + 4) + 0x5c8))(pCVar22,&piStack_1c0);
      std::
      _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)aCStack_174,
                 extraout_EDX_18,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar22)
      ;
      ppuVar18 = *(undefined ***)(param_1 + 4);
      uVar6 = 1;
      ppuStack_1d4 = ppuVar18;
      (**(code **)(*ppuVar18 + 0x5ec))();
      uVar4 = (undefined1)uVar6;
      iVar11 = *(int *)(param_1 + 0x20);
      if (iVar11 != 0) {
        if (3 < iVar11) {
          if (iVar11 != 5) goto LAB_00db684c;
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_44 != '\0') goto LAB_00db6ae0;
          if (param_1[0x1d] == (CWorldMap)0x0) {
            CCreatureAction_TrollWhackGroundBase::Initialise
                      ((CCreatureAction_TrollWhackGroundBase *)param_1);
            if (extraout_AL_52 != '\0') goto LAB_00db6ae0;
            iVar11 = **(int **)(param_1 + 4);
            uVar6 = CScriptGameResourceObjectScriptedThingBase::
                    _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                              ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
            fVar19 = (float10)(**(code **)(iVar11 + 0x420))(uVar6);
            fVar20 = (float10)_DAT_0122dedc;
            C3DClothPrimitive::~C3DClothPrimitive(aCStack_b8);
            ppuVar18 = ppuStack_1d8;
            if (fVar20 < fVar19) {
              bVar3 = false;
              pCVar24 = (CCharString *)0x1;
              pCVar23 = (CCharString *)0x0;
              pCVar22 = (CCharString *)0x0;
              pcVar21 = "TEXT_QST_048_BARRELMAN_NO_TIME";
              pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
              CScriptGameResourceObjectScriptedThingBase::
              _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                        ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,
                         pcVar21,pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&stack0xfffffe00);
              if (bVar3) {
                do {
                  (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
                  CCreatureAction_TrollWhackGroundBase::Initialise
                            ((CCreatureAction_TrollWhackGroundBase *)param_1);
                  if (extraout_AL_53 != '\0') goto LAB_00db6783;
                  bVar3 = CScriptThing::
                          _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                    ((CScriptThing *)&stack0xfffffe00);
                } while (bVar3);
              }
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              ppuVar18 = ppuStack_1d8;
              if (extraout_AL_54 != '\0') {
LAB_00db6ae6:
                puVar14 = *ppuStack_1d8;
                goto LAB_00db6aec;
              }
            }
          }
          else {
            CCreatureAction_TrollWhackGroundBase::Initialise
                      ((CCreatureAction_TrollWhackGroundBase *)param_1);
            if (extraout_AL_45 != '\0') goto LAB_00db6ac9;
            if (*(char *)(*(int *)(param_1 + 0x14) + 0x75) != '\0') {
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_46 != '\0') goto LAB_00db6ae0;
              iVar11 = **(int **)(param_1 + 4);
              uVar6 = CScriptGameResourceObjectScriptedThingBase::
                      _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                                ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
              fVar20 = (float10)(**(code **)(iVar11 + 0x420))(uVar6);
              puVar5 = (undefined4 *)CONCAT13(1,(int3)puVar28);
              if (fVar20 <= (float10)_DAT_0122dedc) {
                puVar5 = (undefined4 *)((uint)puVar28 & 0xffffff);
              }
              puVar28 = puVar5;
              C3DClothPrimitive::~C3DClothPrimitive(aCStack_d0);
              if ((char)((uint)puVar28 >> 0x18) != '\0') {
                bVar3 = false;
                pCVar24 = (CCharString *)0x1;
                pCVar23 = (CCharString *)0x0;
                pCVar22 = (CCharString *)0x0;
                pcVar21 = "TEXT_QST_048_BARRELMAN_LETDOWN_BROKEN";
                pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
                CScriptGameResourceObjectScriptedThingBase::
                _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                          ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,
                           pcVar21,pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
                bVar3 = CScriptThing::
                        _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                  ((CScriptThing *)&stack0xfffffe00);
                if (bVar3) {
                  do {
                    (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
                    CCreatureAction_TrollWhackGroundBase::Initialise
                              ((CCreatureAction_TrollWhackGroundBase *)param_1);
                    if (extraout_AL_47 != '\0') goto LAB_00db6ac9;
                    bVar3 = CScriptThing::
                            _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                      ((CScriptThing *)&stack0xfffffe00);
                  } while (bVar3);
                }
                CCreatureAction_TrollWhackGroundBase::Initialise
                          ((CCreatureAction_TrollWhackGroundBase *)param_1);
                if (extraout_AL_48 != '\0') goto LAB_00db6ae0;
              }
              goto LAB_00db684c;
            }
            CCreatureAction_TrollWhackGroundBase::Initialise
                      ((CCreatureAction_TrollWhackGroundBase *)param_1);
            if (extraout_AL_49 != '\0') goto LAB_00db6ac9;
            iVar11 = **(int **)(param_1 + 4);
            uVar6 = CScriptGameResourceObjectScriptedThingBase::
                    _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                              ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
            fVar19 = (float10)(**(code **)(iVar11 + 0x420))(uVar6);
            fVar20 = (float10)_DAT_0122dedc;
            C3DClothPrimitive::~C3DClothPrimitive(aCStack_a0);
            ppuVar18 = ppuStack_1d8;
            if (fVar20 < fVar19) {
              bVar3 = false;
              pCVar24 = (CCharString *)0x1;
              pCVar23 = (CCharString *)0x0;
              pCVar22 = (CCharString *)0x0;
              pcVar21 = "TEXT_QST_048_BARRELMAN_LETDOWN_NOT_BROKE";
              pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
              CScriptGameResourceObjectScriptedThingBase::
              _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                        ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,
                         pcVar21,pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&stack0xfffffe00);
              if (bVar3) {
                do {
                  (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
                  CCreatureAction_TrollWhackGroundBase::Initialise
                            ((CCreatureAction_TrollWhackGroundBase *)param_1);
                  if (extraout_AL_50 != '\0') goto LAB_00db6ae6;
                  bVar3 = CScriptThing::
                          _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                    ((CScriptThing *)&stack0xfffffe00);
                } while (bVar3);
              }
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              ppuVar18 = ppuStack_1d8;
              if (extraout_AL_51 != '\0') {
LAB_00db6783:
                (**(code **)(*ppuStack_1d8 + 0x5ec))(0);
                goto LAB_00db6af4;
              }
            }
          }
LAB_00db684c:
          bVar3 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)&stack0xfffffe00);
          if (bVar3) {
            CMemoryDataOutputStream::Clear((CMemoryDataOutputStream *)&stack0xfffffe00);
          }
          (**(code **)(*ppuVar18 + 0x5ec))(0);
          CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase
                    ((CScriptGameResourceObjectMovieBase *)&piStack_1c0);
          goto LAB_00db6933;
        }
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_41 == '\0') {
          iVar11 = **(int **)(param_1 + 4);
          uVar6 = CScriptGameResourceObjectScriptedThingBase::
                  _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                            ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
          fVar20 = (float10)(**(code **)(iVar11 + 0x420))(uVar6);
          puVar5 = (undefined4 *)CONCAT13(1,(int3)puVar28);
          if (fVar20 <= (float10)_DAT_0122dedc) {
            puVar5 = (undefined4 *)((uint)puVar28 & 0xffffff);
          }
          puVar28 = puVar5;
          C3DClothPrimitive::~C3DClothPrimitive(aCStack_f4);
          if ((char)((uint)puVar28 >> 0x18) != '\0') {
            bVar3 = false;
            pCVar24 = (CCharString *)0x1;
            pCVar23 = (CCharString *)0x0;
            pCVar22 = (CCharString *)0x0;
            pcVar21 = "TEXT_QST_048_BARRELMAN_NOT_LARKING";
            pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
            CScriptGameResourceObjectScriptedThingBase::
            _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                      ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,pcVar21
                       ,pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
            bVar3 = CScriptThing::
                    _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                              ((CScriptThing *)&stack0xfffffe00);
            if (bVar3) {
              do {
                (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
                CCreatureAction_TrollWhackGroundBase::Initialise
                          ((CCreatureAction_TrollWhackGroundBase *)param_1);
                if (extraout_AL_42 != '\0') goto LAB_00db6ae0;
                bVar3 = CScriptThing::
                        _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                  ((CScriptThing *)&stack0xfffffe00);
              } while (bVar3);
            }
            CCreatureAction_TrollWhackGroundBase::Initialise
                      ((CCreatureAction_TrollWhackGroundBase *)param_1);
            if (extraout_AL_43 != '\0') goto LAB_00db6ac9;
          }
          goto LAB_00db684c;
        }
        goto LAB_00db6ac9;
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_34 != '\0') goto LAB_00db6ae0;
      CTimer::CTimer((CTimer *)&piStack_1d0);
      piVar8 = (int *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
      fVar25 = 4.0;
      pCVar9 = (C3DVector *)(**(code **)(*piVar8 + 0x18))();
      bVar3 = IsDistanceFromThingToPositionOver(pCVar1,pCVar9,fVar25);
      piVar8 = piStack_1d0;
      uVar4 = (undefined1)uVar6;
      if (bVar3) {
        do {
          (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_35 != '\0') goto LAB_00db6ac0;
          piVar10 = (int *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
          pCVar26 = (CCharString *)0x1;
          pCVar24 = (CCharString *)0x0;
          pCVar23 = (CCharString *)0x1;
          pcVar21 = (char *)0x40000000;
          pCVar7 = (CScriptThing *)(**(code **)(*piVar10 + 0x18))();
          CScriptGameResourceObjectScriptedThingBase::
          _MoveToPosition_CScriptGameResourceObjectScriptedThingBase__UAEXABVC3DVector__MW4EScriptEntityMoveType___N2_Z
                    ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,pcVar21,
                     pCVar23,pCVar24,pCVar26,SUB41(uVar6,0),SUB41(pCVar22,0));
          (**(code **)(*DAT_0143e8f8 + 0x164))(piVar8,2);
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&stack0xfffffe00);
          if (bVar3) {
            do {
              iVar11 = (**(code **)(*DAT_0143e8f8 + 0x168))(piVar8);
              if (iVar11 < 1) break;
              (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_36 != '\0') goto LAB_00db6ad7;
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&stack0xfffffe00);
            } while (bVar3);
          }
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_37 != '\0') goto LAB_00db6ac0;
          piVar10 = (int *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
          fVar25 = 4.0;
          pCVar9 = (C3DVector *)(**(code **)(*piVar10 + 0x18))();
          bVar3 = IsDistanceFromThingToPositionOver(pCVar1,pCVar9,fVar25);
          uVar4 = (undefined1)uVar6;
        } while (bVar3);
      }
      CCreatureAction_TrollWhackGroundBase::Initialise
                ((CCreatureAction_TrollWhackGroundBase *)param_1);
      if (extraout_AL_38 == '\0') {
        iVar11 = **(int **)(param_1 + 4);
        uVar6 = CScriptGameResourceObjectScriptedThingBase::
                _GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ
                          ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00);
        fVar20 = (float10)(**(code **)(iVar11 + 0x420))(uVar6);
        puVar5 = (undefined4 *)CONCAT13(1,(int3)puVar28);
        if (fVar20 <= (float10)_DAT_0122dedc) {
          puVar5 = (undefined4 *)((uint)puVar28 & 0xffffff);
        }
        puVar28 = puVar5;
        C3DClothPrimitive::~C3DClothPrimitive(aCStack_ac);
        if ((char)((uint)puVar28 >> 0x18) != '\0') {
          bVar3 = false;
          pCVar24 = (CCharString *)0x1;
          pCVar23 = (CCharString *)0x0;
          pCVar22 = (CCharString *)0x0;
          pcVar21 = "TEXT_QST_048_BARRELMAN_FAVOUR";
          pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
          CScriptGameResourceObjectScriptedThingBase::
          _Speak_CScriptGameResourceObjectScriptedThingBase__UAEXABVCScriptThing__PBDW4ETextGroupSelectionMethod___N33_Z
                    ((CScriptGameResourceObjectScriptedThingBase *)&stack0xfffffe00,pCVar7,pcVar21,
                     pCVar22,pCVar23,pCVar24,bVar3,(bool)uVar4);
          bVar3 = CScriptThing::
                  _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                            ((CScriptThing *)&stack0xfffffe00);
          if (bVar3) {
            do {
              (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
              CCreatureAction_TrollWhackGroundBase::Initialise
                        ((CCreatureAction_TrollWhackGroundBase *)param_1);
              if (extraout_AL_39 != '\0') goto LAB_00db6ac0;
              bVar3 = CScriptThing::
                      _IsPerformingScriptTask_CScriptGameResourceObjectScriptedThingBase__UBE_NXZ
                                ((CScriptThing *)&stack0xfffffe00);
            } while (bVar3);
          }
          CCreatureAction_TrollWhackGroundBase::Initialise
                    ((CCreatureAction_TrollWhackGroundBase *)param_1);
          if (extraout_AL_40 != '\0') goto LAB_00db6ad7;
        }
        (**(code **)(**(int **)(param_1 + 4) + 0x5d4))(0x3f800000,0x3f800000,0xff000000);
        (**(code **)(**(int **)(param_1 + 4) + 0x5e0))(0x40000000);
        CCharString::CCharString(aCStack_1b8,"M_WHouse_GuardPoint",-1);
        piVar8 = *(int **)(param_1 + 4);
        iVar11 = *piVar8;
        uVar6 = (**(code **)(iVar11 + 0x120))(auStack_a4,aCStack_1b8,0);
        ppVar12 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
                  (**(code **)(*piVar8 + 0x118))(uVar6);
        (**(code **)(iVar11 + 0x760))();
        C3DClothPrimitive::~C3DClothPrimitive(aCStack_b8);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_1cc,
                   extraout_EDX_19,ppVar12);
        CCharString::CCharString((CCharString *)&uStack_1c4,"M_BarrelManHiddenPos",-1);
        iVar11 = **(int **)(param_1 + 4);
        uVar6 = (**(code **)(iVar11 + 0x120))(aCStack_a0,&uStack_1c4,0);
        pCVar7 = pCVar1;
        (**(code **)(iVar11 + 0x760))(pCVar1,uVar6);
        C3DClothPrimitive::~C3DClothPrimitive(aCStack_b4);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&ppuStack_1d8,
                   extraout_EDX_20,(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)pCVar7
                  );
        *(undefined4 *)(param_1 + 0x20) = 2;
        (**(code **)(**(int **)(param_1 + 4) + 0x5a4))(pCVar1);
        (**(code **)(**(int **)(param_1 + 4) + 0x5d8))();
        (**(code **)(*DAT_0143e8f8 + 0x164))(*(undefined4 *)(*(int *)(param_1 + 0x14) + 0x108),0x2d)
        ;
        *(undefined1 *)(*(int *)(param_1 + 0x14) + 0x72) = 1;
        CTimer::~CTimer((CTimer *)&piStack_1d0);
        ppuVar18 = ppuStack_1d8;
        goto LAB_00db684c;
      }
LAB_00db6ad7:
      CTimer::~CTimer((CTimer *)&piStack_1d0);
LAB_00db6ae0:
      puVar14 = *ppuVar18;
LAB_00db6aec:
      (**(code **)(puVar14 + 0x5ec))(0);
      goto LAB_00db6af4;
    }
    if ((*(int *)(param_1 + 0x20) == 0) &&
       ((param_1[0x1e] == (CWorldMap)0x0 || (iVar11 = rand(), iVar11 % DAT_013ac854 == 0)))) {
      fVar25 = 15.0;
      pCVar7 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 4) + 0x118))();
      bVar3 = IsDistanceBetweenThingsUnder(pCVar1,pCVar7,fVar25);
      if (bVar3) {
        CCreatureAction_TrollWhackGroundBase::Initialise
                  ((CCreatureAction_TrollWhackGroundBase *)param_1);
        if (extraout_AL_55 != '\0') goto LAB_00db6afd;
        param_1[0x1e] = (CWorldMap)0x1;
        uVar6 = (**(code **)(**(int **)(param_1 + 4) + 0x5b0))(pCVar1,0,0);
        CCharString::CCharString
                  ((CCharString *)&stack0xfffffe68,"TEXT_QST_048_BARRELMAN_OVERHEAR",-1);
        iVar11 = **(int **)(param_1 + 4);
        uVar13 = CCarriedReadableDef::CCarriedReadableDef(aCStack_e8);
        (**(code **)(iVar11 + 0x5b8))(uVar6,&stack0xfffffe68,0,pCVar1,uVar13);
        C3DClothPrimitive::~C3DClothPrimitive(aCStack_dc);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)aCStack_18c,
                   extraout_EDX_21,ppVar27);
      }
    }
LAB_00db6933:
    (**(code **)(**(int **)(param_1 + 4) + 0x1c))();
    CCreatureAction_TrollWhackGroundBase::Initialise
              ((CCreatureAction_TrollWhackGroundBase *)param_1);
    cVar2 = extraout_AL_56;
  } while( true );
LAB_00db6ac0:
  CTimer::~CTimer((CTimer *)&piStack_1d0);
LAB_00db6ac9:
  (**(code **)(*ppuVar18 + 0x5ec))(0);
LAB_00db6af4:
  pCVar15 = (CScriptGameResourceObjectMovieBase *)&piStack_1c0;
LAB_00db6af8:
  CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase(pCVar15);
LAB_00db6afd:
  C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&ppuStack_1d8);
  C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&ppuStack_1e4);
  CScriptGameResourceObjectMovieBase::~CScriptGameResourceObjectMovieBase
            ((CScriptGameResourceObjectMovieBase *)&ppuStack_1f4);
  return;
}


