/* Ghidra project FableTLC/Fable.exe; function entry 0x00DB4F70; generated by DecompFuncsToDirectory.java. */


/* autoname-t5 [medium]: Strings 'HUD_CLOCK_ICON', 'M_WHouse_GuardPoint'; distance check loop; guard
   post check */

void __fastcall Script_Guard_Duty(CScriptBase *param_1)

{
  CScriptBase CVar1;
  bool bVar2;
  int iVar3;
  CScriptThing *pCVar4;
  CCharString **ppCVar5;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  undefined8 uVar6;
  float fVar7;
  undefined1 **ppuVar8;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar9;
  CCharString *pCStack_48;
  undefined1 *puStack_44;
  undefined1 *puStack_40;
  CCharString *pCStack_3c;
  undefined1 uStack_20;
  undefined1 uStack_1f;
  undefined1 uStack_1e;
  undefined1 uStack_1d;
  CCharString aCStack_1c [4];
  CCharString aCStack_18 [24];
  
  iVar3 = (**(code **)(*DAT_0143e8f8 + 0x168))();
  while (iVar3 < 1) {
    (**(code **)(**(int **)(param_1 + 0x40) + 0x1c))();
    bVar2 = CScriptBase::IsActiveThreadTerminating(param_1);
    if (bVar2) {
      return;
    }
    iVar3 = (**(code **)(*DAT_0143e8f8 + 0x168))();
  }
  bVar2 = CScriptBase::IsActiveThreadTerminating(param_1);
  if (!bVar2) {
    pCStack_3c = (CCharString *)0xdb4fe1;
    CCharString::CCharString(aCStack_1c,"",-1);
    pCStack_3c = (CCharString *)0xdb4ff1;
    CCharString::CCharString(aCStack_18,"HUD_CLOCK_ICON",-1);
    pCStack_3c = aCStack_18;
    puStack_40 = &stack0xffffffdc;
    puStack_44 = &uStack_20;
    pCStack_48 = (CCharString *)0x0;
    uStack_1e = 0;
    uStack_1f = 0xff;
    uStack_20 = 0;
    uStack_1d = 0xff;
    ppVar9 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)0x42340000;
    uVar6 = (**(code **)(**(int **)(param_1 + 0x40) + 0x510))();
    *(int *)(param_1 + 0x60) = (int)uVar6;
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffcc,
               (pair<EHeroMorphType,CParticleMorphs::CEntry> *)((ulonglong)uVar6 >> 0x20),ppVar9);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffc8,
               extraout_EDX,ppVar9);
    CCharString::CCharString((CCharString *)&stack0xffffffcc,"M_WHouse_GuardPoint",-1);
    ppVar9 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&stack0xffffffd4;
    (**(code **)(**(int **)(param_1 + 0x40) + 0x120))(ppVar9,&stack0xffffffcc);
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&pCStack_3c,
               extraout_EDX_00,ppVar9);
    CVar1 = param_1[0x73];
    while (CVar1 == (CScriptBase)0x0) {
      (**(code **)(**(int **)(param_1 + 0x40) + 0x1c))();
      bVar2 = CScriptBase::IsActiveThreadTerminating(param_1);
      if (bVar2) goto LAB_00db5192;
      fVar7 = 2.0;
      pCVar4 = (CScriptThing *)(**(code **)(**(int **)(param_1 + 0x40) + 0x118))();
      bVar2 = IsDistanceBetweenThingsUnder(pCVar4,(CScriptThing *)&stack0xffffffcc,fVar7);
      if (bVar2) {
        ppuVar8 = &puStack_44;
        puStack_44 = (undefined1 *)0xff00ff00;
        pCStack_48 = (CCharString *)0xff00ff00;
        ppCVar5 = &pCStack_48;
      }
      else {
        ppuVar8 = &puStack_40;
        puStack_40 = (undefined1 *)0xffff0000;
        pCStack_3c = (CCharString *)0xffff0000;
        ppCVar5 = &pCStack_3c;
      }
      (**(code **)(**(int **)(param_1 + 0x40) + 0x534))
                (*(undefined4 *)(param_1 + 0x60),ppCVar5,ppuVar8);
      iVar3 = **(int **)(param_1 + 0x40);
      pCStack_48 = (CCharString *)
                   (**(code **)(*DAT_0143e8f8 + 0x168))
                             (*(undefined4 *)(param_1 + 0x108),0xbf800000,0xbf800000);
      (**(code **)(iVar3 + 0x530))(*(undefined4 *)(param_1 + 0x60),(float)(int)pCStack_48);
      CVar1 = param_1[0x73];
    }
    bVar2 = CScriptBase::IsActiveThreadTerminating(param_1);
    if (!bVar2) {
      (**(code **)(**(int **)(param_1 + 0x40) + 0x548))(*(undefined4 *)(param_1 + 0x60));
    }
LAB_00db5192:
    C3DClothPrimitive::~C3DClothPrimitive((C3DClothPrimitive *)&stack0xffffffcc);
  }
  return;
}


