/* Ghidra project FableTLC/Fable.exe; function entry 0x00DBE2E0; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.6202443419279919 <- ego_r]
   public: void __thiscall NScript::CQ_FireHeartScript::CheckGameEnding(void) */

void __thiscall NScript::CQ_FireHeartScript::CheckGameEnding(CQ_FireHeartScript *this)

{
  bool bVar1;
  int iVar2;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar3;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_01;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_02;
  CCharString *pCStack_24;
  CCharString aCStack_10 [4];
  CCharString aCStack_c [4];
  CCharString aCStack_8 [4];
  undefined1 auStack_4 [4];
  
  iVar2 = (**(code **)(**(int **)(this + 0x40) + 0x1fc))();
  while( true ) {
    if (2 < iVar2) {
      bVar1 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
      if (!bVar1) {
        pCStack_24 = (CCharString *)0xdbe33d;
        CCharString::CCharString(aCStack_8,"",-1);
        pCStack_24 = (CCharString *)0xdbe34d;
        CCharString::CCharString(aCStack_c,"",-1);
        pCStack_24 = (CCharString *)0xdbe35d;
        CCharString::CCharString(aCStack_10,"TEXT_QUEST_OAKVALE_INTRO_OBJECTIVE_03",-1);
        iVar2 = **(int **)(this + 0x40);
        pCStack_24 = aCStack_10;
        ppVar3 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)
                 (**(code **)(**(int **)(this + 0x40) + 0xa3c))(auStack_4);
        (**(code **)(iVar2 + 0x4a0))();
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffe8
                   ,extraout_EDX,ppVar3);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&pCStack_24,
                   extraout_EDX_00,ppVar3);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffe0
                   ,extraout_EDX_01,ppVar3);
        std::
        _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
                  ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&stack0xffffffe4
                   ,extraout_EDX_02,ppVar3);
      }
      return;
    }
    (**(code **)(**(int **)(this + 0x40) + 0x1c))();
    bVar1 = CScriptBase::IsActiveThreadTerminating((CScriptBase *)this);
    if (bVar1) break;
    iVar2 = (**(code **)(**(int **)(this + 0x40) + 0x1fc))();
  }
  return;
}


