/* Ghidra project FableTLC/Fable.exe; function entry 0x00DBCD00; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.968675738445847 <- ego_r]
   private: void __thiscall NScript::CQ_NewOakValeIntroScript::CNOVI_Bully::GivenTeddy(void) */

void __thiscall NScript::CQ_NewOakValeIntroScript::CNOVI_Bully::GivenTeddy(CNOVI_Bully *this)

{
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar1;
  undefined4 uStack_c;
  
  uStack_c = 1;
  (**(code **)(**(int **)(this + 4) + 0x1f8))();
  CCharString::CCharString((CCharString *)&stack0xfffffff8,"OBJECT_TEDDY_BEAR_UNGIVEABLE",-1);
  ppVar1 = (pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *)&stack0xfffffff8;
  (**(code **)(**(int **)(this + 4) + 500))();
  std::
  _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
            ((allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *)&uStack_c,extraout_EDX
             ,ppVar1);
  *(undefined1 *)(*(int *)(this + 0x14) + 0x70) = 1;
  *(undefined1 *)(*(int *)(this + 0x14) + 0x91) = 1;
  AddBadDeed(*(CQ_NewOakValeIntroScript **)(this + 0x14),3);
  return;
}


