/* Ghidra project FableTLC/Fable.exe; function entry 0x00DAED30; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.7245329992701657 <- ego_r]
   private: virtual void __thiscall NScript::CQ_NewOakValeIntroScript::CNOVI_Bully::Init(void) */

void __thiscall NScript::CQ_NewOakValeIntroScript::CNOVI_Bully::Init(CNOVI_Bully *this)

{
  CNOVI_Bully *pCVar1;
  int iVar2;
  int *piVar3;
  undefined4 uVar4;
  
  this[0x24] = (CNOVI_Bully)0x0;
  *(undefined4 *)(this + 0x20) = 0;
  *(undefined4 *)(this + 0x1c) = 4;
  this[0x26] = (CNOVI_Bully)0x0;
  *(undefined1 *)(*(int *)(this + 0x14) + 0x70) = 0;
  this[0x25] = (CNOVI_Bully)0x0;
  *(undefined4 *)(this + 0x28) = 10;
  pCVar1 = this + 8;
  (**(code **)(**(int **)(this + 4) + 0x810))(pCVar1,0);
  (**(code **)(**(int **)(this + 4) + 0x814))(pCVar1,0,0);
  (**(code **)(**(int **)(this + 4) + 0x838))(pCVar1,0);
  (**(code **)(**(int **)(this + 4) + 0x5a0))(pCVar1,0,0,0);
  iVar2 = **(int **)(this + 4);
  uVar4 = (**(code **)(iVar2 + 0x118))();
  (**(code **)(iVar2 + 0x95c))(pCVar1,uVar4);
  uVar4 = *(undefined4 *)(this + 0xc);
  piVar3 = *(int **)(this + 0x10);
  if (piVar3 != (int *)0x0) {
    *piVar3 = *piVar3 + 1;
  }
  (**(code **)(**(int **)(this + 4) + 0xd30))
            (&PTR__scalar_deleting_destructor__01238c8c,uVar4,piVar3,0);
  return;
}


