/* Ghidra project FableTLC/Fable.exe; function entry 0x00644DF8; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.9999999999999999 <- ego_r]
   public: void __thiscall NPlayerGui::CDrawQuestInfo::ChangeBarColour(long,class CRGBColour const
   &,class CRGBColour const &) */

void __thiscall
NPlayerGui::CDrawQuestInfo::ChangeBarColour
          (CDrawQuestInfo *this,long param_1,CRGBColour *param_2,CRGBColour *param_3)

{
  undefined4 *puVar1;
  int *piVar2;
  int iVar3;
  
  puVar1 = (undefined4 *)**(undefined4 **)(this + 0x58);
  while( true ) {
    if (puVar1 == *(undefined4 **)(this + 0x58)) {
      return;
    }
    piVar2 = (int *)puVar1[2];
    if ((piVar2 != (int *)0x0) && (piVar2[1] == param_1)) break;
    puVar1 = (undefined4 *)*puVar1;
  }
  iVar3 = (**(code **)(*piVar2 + 0xc))();
  if (iVar3 != 1) {
    return;
  }
  piVar2[10] = *(int *)param_2;
  piVar2[0xb] = *(int *)param_3;
  return;
}


