-- Retail helper 0x00F25840 (NScript::CQ_ArenaScript::InitialiseVariables)
-- Preserve initializer order and native offsets without inventing field names.
return function(set_string, write_u8, write_u32, write_nested_u8, invoke_native)
    invoke_native(15882624, 21231952)
    set_string(72, "ARENA_HECKLE_SMALL_LOOP")
    set_string(76, "ARENA_CHANT_LOOP")
    set_string(80, "ARENA_APPLAUSE_SMALL_LOOP")
    set_string(84, "ARENA_CHEER_CROWD")
    set_string(88, "ARENA_AWWW")
    set_string(92, "ARENA_HECKLE_SMALL_LOOP")
    set_string(96, "ARENA_CHANT_LOOP")
    set_string(100, "ARENA_APPLAUSE_MEDIUM_LOOP")
    set_string(104, "ARENA_CHEER_CROWD")
    set_string(108, "ARENA_AWWW")
    set_string(112, "ARENA_HECKLE_MEDIUM_LOOP")
    set_string(116, "ARENA_CHANT_LOOP")
    set_string(120, "ARENA_APPLAUSE_BIG_LOOP")
    set_string(124, "ARENA_CHEER_CROWD")
    set_string(128, "ARENA_AWWW")
    set_string(132, "ARENA_HECKLE_BIG_LOOP")
    set_string(136, "ARENA_CHANT_LOOP")
    set_string(140, "ARENA_APPLAUSE_BIG_LOOP")
    set_string(144, "ARENA_CHEER_CROWD")
    set_string(148, "ARENA_AWWW")
end
