/* Ghidra project FableTLC/Fable.exe; function entry 0x00DAC2C0; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.8386630707597903 <- ego_r]
   public: __thiscall CTriangleStripifier::CTriangleList::CTriangleList(void) */

CTriangleList * __thiscall CTriangleStripifier::CTriangleList::CTriangleList(CTriangleList *this)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  int in_EDX;
  undefined4 in_stack_00000004;
  CScriptThing *in_stack_00000008;
  
  puVar2 = ::operator_new(0x20);
  if (puVar2 == (undefined4 *)0x0) {
    puVar2 = (undefined4 *)0x0;
  }
  else {
    puVar2[1] = *(undefined4 *)(in_EDX + 0x40);
    *puVar2 = &PTR__vector_deleting_destructor__012c3224;
    CScriptThing::CScriptThing((CScriptThing *)(puVar2 + 2),in_stack_00000008);
    *puVar2 = &PTR__vector_deleting_destructor__012d8388;
    puVar2[5] = in_EDX;
    puVar2[6] = in_stack_00000004;
  }
  *(undefined4 **)this = puVar2;
  if (puVar2 != (undefined4 *)0x0) {
    puVar2 = ::operator_new(0xc);
    if (puVar2 != (undefined4 *)0x0) {
      uVar1 = *(undefined4 *)this;
      *puVar2 = 1;
      puVar2[1] = &LAB_00cdee00;
      puVar2[2] = uVar1;
      *(undefined4 **)(this + 4) = puVar2;
      return this;
    }
    *(undefined4 *)(this + 4) = 0;
    return this;
  }
  *(undefined4 *)(this + 4) = 0;
  return this;
}


