-- Lifted draft of retail entity script NOVI_Villager (Init 0x00DADF00, Main 0x00DADF80).
-- Generated by tools/script_recovery/lift_native_lua.py; every TODO(native) needs a human.
local MY_SCRIPT_NAME = "NOVI_Villager"

function Init(quest, me)
    quest:SetStateBool("HeroDidHitMe", false)
    quest:EntitySetAsDamageable(me, false)
    quest:EntitySetAsKillable(me, false, false)
    quest:EntitySetAsToAddToComboMultiplierWhenHit(me, false)
    local uVar3 = quest:GetHero()
    quest:EntitySetThingAsAllyOfThing(me, uVar3)
end

function Main(quest, me)
    local bVar5, fVar16, fVar3, iVar12, iVar8, native_arg_sequence_1, pCVar18, pCVar19, pCVar20, pCVar25, pCVar9, ppVar10, ppVar21, r1, r2, uVar11, uVar15, uVar22, uVar23, uVar4, uVar7
    local alive = true
    alive = quest:NewScriptFrame(me)
    if not alive then
        return
    end
    uVar4 = 0
    local cVar6 = extraout_AL_00
    repeat
        if cVar6 ~= 0 then
            return
        end
        -- TODO(native): bVar5 = C3DMeshInfo::HasPhysicsMesh((C3DMeshInfo *)appuStack_20);
        if bVar5 then
        end
        pCVar25 = "SCRIPT_NAME_HERO"
        uVar15 = uVar4 | 1
        cVar6 = me:MsgIsHitByHero()
        if not cVar6 then
            uVar15 = uVar4 | 3
            cVar6 = me:MsgIsHitByAnySpecialAbilityFromHero()
            if cVar6 then
                uVar15 = uVar4 | 7
                cVar6 = me:MsgIsHitByHeroSpecialAbility(0xe)
                if not cVar6 then return end  -- TODO(native): goto LAB_00dae0aa
            end
            bVar5 = false
        else
            -- LAB_00dae0aa: (native jump target)
            bVar5 = true
        end
        if (uVar15 & 4) ~= 0 then
            uVar15 = uVar15 & 0xfffffffb
        end
        if (uVar15 & 2) ~= 0 then
            uVar15 = uVar15 & 0xfffffffd
        end
        if (uVar15 & 1) ~= 0 then
            -- TODO(native): uStack_64 = uVar15 & 0xfffffffe;
        end
        if bVar5 then
            if not alive then return end  -- TODO(native): goto LAB_00daea49
            uVar7 = quest:GetHero()
            quest:EntitySetThingAsAllyOfThing(me, uVar7)
            uVar7 = quest:GetHero()
            quest:EntitySetThingAsAllyOfThing(uVar7, nil --[[missing]])
            -- TODO(native): AddBadDeed(*(CQ_NewOakValeIntroScript **)(this + 0x14),2);
            quest:SetStateBool("HeroDidHitMe", true)
            -- TODO(native): bVar5 = C3DMeshInfo::HasPhysicsMesh(aCStack_34);
            if bVar5 then
            end
            cVar6 = me:AcquireControl(4)
            while not cVar6 do
                alive = quest:NewScriptFrame(me)
                if not alive then return end  -- TODO(native): goto LAB_00daea49
                cVar6 = me:AcquireControl(4)
            end
            if not alive then return end  -- TODO(native): goto LAB_00daea49
            pCVar18 = ""
            quest:StartMovieSequence()
            quest:PauseAllNonScriptedEntities(true)
            iVar8 = quest:EntityGetSex(nil --[[missing]])
            uVar22 = SUB41(me,0)
            if iVar8 == 1 then
                if not alive then
                    quest:PauseAllNonScriptedEntities(false)
                    -- TODO(native): goto LAB_00daea49
                end
                -- TODO(native): uVar7 = CScriptGameResourceObjectScriptedThingBase::_GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ ((CScriptGameResourceObjectScriptedThingBase *)aCStack_34);
                fVar16 = quest:GetHealth(nil --[[missing]])
                fVar3 = 0.0
                if fVar3 < fVar16 then
                    bVar5 = false
                    pCVar20 = 0x1
                    pCVar19 = 0x0
                    pCVar18 = 0x1
                    pCVar9 = quest:GetHero()
                    r1 = me:Speak(pCVar9, "TEXT_QST_048_VILLAGER_ATTACKED_MALE", pCVar18, (pCVar19 ~= 0), (pCVar20 ~= 0), bVar5)
                    bVar5 = me:IsPerformingScriptTask()
                    if bVar5 then
                        repeat
                            alive = quest:NewScriptFrame(me)
                            if not alive then return end  -- TODO(native): goto LAB_00daea2a
                            bVar5 = me:IsPerformingScriptTask()
                        until not (bVar5)
                    end
                    if not alive then
                        quest:PauseAllNonScriptedEntities(false)
                        -- TODO(native): goto LAB_00daea49
                    end
                end
            else
                if not alive then
                    -- LAB_00daea2a: (native jump target)
                    quest:PauseAllNonScriptedEntities(false)
                    -- TODO(native): goto LAB_00daea49
                end
                -- TODO(native): uVar7 = CScriptGameResourceObjectScriptedThingBase::_GetScriptThing_CScriptGameResourceObjectScriptedThingBase__UBE_AVCScriptThing__XZ ((CScriptGameResourceObjectScriptedThingBase *)aCStack_34);
                fVar16 = quest:GetHealth(nil --[[missing]])
                fVar3 = 0.0
                if fVar3 < fVar16 then
                    bVar5 = false
                    pCVar20 = 0x1
                    pCVar19 = 0x0
                    pCVar18 = 0x1
                    pCVar9 = quest:GetHero()
                    r2 = me:Speak(pCVar9, "TEXT_QST_048_VILLAGER_ATTACKED_FEMALE", pCVar18, (pCVar19 ~= 0), (pCVar20 ~= 0), bVar5)
                    bVar5 = me:IsPerformingScriptTask()
                    if bVar5 then
                        repeat
                            alive = quest:NewScriptFrame(me)
                            if not alive then
                                quest:PauseAllNonScriptedEntities(false)
                                -- TODO(native): goto LAB_00daea49
                            end
                            bVar5 = me:IsPerformingScriptTask()
                        until not (bVar5)
                    end
                    if not alive then return end  -- TODO(native): goto LAB_00daea2a
                end
            end
            quest:PauseAllNonScriptedEntities(false)
        else
            cVar6 = me:IsTalkedToByHero()
            if cVar6 then
                if not alive then return end  -- TODO(native): goto LAB_00daea49
                iVar8 = quest:EntityGetSex(me)
                if iVar8 == 1 then
                    if alive then
                        -- LAB_00dae43d: (native jump target)
                        -- TODO(native): bVar5 = C3DMeshInfo::HasPhysicsMesh(aCStack_24);
                        if bVar5 then
                        end
                        cVar6 = me:AcquireControl(4)
                        while not cVar6 do
                            alive = quest:NewScriptFrame(me)
                            if not alive then return end  -- TODO(native): goto LAB_00daea44
                            cVar6 = me:AcquireControl(4)
                        end
                        if alive then
                            uVar7 = quest:GetHero()
                            quest:EntitySetFacingAngleTowardsThing(me, uVar7)
                            ppVar10 = quest:AddNewConversation(me, false, false)
                            uVar7 = quest:GetHero()
                            quest:AddPersonToConversation(ppVar10, uVar7)
                            ppVar21 = ppVar10
                            if not quest:GetStateBool("HeroDidHitMe") then
                                if alive then
                                    uVar7 = quest:GetHero()
                                    uVar23 = 0
                                    pCVar18 = "_MALE"
                                    uVar11 = CCharString__AppendData(pCVar18)
                                    quest:AddLineToConversation(ppVar10, uVar11, me, uVar7, (uVar23 ~= 0))
                                    -- TODO(native): paVar13 = (allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *) aCStack_54;
                                    -- TODO(native): goto LAB_00dae59d
                                end
                            else
                                if alive then
                                    uVar7 = quest:GetHero()
                                    uVar23 = 0
                                    pCVar18 = "_MALE"
                                    uVar11 = CCharString__AppendData(pCVar18)
                                    quest:AddLineToConversation(ppVar10, uVar11, me, uVar7, (uVar23 ~= 0))
                                    -- TODO(native): paVar13 = (allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *) aCStack_5c;
                                    -- LAB_00dae59d: (native jump target)
                                    cVar6 = quest:IsConversationActive(ppVar10)
                                    while cVar6 do
                                        alive = quest:NewScriptFrame(me)
                                        if not alive then return end  -- TODO(native): goto LAB_00daea44
                                        cVar6 = quest:IsConversationActive(ppVar10)
                                    end
                                    if alive then
                                        -- TODO(native): bVar5 = C3DMeshInfo::HasPhysicsMesh(aCStack_24);
                                        if bVar5 then
                                        end
                                        -- TODO(native): goto LAB_00dae98e
                                    end
                                end
                            end
                        end
                    end
                else
                    if alive then
                        -- TODO(native): goto LAB_00dae43d
                    end
                end
                -- LAB_00daea44: (native jump target)
                -- LAB_00daea49: (native jump target)
                return
            end
            if not alive then return end  -- TODO(native): goto LAB_00daea49
            iVar8 = quest:GetTimer(quest:GetStateInt("TalkIntermittentTimer"))
            native_arg_sequence_1 = false
            if iVar8 == 0 then
                native_arg_sequence_1 = true
            else
                native_arg_sequence_1 = false
            end
            if native_arg_sequence_1 then
                iVar8 = rand()
                if iVar8 % 100 == 0 then
                    native_arg_sequence_1 = true
                else
                    native_arg_sequence_1 = false
                end
            end
            if native_arg_sequence_1 then
                pCVar9 = quest:GetHero()
                bVar5 = quest:IsDistanceBetweenThingsUnder(me, pCVar9, 5.0)
                if bVar5 then
                    if not alive then return end  -- TODO(native): goto LAB_00daea49
                    quest:SetTimer(quest:GetStateInt("TalkIntermittentTimer"), 3)
                    uVar7 = quest:AddNewConversation(me, false, false)
                    uVar11 = quest:GetHero()
                    quest:AddPersonToConversation(uVar7, uVar11)
                    iVar12 = quest:GetStateInt("BadDeedsPerformed")
                    if (iVar12 == 0) and (0 < quest:GetStateInt("GoodDeedsPerformed")) then
                        if not alive then return end  -- TODO(native): goto LAB_00daea49
                        iVar8 = quest:EntityGetSex(me)
                        if iVar8 == 1 then
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xa0) - *(quest:GetStateInt("self_0x14") + 0x9c) >> 2)
                            iVar8 = *(quest:GetStateInt("self_0x14") + 0x9c)
                        else
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xd0) - *(quest:GetStateInt("self_0x14") + 0xcc) >> 2)
                            iVar8 = *(quest:GetStateInt("self_0x14") + 0xcc)
                        end
                    elseif (iVar12 < 1) or (quest:GetStateInt("GoodDeedsPerformed") ~= 0) then
                        if (iVar12 < 1) or (quest:GetStateInt("GoodDeedsPerformed") < 1) then
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar8 = quest:EntityGetSex(me)
                            if iVar8 == 1 then
                                if not alive then return end  -- TODO(native): goto LAB_00daea49
                                iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xc4) - *(quest:GetStateInt("self_0x14") + 0xc0) >> 2)
                                iVar8 = *(quest:GetStateInt("self_0x14") + 0xc0)
                            else
                                if not alive then return end  -- TODO(native): goto LAB_00daea49
                                iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xf4) - *(quest:GetStateInt("self_0x14") + 0xf0) >> 2)
                                iVar8 = *(quest:GetStateInt("self_0x14") + 0xf0)
                            end
                        else
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar8 = quest:EntityGetSex(me)
                            if iVar8 == 1 then
                                if not alive then return end  -- TODO(native): goto LAB_00daea49
                                iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xb8) - *(quest:GetStateInt("self_0x14") + 0xb4) >> 2)
                                iVar8 = *(quest:GetStateInt("self_0x14") + 0xb4)
                            else
                                if not alive then return end  -- TODO(native): goto LAB_00daea49
                                iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xe8) - *(quest:GetStateInt("self_0x14") + 0xe4) >> 2)
                                iVar8 = *(quest:GetStateInt("self_0x14") + 0xe4)
                            end
                        end
                    else
                        if not alive then return end  -- TODO(native): goto LAB_00daea49
                        iVar8 = quest:EntityGetSex(me)
                        if iVar8 == 1 then
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xac) - *(quest:GetStateInt("self_0x14") + 0xa8) >> 2)
                            iVar8 = *(quest:GetStateInt("self_0x14") + 0xa8)
                        else
                            if not alive then return end  -- TODO(native): goto LAB_00daea49
                            iVar12 = GetVillagerSpeechIndex (this,*(quest:GetStateInt("self_0x14") + 0xdc) - *(quest:GetStateInt("self_0x14") + 0xd8) >> 2)
                            iVar8 = *(quest:GetStateInt("self_0x14") + 0xd8)
                        end
                    end
                    -- TODO(native): CCharString::operator=(aCStack_6c,(CCharString *)(iVar8 + iVar12 * 4));
                    uVar11 = quest:GetHero()
                    quest:AddLineToConversation(uVar7, "_FEMALE", me, uVar11, aCStack_6c)
                end
            end
        end
        -- LAB_00dae98e: (native jump target)
        alive = quest:NewScriptFrame(me)
        cVar6 = extraout_AL_32
    until false
end

