-- Lifted draft of retail entity script NOVI_CreatedBeetle (Init None, Main 0x00DB80C0).
-- Generated by tools/script_recovery/lift_native_lua.py; every TODO(native) needs a human.
local MY_SCRIPT_NAME = "NOVI_CreatedBeetle"

function Init(quest, me)
end

function Main(quest, me)
    local iVar2, uVar1
    local alive = true
    alive = quest:NewScriptFrame(me)
    if alive then
        uVar1 = quest:RegisterTimer()
        quest:SetTimer(uVar1, 5)
        iVar2 = quest:GetTimer(uVar1)
        while iVar2 ~= 0 do
            alive = quest:NewScriptFrame(me)
            if not alive then
                quest:DeregisterTimer(uVar1)
                return
            end
            iVar2 = quest:GetTimer(uVar1)
        end
        if alive then
            quest:RemoveThing(me, true, true)
        end
        quest:DeregisterTimer(uVar1)
    end
end

