"""Coverage of EVERY retail script (the 161-entry quest registry) by the Lua conversion.

    python -m tools.script_recovery.script_coverage            # writes docs/scripts/SCRIPT_COVERAGE.md
    python -m tools.script_recovery.script_coverage --json     # the same rows as JSON on stdout

Status per script:
  played     converted, and a runner playthrough completed it in-game (PLAYED below, with its checkpoint)
  converted  in a converter unit (tools/script_recovery/script_units.py) with a generated draft
  todo       not converted yet
  test       a developer / debug script (alextest, TestNewNav1, Global_ToggleTimeDisplay ...): not shipped content

Scope note: the registry is the NScript layer (quests, village scripts, expression / global / personal / master
scripts, cutscene hosts); each script's entity behaviour scripts are its entity bindings and convert with it.
Engine gameplay systems -- real estate (CTCBuyableHouse), shops / economy (CTCShop, CTCShopKeeper), the tavern
games (CTCTavernGameCardBlackjack / CoinGolf / ShoveHaPenny), the Fireheart minigame, creature AI (CBrain*) --
are engine C++, reconstructed by the byte-exact rebuild, not scripts.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tools.script_recovery.script_units import UNITS  # noqa: E402

CATALOG = ROOT / 'refs/script_recovery/native_catalog.json'
OUT = ROOT / 'docs/scripts/SCRIPT_COVERAGE.md'

# In-game completions on the converted scripts (runner or recorded playthrough) -> the checkpoint / evidence.
# Keep this list to what a run actually showed; see the journals under docs/journal/2026-09/.
PLAYED = {
    'Q_NewOakValeIntro': 'childhood played clean (New Oakvale sidecar v4, 2026-09-16)',
    'Q_GuildTraining': 'guild training completed end-to-end (v6, 2026-09-21)',
    'Q_WaspBoss': 'adult chain runner (2026-09-25)',
    'QS_GuardianSisterInfo': 'adult chain runner (2026-09-25)',
    'Q_OrchardFarmRaidGood': 'adult chain runner, Good route (2026-09-25)',
    'Q_TraderEscort': 'adult_trader_escort_completed_v15_2026-09-25',
    'QS_GuardianSisterInfo2_SisterInBanditCamp': 'adult_maze2_completed_2026-09-25',
    'Q_BanditCamp': 'adult_bandit_camp_completed_2026-09-26 (bc15, zero manual input)',
    'Q_BanditCampBossBattle': 'adult_bandit_camp_completed_2026-09-26',
    'QS_GuardianTrophyDealerInfo': 'adult_trophy_dealer_info_completed_2026-09-26',
    'V_TrophyDealer': 'adult_trophy_dealer_completed_2026-09-26 (Singing Stones assisted)',
    'Q_WhiteBalverineKnotholeGlade': 'adult_white_balverine_completed_2026-09-26',
    'Q_WhiteBalverineWW': 'adult_white_balverine_completed_2026-09-26',
    'Gameflow': 'drives every stage of the chain above (stages 0 -> 875)',
}


# developer scripts registered under other kinds (the catalog's `test` kind misses these): not shipped content
DEV = {'alextest', 'PersonalScript_alextest', 'DanyalTestScripts', 'PersonalScript_Aardvark', 'joss_test_scripts',
       'guy_script', 'bandit_level_cutscene', 'Empty', 'PersonalScript_Empty', 'Global_DebugCycleThroughSpeech',
       'Global_ToggleTimeDisplay'}


def rows():
    scripts = json.loads(CATALOG.read_text(encoding='utf-8'))['scripts']
    unit_of = {s: name for name, u in UNITS.items() for s in u['scripts']}
    out = []
    for s in scripts:
        name, kind = s['name'], s['kind']
        if kind == 'test' or name in DEV or 'test' in name.lower():
            status = 'test'
        elif name in PLAYED:
            status = 'played'
        elif name in unit_of:
            status = 'converted'
        else:
            status = 'todo'
        out.append({'name': name, 'kind': kind, 'status': status, 'unit': unit_of.get(name, ''),
                    'evidence': PLAYED.get(name, ''), 'allocator': s.get('allocatorAddress') or ''})
    return out


def markdown(data):
    shipped = [r for r in data if r['status'] != 'test']
    count = {k: sum(1 for r in shipped if r['status'] == k) for k in ('played', 'converted', 'todo')}
    lines = ['# Script coverage', '',
             'Generated by `python -m tools.script_recovery.script_coverage`; do not edit by hand.', '',
             f"**{len(shipped)} shipped scripts** (plus {len(data) - len(shipped)} developer test scripts): "
             f"{count['played']} played in-game on the converted Lua, {count['converted']} converted but not "
             f"played, {count['todo']} not converted.", '',
             'Entity behaviour scripts convert with the script that binds them. Engine gameplay systems (real estate, '
             'shops / economy, tavern games, the Fireheart minigame, creature AI) are engine C++ for the byte-exact '
             'rebuild, not scripts.', '']
    kinds = sorted({r['kind'] for r in shipped}, key=lambda k: -sum(1 for r in shipped if r['kind'] == k))
    for kind in kinds:
        group = [r for r in shipped if r['kind'] == kind]
        done = sum(1 for r in group if r['status'] != 'todo')
        lines += [f'## {kind} ({done}/{len(group)} converted)', '', '| script | status | unit | evidence |', '|---|---|---|---|']
        order = {'played': 0, 'converted': 1, 'todo': 2}
        for r in sorted(group, key=lambda r: (order[r['status']], r['name'])):
            lines.append(f"| `{r['name']}` | {r['status']} | {r['unit']} | {r['evidence']} |")
        lines.append('')
    return '\n'.join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--json', action='store_true')
    a = ap.parse_args(argv)
    data = rows()
    if a.json:
        print(json.dumps(data, indent=1))
        return
    OUT.write_text(markdown(data) + '\n', encoding='utf-8')
    shipped = [r for r in data if r['status'] != 'test']
    print(f'{OUT.relative_to(ROOT)}: {len(shipped)} shipped scripts, '
          + ', '.join(f"{k} {sum(1 for r in shipped if r['status'] == k)}" for k in ('played', 'converted', 'todo')))


if __name__ == '__main__':
    main()
