/* Ghidra project FableTLC/Fable.exe; function entry 0x00DAAC00; generated by DecompFuncsToDirectory.java. */


/* [bsim sim=0.9616046519250714 <- ego_r]
   public: __thiscall NScript::CQ_NewOakValeIntroScript::CQ_NewOakValeIntroScript(class
   CScriptDataBase *,class CGameScriptInterfaceBase &) */

CQ_NewOakValeIntroScript * __thiscall
NScript::CQ_NewOakValeIntroScript::CQ_NewOakValeIntroScript
          (CQ_NewOakValeIntroScript *this,CScriptDataBase *param_1,CGameScriptInterfaceBase *param_2
          )

{
  undefined4 uVar1;
  
  CHeroMorphDef::CHeroMorphDef((CHeroMorphDef *)this);
  *(CGameScriptInterfaceBase **)(this + 0x40) = param_2;
  *(CScriptDataBase **)(this + 0x44) = param_1;
  *(undefined ***)this = &PTR__vector_deleting_destructor__012d7a28;
  *(undefined4 *)(this + 0x9c) = 0;
  *(undefined4 *)(this + 0xa0) = 0;
  *(undefined4 *)(this + 0xa4) = 0;
  *(undefined4 *)(this + 0xa8) = 0;
  *(undefined4 *)(this + 0xac) = 0;
  *(undefined4 *)(this + 0xb0) = 0;
  *(undefined4 *)(this + 0xb4) = 0;
  *(undefined4 *)(this + 0xb8) = 0;
  *(undefined4 *)(this + 0xbc) = 0;
  *(undefined4 *)(this + 0xc0) = 0;
  *(undefined4 *)(this + 0xc4) = 0;
  *(undefined4 *)(this + 200) = 0;
  *(undefined4 *)(this + 0xcc) = 0;
  *(undefined4 *)(this + 0xd0) = 0;
  *(undefined4 *)(this + 0xd4) = 0;
  *(undefined4 *)(this + 0xd8) = 0;
  *(undefined4 *)(this + 0xdc) = 0;
  *(undefined4 *)(this + 0xe0) = 0;
  *(undefined4 *)(this + 0xe4) = 0;
  *(undefined4 *)(this + 0xe8) = 0;
  *(undefined4 *)(this + 0xec) = 0;
  *(undefined4 *)(this + 0xf0) = 0;
  *(undefined4 *)(this + 0xf4) = 0;
  *(undefined4 *)(this + 0xf8) = 0;
  uVar1 = (**(code **)(*DAT_0143e8f8 + 0x15c))();
  *(undefined4 *)(this + 0x104) = uVar1;
  uVar1 = (**(code **)(*DAT_0143e8f8 + 0x15c))();
  *(undefined4 *)(this + 0x108) = uVar1;
  return this;
}


