/* Ghidra project FableTLC/Fable.exe; function entry 0x00DBEFC0; generated by DecompFuncsToDirectory.java. */


/* autoname-t5 [high]: Vector_deleting_destructor, calls DeleteAllParticles; seventh emitter
   destructor */

void __fastcall CParticleEmitter_Dtor_7(CParticleEmitter *param_1)

{
  allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *paVar1;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_00;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_01;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_02;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_03;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_04;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_05;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_06;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_07;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_08;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_09;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_10;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_11;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_12;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_13;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *ppVar2;
  pair<EHeroMorphType,CParticleMorphs::CEntry> *extraout_EDX_14;
  CIEngine *unaff_EBX;
  allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> *paVar3;
  pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> *ppVar4;
  
  (**(code **)(*DAT_0143e8f8 + 0x160))(*(undefined4 *)(param_1 + 0x108));
  ppVar4 = *(pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry> **)(param_1 + 0x104);
  (**(code **)(*DAT_0143e8f8 + 0x160))();
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xf4);
  ppVar2 = extraout_EDX;
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xf0);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_00;
  }
  if (*(void **)(param_1 + 0xf0) != (void *)0x0) {
    free(*(void **)(param_1 + 0xf0));
    ppVar2 = extraout_EDX_01;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xe8);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xe4);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_02;
  }
  if (*(void **)(param_1 + 0xe4) != (void *)0x0) {
    free(*(void **)(param_1 + 0xe4));
    ppVar2 = extraout_EDX_03;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xdc);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xd8);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_04;
  }
  if (*(void **)(param_1 + 0xd8) != (void *)0x0) {
    free(*(void **)(param_1 + 0xd8));
    ppVar2 = extraout_EDX_05;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xd0);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xcc);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_06;
  }
  if (*(void **)(param_1 + 0xcc) != (void *)0x0) {
    free(*(void **)(param_1 + 0xcc));
    ppVar2 = extraout_EDX_07;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xc4);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xc0);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_08;
  }
  if (*(void **)(param_1 + 0xc0) != (void *)0x0) {
    free(*(void **)(param_1 + 0xc0));
    ppVar2 = extraout_EDX_09;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xb8);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xb4);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_10;
  }
  if (*(void **)(param_1 + 0xb4) != (void *)0x0) {
    free(*(void **)(param_1 + 0xb4));
    ppVar2 = extraout_EDX_11;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xac);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xa8);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_12;
  }
  if (*(void **)(param_1 + 0xa8) != (void *)0x0) {
    free(*(void **)(param_1 + 0xa8));
    ppVar2 = extraout_EDX_13;
  }
  paVar1 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0xa0);
  for (paVar3 = *(allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_> **)(param_1 + 0x9c);
      paVar3 != paVar1; paVar3 = paVar3 + 4) {
    std::
    _Cons_val<std::allocator<std::pair<EHeroMorphType,CParticleMorphs::CEntry>_>,std::pair<EHeroMorphType,CParticleMorphs::CEntry>,std::pair<enum_EHeroMorphType,class_CParticleMorphs::CEntry>_const&>
              (paVar3,ppVar2,ppVar4);
    ppVar2 = extraout_EDX_14;
  }
  if (*(void **)(param_1 + 0x9c) != (void *)0x0) {
    free(*(void **)(param_1 + 0x9c));
  }
  NParticleEngine::CParticleEmitter::DeleteAllParticles(param_1,unaff_EBX);
  return;
}


