#ifndef FABLE_ENGINE_CCLOCKDEF_H
#define FABLE_ENGINE_CCLOCKDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CClockDef = 0x3c.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 1 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CClockDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char Sound[0x10];                               // +0x28 map<CCharString,long,std::less<CCharString>,std::allocator<std::pair<CCharString_const_,long>_>_>
    unsigned char HandType[0x4];                             // +0x38 EClockHandType
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CClockDef) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CClockDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CClockDef, Sound) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CClockDef, HandType) == 0x38);

#endif // FABLE_ENGINE_CCLOCKDEF_H
