#ifndef FABLE_ENGINE_CCOMBATABILITYBLOCKUNARMEDATTACKDEF_H
#define FABLE_ENGINE_CCOMBATABILITYBLOCKUNARMEDATTACKDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CCombatAbilityBlockUnarmedAttackDef = 0x5c.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CCombatAbilityBlockUnarmedAttackDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x24];                           // +0x04
    long          m_member;                                  // +0x28 retail-only CMemberDef (CCombatAbilityBlockUnarmedAttackDef_Copy_00463bdb.cpp)
    unsigned char _pad_0x2c[0x30];                           // +0x2c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CCombatAbilityBlockUnarmedAttackDef) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CCombatAbilityBlockUnarmedAttackDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CCombatAbilityBlockUnarmedAttackDef, m_member) == 0x28);

#endif // FABLE_ENGINE_CCOMBATABILITYBLOCKUNARMEDATTACKDEF_H
