#ifndef FABLE_ENGINE_CCOMBATDIALOGUEDEF_H
#define FABLE_ENGINE_CCOMBATDIALOGUEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CCombatDialogueDef = 0x90.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CCombatDialogueDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    float         MinTimeBetweenSpeech;                      // +0x40
    float         MinTimeBetweenSpeechRepeat;                // +0x44
    float         MinDelayAfterBattleCry;                    // +0x48
    long          EnemySighted;                              // +0x4c
    long          RunForCover;                               // +0x50
    long          Hiding;                                    // +0x54
    long          Ambushing;                                 // +0x58
    long          WillSeenUsed;                              // +0x5c
    long          Threat;                                    // +0x60
    long          Encourage;                                 // +0x64
    long          FoeKnockedDownByColleague;                 // +0x68
    long          MenLosing;                                 // +0x6c
    long          EnemyKnockedDown;                          // +0x70
    long          RangedCombatAiming;                        // +0x74
    long          RangedCombatAimingBlocked;                 // +0x78
    long          Injured;                                   // +0x7c
    long          ReactionToDecapitation;                    // +0x80
    long          ColleagueInjured;                          // +0x84
    long          Scared;                                    // +0x88
    long          Flee;                                      // +0x8c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CCombatDialogueDef) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, MinTimeBetweenSpeech) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, MinTimeBetweenSpeechRepeat) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, MinDelayAfterBattleCry) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, EnemySighted) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, RunForCover) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Hiding) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Ambushing) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, WillSeenUsed) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Threat) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Encourage) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, FoeKnockedDownByColleague) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, MenLosing) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, EnemyKnockedDown) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, RangedCombatAiming) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, RangedCombatAimingBlocked) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Injured) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, ReactionToDecapitation) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, ColleagueInjured) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Scared) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CCombatDialogueDef, Flee) == 0x8c);

#endif // FABLE_ENGINE_CCOMBATDIALOGUEDEF_H
