#ifndef FABLE_ENGINE_CCREATUREACTIONHEROJUMP_H
#define FABLE_ENGINE_CCREATUREACTIONHEROJUMP_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CCreatureActionHeroJump = 0x12c.
// Retail evidence: 3 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 1 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CCreatureActionHeroJump {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    int           m04;                                       // +0x04 retail-only (CCreatureActionHeroJump_FrameUpdateCCreatureActionHeroJumpUAEXXZ_0085bad0.cpp)
    int           m08;                                       // +0x08 retail-only (CCreatureActionHeroJump_FrameUpdateCCreatureActionHeroJumpUAEXXZ_0085bad0.cpp)
    int           m0c;                                       // +0x0c retail-only (CCreatureActionHeroJump_FrameUpdateCCreatureActionHeroJumpUAEXXZ_0085bad0.cpp)
    int           f10;                                       // +0x10 retail-only (CCreatureActionHeroJump_IsPreventingNormalMovement_0085b8a0.cpp)
    int           f1c;                                       // +0x14 retail-only (CCreatureActionHeroJump_IsPreventingNormalMovement_0085b8a0.cpp)
    int           m18;                                       // +0x18 retail-only (CCreatureActionHeroJump_FrameUpdateCCreatureActionHeroJumpUAEXXZ_0085bad0.cpp)
    int           m1c;                                       // +0x1c retail-only (CCreatureActionHeroJump_FrameUpdateCCreatureActionHeroJumpUAEXXZ_0085bad0.cpp)
    unsigned char _pad_0x20[0x10c];                          // +0x20
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CCreatureActionHeroJump) == 0x12c);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, m04) == 0x4);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, m08) == 0x8);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, m0c) == 0xc);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, f10) == 0x10);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, f1c) == 0x14);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, m18) == 0x18);
FABLE_STATIC_ASSERT(offsetof(CCreatureActionHeroJump, m1c) == 0x1c);

#endif // FABLE_ENGINE_CCREATUREACTIONHEROJUMP_H
