#ifndef FABLE_ENGINE_CEXPRESSIONDEF_H
#define FABLE_ENGINE_CEXPRESSIONDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CExpressionDef = 0x94.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CExpressionDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    long          Animation_TablePos;                        // +0x40 CDefString::TablePos
    long          AnimationInto_TablePos;                    // +0x44 CDefString::TablePos
    long          AnimationLoop_TablePos;                    // +0x48 CDefString::TablePos
    long          AnimationOutOf_TablePos;                   // +0x4c CDefString::TablePos
    long          AnimationToOther_TablePos;                 // +0x50 CDefString::TablePos
    long          AnimationToOtherInto_TablePos;             // +0x54 CDefString::TablePos
    long          AnimationToOtherLoop_TablePos;             // +0x58 CDefString::TablePos
    long          AnimationToOtherOutOf_TablePos;            // +0x5c CDefString::TablePos
    float         SpriteDuration;                            // +0x60
    long          SpriteGraphic;                             // +0x64
    long          SpriteOverrideText_TablePos;               // +0x68 CDefString::TablePos
    long          SoundCriteria_TablePos;                    // +0x6c CDefString::TablePos
    long          LoopSoundCriteria_TablePos;                // +0x70 CDefString::TablePos
    long          DummyObject_Val;                           // +0x74 CDefIndex::Val
    unsigned char GameEventType[0x4];                        // +0x78 EGameEventType
    long          ScriptName_TablePos;                       // +0x7c CDefString::TablePos
    bool          ScriptLoadResources;                       // +0x80
    bool          DeactivateScriptAtEnd;                     // +0x81
    bool          PerformAfterScript;                        // +0x82
    unsigned char _pad_0x83[0x1];                            // +0x83
    unsigned char OpinionDeedType[0x4];                      // +0x84 EOpinionDeedType
    bool          Extendable;                                // +0x88
    bool          SheatheWeapons;                            // +0x89
    bool          ReplaceHeldItemWhenDone;                   // +0x8a
    unsigned char _pad_0x8b[0x1];                            // +0x8b
    unsigned long TextTag;                                   // +0x8c
    unsigned char ExpressionType[0x4];                       // +0x90 EExpressionInventoryType
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CExpressionDef) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, Animation_TablePos) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationInto_TablePos) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationLoop_TablePos) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationOutOf_TablePos) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationToOther_TablePos) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationToOtherInto_TablePos) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationToOtherLoop_TablePos) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, AnimationToOtherOutOf_TablePos) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, SpriteDuration) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, SpriteGraphic) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, SpriteOverrideText_TablePos) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, SoundCriteria_TablePos) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, LoopSoundCriteria_TablePos) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, DummyObject_Val) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, GameEventType) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, ScriptName_TablePos) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, ScriptLoadResources) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, DeactivateScriptAtEnd) == 0x81);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, PerformAfterScript) == 0x82);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, OpinionDeedType) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, Extendable) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, SheatheWeapons) == 0x89);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, ReplaceHeldItemWhenDone) == 0x8a);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, TextTag) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CExpressionDef, ExpressionType) == 0x90);

#endif // FABLE_ENGINE_CEXPRESSIONDEF_H
