#ifndef FABLE_ENGINE_CGLOBALDEF_H
#define FABLE_ENGINE_CGLOBALDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CGlobalDef = 0x160.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CGlobalDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    long          ControlSchemePC;                           // +0x40
    long          ControlSchemePCAggressive;                 // +0x44
    long          ControlSchemeXBOX;                         // +0x48
    long          ControlSchemeXBOXAggressive;               // +0x4c
    long          PhysicsTexture;                            // +0x50
    long          InvalidThemeStandin;                       // +0x54
    long          DefaultEngineThemeDef;                     // +0x58
    float         StaticMapGenerationEstimatedMaxCameraHeightAboveLandscape; // +0x5c
    long          GraphicWeaponTrail;                        // +0x60
    long          GraphicWeaponTrail2;                       // +0x64
    long          GraphicWeaponTrailArrow;                   // +0x68
    long          WeaponTrailAlpha;                          // +0x6c
    float         WeaponTrailAlphaFadeOffTime;               // +0x70
    long          WeaponTrailArrowAlpha;                     // +0x74
    float         WeaponTrailArrowAlphaFadeOffTime;          // +0x78
    long          WeaponTrialNumFramesToFadeOut;             // +0x7c
    long          HealthPickupValue;                         // +0x80
    long          RespawnDelay;                              // +0x84
    long          ScrabbleAngle;                             // +0x88
    long          SlideAngle;                                // +0x8c
    long          MaxFollowers;                              // +0x90
    unsigned char PickupGoldSoundCriteria[0x4];              // +0x94 CCharString
    unsigned char PickupItemSoundCriteria[0x4];              // +0x98 CCharString
    unsigned char OnClickSoundCriteria[0x4];                 // +0x9c CCharString
    long          EditorSpangleCursor;                       // +0xa0
    long          EditorCircleSprite;                        // +0xa4
    long          EditorSecondaryCircleSprite;               // +0xa8
    long          TestSpeech;                                // +0xac
    unsigned char MimeSpeechIndex[0x4];                      // +0xb0 CCharString
    long          AdultSleepTimeStart;                       // +0xb4
    long          AdultSleepTimeEnd;                         // +0xb8
    long          ChildSleepTimeStart;                       // +0xbc
    long          ChildSleepTimeEnd;                         // +0xc0
    long          ElderlySleepTimeStart;                     // +0xc4
    long          ElderlySleepTimeEnd;                       // +0xc8
    float         CreatureGeneratorRegenDelaySeconds;        // +0xcc
    long          Music;                                     // +0xd0
    float         AgeIncreasePerLevelUp;                     // +0xd4
    long          E3BodgeFireflyGraphic;                     // +0xd8
    unsigned char SwitchGraphic[0xe];                        // +0xdc CEngineGraphic
    unsigned char TrackGraphic[0xe];                         // +0xea CEngineGraphic
    unsigned char ConversationCameras[0x10];                 // +0xf8 map<long,CCharString,std::less<long>,std::allocator<std::pair<long_const_,CCharString>_>_>
    unsigned char PermittedAINarrators[0x10];                // +0x108 vector<CCharString,std::allocator<CCharString>_>
    unsigned char DialogueLayers[0x10];                      // +0x118 vector<NSpeechGainManager::CDialogueLayerDef,std::allocator<NSpeechGainManager::CDialogueLayerDef>_>
    long          OpinionDebugIndicatorIcon;                 // +0x128
    long          WifeLoveIndicatorIcon;                     // +0x12c
    long          WifeEngagedIndicatorIcon;                  // +0x130
    long          WifeMarriedIndicatorIcon;                  // +0x134
    long          ExpressionIndicatorIcon;                   // +0x138
    long          FollowerIndicatorIcon;                     // +0x13c
    float         EmoteIconDrawDistance;                     // +0x140
    float         AngleToBeConsideredVertical;               // +0x144
    float         SoundGainLowerValueWhenInsideOutside;      // +0x148
    long          TeleportOutParticleEffect;                 // +0x14c
    float         TeleportFadeOutTimeInSeconds;              // +0x150
    long          TeleportInParticleEffect;                  // +0x154
    float         TeleportFadeInTimeInSeconds;               // +0x158
    float         DamageForMaximumBlood;                     // +0x15c
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CGlobalDef) == 0x160);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ControlSchemePC) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ControlSchemePCAggressive) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ControlSchemeXBOX) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ControlSchemeXBOXAggressive) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, PhysicsTexture) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, InvalidThemeStandin) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, DefaultEngineThemeDef) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, StaticMapGenerationEstimatedMaxCameraHeightAboveLandscape) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, GraphicWeaponTrail) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, GraphicWeaponTrail2) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, GraphicWeaponTrailArrow) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WeaponTrailAlpha) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WeaponTrailAlphaFadeOffTime) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WeaponTrailArrowAlpha) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WeaponTrailArrowAlphaFadeOffTime) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WeaponTrialNumFramesToFadeOut) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, HealthPickupValue) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, RespawnDelay) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ScrabbleAngle) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, SlideAngle) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, MaxFollowers) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, PickupGoldSoundCriteria) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, PickupItemSoundCriteria) == 0x98);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, OnClickSoundCriteria) == 0x9c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, EditorSpangleCursor) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, EditorCircleSprite) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, EditorSecondaryCircleSprite) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TestSpeech) == 0xac);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, MimeSpeechIndex) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, AdultSleepTimeStart) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, AdultSleepTimeEnd) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ChildSleepTimeStart) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ChildSleepTimeEnd) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ElderlySleepTimeStart) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ElderlySleepTimeEnd) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, CreatureGeneratorRegenDelaySeconds) == 0xcc);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, Music) == 0xd0);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, AgeIncreasePerLevelUp) == 0xd4);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, E3BodgeFireflyGraphic) == 0xd8);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, SwitchGraphic) == 0xdc);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TrackGraphic) == 0xea);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ConversationCameras) == 0xf8);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, PermittedAINarrators) == 0x108);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, DialogueLayers) == 0x118);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, OpinionDebugIndicatorIcon) == 0x128);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WifeLoveIndicatorIcon) == 0x12c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WifeEngagedIndicatorIcon) == 0x130);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, WifeMarriedIndicatorIcon) == 0x134);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, ExpressionIndicatorIcon) == 0x138);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, FollowerIndicatorIcon) == 0x13c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, EmoteIconDrawDistance) == 0x140);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, AngleToBeConsideredVertical) == 0x144);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, SoundGainLowerValueWhenInsideOutside) == 0x148);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TeleportOutParticleEffect) == 0x14c);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TeleportFadeOutTimeInSeconds) == 0x150);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TeleportInParticleEffect) == 0x154);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, TeleportFadeInTimeInSeconds) == 0x158);
FABLE_STATIC_ASSERT(offsetof(CGlobalDef, DamageForMaximumBlood) == 0x15c);

#endif // FABLE_ENGINE_CGLOBALDEF_H
