#ifndef FABLE_ENGINE_CJACKOFBLADESBATTLEDEF_H
#define FABLE_ENGINE_CJACKOFBLADESBATTLEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CJackOfBladesBattleDef = 0x84.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CJackOfBladesBattleDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    float         IdealShootDistance;                        // +0x40
    long          NumGetHitsBeforeRush;                      // +0x44
    float         TimeBetweenShots;                          // +0x48
    float         ScreamInAirTime;                           // +0x4c
    float         TimeBetweenPillars;                        // +0x50
    float         BattleFloatHeight;                         // +0x54
    float         BattleScale;                               // +0x58
    float         ScaleUpTime;                               // +0x5c
    float         ScaleDownTime;                             // +0x60
    float         DeathScreamTime;                           // +0x64
    float         DeathHeight;                               // +0x68
    float         BurnDamage;                                // +0x6c
    float         FlashDuration;                             // +0x70
    float         FlashBuildUpTime;                          // +0x74
    float         RushTriggerDistance;                       // +0x78
    float         RushToDistance;                            // +0x7c
    float         RushAwayDistance;                          // +0x80
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CJackOfBladesBattleDef) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, IdealShootDistance) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, NumGetHitsBeforeRush) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, TimeBetweenShots) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, ScreamInAirTime) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, TimeBetweenPillars) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, BattleFloatHeight) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, BattleScale) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, ScaleUpTime) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, ScaleDownTime) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, DeathScreamTime) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, DeathHeight) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, BurnDamage) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, FlashDuration) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, FlashBuildUpTime) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, RushTriggerDistance) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, RushToDistance) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CJackOfBladesBattleDef, RushAwayDistance) == 0x80);

#endif // FABLE_ENGINE_CJACKOFBLADESBATTLEDEF_H
