#ifndef FABLE_ENGINE_COPINIONDEEDREACTIONDEF_H
#define FABLE_ENGINE_COPINIONDEEDREACTIONDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof COpinionDeedReactionDef = 0x58.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct COpinionDeedReactionDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    unsigned char Attitudes[0x10];                           // +0x40 vector<EOpinionAttitudeType,std::allocator<EOpinionAttitudeType>_>
    unsigned char Animation[0x4];                            // +0x50 CDefString
    unsigned long DialogueTag;                               // +0x54
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(COpinionDeedReactionDef) == 0x58);
FABLE_STATIC_ASSERT(offsetof(COpinionDeedReactionDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(COpinionDeedReactionDef, Attitudes) == 0x40);
FABLE_STATIC_ASSERT(offsetof(COpinionDeedReactionDef, Animation) == 0x50);
FABLE_STATIC_ASSERT(offsetof(COpinionDeedReactionDef, DialogueTag) == 0x54);

#endif // FABLE_ENGINE_COPINIONDEEDREACTIONDEF_H
