#ifndef FABLE_ENGINE_CSOUNDTHEMEDEF_H
#define FABLE_ENGINE_CSOUNDTHEMEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CSoundThemeDef = 0x6c.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CSoundThemeDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    unsigned char EditColour[0x4];                           // +0x40 CRGBColour
    long          AtmosIndex;                                // +0x44
    long          MusicSet;                                  // +0x48
    float         Gain;                                      // +0x4c
    float         Range;                                     // +0x50
    float         Granularity;                               // +0x54
    unsigned char AtmosGroupMap[0x10];                       // +0x58 multimap<CCharString,long,std::less<CCharString>,std::allocator<std::pair<CCharString_const_,long>_>_>
    bool          PlayOnlyWhenInside;                        // +0x68
    bool          PlayQuietlyWhenInside;                     // +0x69
    bool          PlayOnlyWhenOutside;                       // +0x6a
    bool          PlayQuietlyWhenOutside;                    // +0x6b
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CSoundThemeDef) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, EditColour) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, AtmosIndex) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, MusicSet) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, Gain) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, Range) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, Granularity) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, AtmosGroupMap) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, PlayOnlyWhenInside) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, PlayQuietlyWhenInside) == 0x69);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, PlayOnlyWhenOutside) == 0x6a);
FABLE_STATIC_ASSERT(offsetof(CSoundThemeDef, PlayQuietlyWhenOutside) == 0x6b);

#endif // FABLE_ENGINE_CSOUNDTHEMEDEF_H
