#ifndef FABLE_ENGINE_CSPECIALABILITIESTHUNDERLIGHTNINGSTORMDEF_H
#define FABLE_ENGINE_CSPECIALABILITIESTHUNDERLIGHTNINGSTORMDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CSpecialAbilitiesThunderLightningStormDef = 0x6c.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CSpecialAbilitiesThunderLightningStormDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    long          NumBeams;                                  // +0x40
    float         StartRadius;                               // +0x44
    float         EndRadius;                                 // +0x48
    float         SkyBeamStartTime;                          // +0x4c
    float         MainBeamsStartTime;                        // +0x50
    float         BeamRotationStartSpeed;                    // +0x54
    float         BeamRotationEndSpeed;                      // +0x58
    float         TotalLifetime;                             // +0x5c
    float         Damage;                                    // +0x60
    unsigned char InitSound[0x4];                            // +0x64 CDefString
    unsigned char LoopingSound[0x4];                         // +0x68 CDefString
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CSpecialAbilitiesThunderLightningStormDef) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, NumBeams) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, StartRadius) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, EndRadius) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, SkyBeamStartTime) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, MainBeamsStartTime) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, BeamRotationStartSpeed) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, BeamRotationEndSpeed) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, TotalLifetime) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, Damage) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, InitSound) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesThunderLightningStormDef, LoopingSound) == 0x68);

#endif // FABLE_ENGINE_CSPECIALABILITIESTHUNDERLIGHTNINGSTORMDEF_H
