#ifndef FABLE_ENGINE_CSPECIALABILITIESMULTISTRIKEDEF_H
#define FABLE_ENGINE_CSPECIALABILITIESMULTISTRIKEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CSpecialAbilitiesMultiStrikeDef = 0xb4.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CSpecialAbilitiesMultiStrikeDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    unsigned char Sounds[0x10];                              // +0x40 CDefString[4]
    unsigned char Animations[0x10];                          // +0x50 CDefString[4]
    float         HighlightWidth;                            // +0x60
    unsigned char HighlightColor[0x10];                      // +0x64 vector<long,std::allocator<long>_>
    unsigned char DelayTimeSecs[0x10];                       // +0x74 vector<float,std::allocator<float>_>
    unsigned char NumHits[0x10];                             // +0x84 vector<long,std::allocator<long>_>
    unsigned char PerHitDamagerMultiplier[0x10];             // +0x94 vector<float,std::allocator<float>_>
    unsigned char AttachmentPoint[0x10];                     // +0xa4 vector<CCharString,std::allocator<CCharString>_>
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CSpecialAbilitiesMultiStrikeDef) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, Sounds) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, Animations) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, HighlightWidth) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, HighlightColor) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, DelayTimeSecs) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, NumHits) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, PerHitDamagerMultiplier) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CSpecialAbilitiesMultiStrikeDef, AttachmentPoint) == 0xa4);

#endif // FABLE_ENGINE_CSPECIALABILITIESMULTISTRIKEDEF_H
