#ifndef FABLE_ENGINE_CTAVERNGAMEDEF_H
#define FABLE_ENGINE_CTAVERNGAMEDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTavernGameDef = 0x1a8.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CTavernGameDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned long Banter;                                    // +0x28
    unsigned long Greeting;                                  // +0x2c
    unsigned long OptionsInitial;                            // +0x30
    unsigned long OptionsSubsequent;                         // +0x34
    unsigned long Instructions;                              // +0x38
    unsigned long InstructionsPC;                            // +0x3c
    unsigned long Betting;                                   // +0x40
    unsigned long Play;                                      // +0x44
    unsigned long ReactionWin;                               // +0x48
    unsigned long ReactionLose;                              // +0x4c
    unsigned long ReactionDraw;                              // +0x50
    unsigned long ReactionWinNewBestScore;                   // +0x54
    unsigned long FarewellInitial;                           // +0x58
    unsigned long FarewellSubsequent;                        // +0x5c
    unsigned long WinRoundPhrase;                            // +0x60
    unsigned long OutOfTimePhrase;                           // +0x64
    unsigned long NoMoney;                                   // +0x68
    unsigned long GreetingForward;                           // +0x6c
    unsigned long OptionsForward;                            // +0x70
    unsigned long OptionsBack;                               // +0x74
    unsigned long OptionsAlternative;                        // +0x78
    unsigned long InstructionsBack;                          // +0x7c
    unsigned long BettingForward;                            // +0x80
    unsigned long BettingBack;                               // +0x84
    unsigned long ReactionForward;                           // +0x88
    unsigned long FarewellForward;                           // +0x8c
    long          CameraName_TablePos;                       // +0x90 CDefString::TablePos
    unsigned long BoxGraphicL;                               // +0x94
    unsigned long BoxGraphicC;                               // +0x98
    unsigned long BoxGraphicR;                               // +0x9c
    unsigned long ClickToContinue;                           // +0xa0
    unsigned long WinPhrase;                                 // +0xa4
    unsigned long LosePhrase;                                // +0xa8
    unsigned long DrawPhrase;                                // +0xac
    unsigned long NewGame;                                   // +0xb0
    unsigned long BestScore;                                 // +0xb4
    unsigned long CurrentScore;                              // +0xb8
    unsigned long RequiredScore;                             // +0xbc
    unsigned long AdditionalInfo;                            // +0xc0
    unsigned long BlackjackBusted;                           // +0xc4
    unsigned long BlackjackSplit;                            // +0xc8
    unsigned long BlackjackDouble;                           // +0xcc
    unsigned long BlackjackHit;                              // +0xd0
    unsigned long BlackjackStand;                            // +0xd4
    unsigned long BlackjackDealerTakesCard;                  // +0xd8
    unsigned long BlackjackSplitGUI;                         // +0xdc
    unsigned long BlackjackDoubleGUI;                        // +0xe0
    unsigned long BlackjackHitGUI;                           // +0xe4
    unsigned long BlackjackStandGUI;                         // +0xe8
    unsigned long Bet;                                       // +0xec
    unsigned long PlayersMoney;                              // +0xf0
    unsigned long TotalWinnings;                             // +0xf4
    unsigned long Continue;                                  // +0xf8
    unsigned long Quit;                                      // +0xfc
    unsigned long Yes;                                       // +0x100
    unsigned long No;                                        // +0x104
    unsigned long PrizeGiven;                                // +0x108
    unsigned long MoneyBagGraphic;                           // +0x10c
    long          MinBet;                                    // +0x110
    long          MaxBet;                                    // +0x114
    long          BetIncrement;                              // +0x118
    long          ScoreFont_TablePos;                        // +0x11c CDefString::TablePos
    long          TargetFont_TablePos;                       // +0x120 CDefString::TablePos
    long          StatsFont_TablePos;                        // +0x124 CDefString::TablePos
    float         ScoreX;                                    // +0x128
    float         ScoreY;                                    // +0x12c
    float         TargetX;                                   // +0x130
    float         TargetY;                                   // +0x134
    float         BestX;                                     // +0x138
    float         BestY;                                     // +0x13c
    float         AdditionalX;                               // +0x140
    float         AdditionalY;                               // +0x144
    float         BetX;                                      // +0x148
    float         BetY;                                      // +0x14c
    float         MoneyX;                                    // +0x150
    float         MoneyY;                                    // +0x154
    float         WinningsX;                                 // +0x158
    float         WinningsY;                                 // +0x15c
    float         MainBetX;                                  // +0x160
    float         MainBetY;                                  // +0x164
    float         MainMoneyX;                                // +0x168
    float         MainMoneyY;                                // +0x16c
    bool          BestScoreHigh;                             // +0x170
    unsigned char _pad_0x171[0x1];                           // +0x171
    unsigned char _pad_0x172[0x2];                           // +0x172
    unsigned char PrizeScores[0x10];                         // +0x174 vector<CPrizeScoreDef,std::allocator<CPrizeScoreDef>_>
    long          Prize;                                     // +0x184
    long          PrizeRenown;                               // +0x188
    float         MainGameScoreBoxX;                         // +0x18c
    float         MainGameScoreBoxY;                         // +0x190
    float         MainGameScoreBoxWidthXbox;                 // +0x194
    float         MainGameScoreBoxWidthPC;                   // +0x198
    float         MainGameScoreBoxHeight;                    // +0x19c
    bool          DisplayErrata;                             // +0x1a0
    unsigned char _pad_0x1a1[0x3];                           // +0x1a1
    float         PointerPhaseSpeed;                         // +0x1a4
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTavernGameDef) == 0x1a8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Banter) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Greeting) == 0x2c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OptionsInitial) == 0x30);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OptionsSubsequent) == 0x34);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Instructions) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, InstructionsPC) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Betting) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Play) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ReactionWin) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ReactionLose) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ReactionDraw) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ReactionWinNewBestScore) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, FarewellInitial) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, FarewellSubsequent) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, WinRoundPhrase) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OutOfTimePhrase) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, NoMoney) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, GreetingForward) == 0x6c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OptionsForward) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OptionsBack) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, OptionsAlternative) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, InstructionsBack) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BettingForward) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BettingBack) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ReactionForward) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, FarewellForward) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, CameraName_TablePos) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BoxGraphicL) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BoxGraphicC) == 0x98);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BoxGraphicR) == 0x9c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ClickToContinue) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, WinPhrase) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, LosePhrase) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, DrawPhrase) == 0xac);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, NewGame) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BestScore) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, CurrentScore) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, RequiredScore) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, AdditionalInfo) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackBusted) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackSplit) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackDouble) == 0xcc);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackHit) == 0xd0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackStand) == 0xd4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackDealerTakesCard) == 0xd8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackSplitGUI) == 0xdc);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackDoubleGUI) == 0xe0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackHitGUI) == 0xe4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BlackjackStandGUI) == 0xe8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Bet) == 0xec);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, PlayersMoney) == 0xf0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, TotalWinnings) == 0xf4);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Continue) == 0xf8);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Quit) == 0xfc);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Yes) == 0x100);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, No) == 0x104);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, PrizeGiven) == 0x108);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MoneyBagGraphic) == 0x10c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MinBet) == 0x110);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MaxBet) == 0x114);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BetIncrement) == 0x118);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ScoreFont_TablePos) == 0x11c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, TargetFont_TablePos) == 0x120);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, StatsFont_TablePos) == 0x124);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ScoreX) == 0x128);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, ScoreY) == 0x12c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, TargetX) == 0x130);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, TargetY) == 0x134);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BestX) == 0x138);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BestY) == 0x13c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, AdditionalX) == 0x140);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, AdditionalY) == 0x144);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BetX) == 0x148);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BetY) == 0x14c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MoneyX) == 0x150);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MoneyY) == 0x154);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, WinningsX) == 0x158);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, WinningsY) == 0x15c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainBetX) == 0x160);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainBetY) == 0x164);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainMoneyX) == 0x168);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainMoneyY) == 0x16c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, BestScoreHigh) == 0x170);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, PrizeScores) == 0x174);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, Prize) == 0x184);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, PrizeRenown) == 0x188);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainGameScoreBoxX) == 0x18c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainGameScoreBoxY) == 0x190);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainGameScoreBoxWidthXbox) == 0x194);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainGameScoreBoxWidthPC) == 0x198);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, MainGameScoreBoxHeight) == 0x19c);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, DisplayErrata) == 0x1a0);
FABLE_STATIC_ASSERT(offsetof(CTavernGameDef, PointerPhaseSpeed) == 0x1a4);

#endif // FABLE_ENGINE_CTAVERNGAMEDEF_H
