#ifndef FABLE_ENGINE_CTHINGCREATUREDEF_H
#define FABLE_ENGINE_CTHINGCREATUREDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CThingCreatureDef = 0x154.
// Retail evidence: 1 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CThingCreatureDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    unsigned char _pad_0x40[0x4];                            // +0x40
    unsigned char _pad_0x44[0x4];                            // +0x44
    unsigned char _pad_0x48[0x4];                            // +0x48
    unsigned char _pad_0x4c[0x4];                            // +0x4c
    unsigned char _pad_0x50[0x4];                            // +0x50
    unsigned char _pad_0x54[0x4];                            // +0x54
    unsigned char _pad_0x58[0x4];                            // +0x58
    unsigned char _pad_0x5c[0x4];                            // +0x5c
    unsigned char _pad_0x60[0x4];                            // +0x60
    unsigned char _pad_0x64[0x4];                            // +0x64
    unsigned char _pad_0x68[0x4];                            // +0x68
    unsigned char _pad_0x6c[0x4];                            // +0x6c
    unsigned char _pad_0x70[0x4];                            // +0x70
    float         StunTimeMin;                               // +0x74
    float         StunTimeMax;                               // +0x78
    float         StunHealthThreshold;                       // +0x7c
    float         DazedTimeMin;                              // +0x80
    float         DazedTimeMax;                              // +0x84
    long          DazedHealthThreshold;                      // +0x88
    float         NumSecondsToPersistOnDeath;                // +0x8c
    float         MaxSlowWalkingSpeed;                       // +0x90
    float         MaxWalkingSpeed;                           // +0x94
    float         MaxJoggingSpeed;                           // +0x98
    float         MaxRunningSpeed;                           // +0x9c
    float         MaxPushingSpeed;                           // +0xa0
    float         MaxFlyingSpeed;                            // +0xa4
    float         MaxHoverSpeedSlow;                         // +0xa8
    float         MaxHoverSpeedMedium;                       // +0xac
    float         MaxHoverSpeedFast;                         // +0xb0
    float         SpeedRandomisationFactor;                  // +0xb4
    float         MaxAcceleration;                           // +0xb8
    float         HearingRadius;                             // +0xbc
    float         FOV;                                       // +0xc0
    unsigned char Sex[0x4];                                  // +0xc4 ESex
    unsigned char CreatureType[0x4];                         // +0xc8 ECreatureType
    unsigned char NavigatorTypes[0x10];                      // +0xcc vector<ENavigatorType,std::allocator<ENavigatorType>_>
    long          InitialWeaponDef;                          // +0xdc
    long          PrimaryMeleeWeaponDef;                     // +0xe0
    long          SecondaryMeleeWeaponDef;                   // +0xe4
    long          RangedWeaponDef;                           // +0xe8
    long          InitialSheathedWeapon;                     // +0xec
    long          BrainDef;                                  // +0xf0
    unsigned char CreatureInteractionType[0x4];              // +0xf4 ECreatureInteractionType
    unsigned char Property[0x4];                             // +0xf8 EThingCreatureProperty
    float         Damage;                                    // +0xfc
    long          DamageEffectDef;                           // +0x100
    long          StunnedParticle;                           // +0x104
    unsigned long Graphic_BankIndex;                         // +0x108 CEngineGraphic::BankIndex
    float         Graphic_AnimStep;                          // +0x10c CEngineGraphic::AnimStep
    float         Graphic_RenderSizeX;                       // +0x110 CEngineGraphic::RenderSizeX
    bool          Graphic_AdditiveAlpha;                     // +0x114 CEngineGraphic::AdditiveAlpha
    unsigned char Graphic_Type;                              // +0x115 CEngineGraphic::Type
    unsigned long EyeGraphic_BankIndex;                      // +0x116 CEngineGraphic::BankIndex
    float         EyeGraphic_AnimStep;                       // +0x11a CEngineGraphic::AnimStep
    float         EyeGraphic_RenderSizeX;                    // +0x11e CEngineGraphic::RenderSizeX
    bool          EyeGraphic_AdditiveAlpha;                  // +0x122 CEngineGraphic::AdditiveAlpha
    unsigned char EyeGraphic_Type;                           // +0x123 CEngineGraphic::Type
    long          DefaultOwner;                              // +0x124
    unsigned char ControlledMovementType[0x4];               // +0x128 EControlledMovementType
    long          CombatTypeDef;                             // +0x12c
    bool          ResetCombatTypeOnUnsheatheDefaultWeapons;  // +0x130
    unsigned char _pad_0x131[0x3];                           // +0x131
    long          HeroCombatDef;                             // +0x134
    long          HeroCombatPCDef;                           // +0x138
    float         CombatDiameter;                            // +0x13c
    unsigned char DeferHitsIfBehindHitter[0x4];              // +0x140 bitfield group: bool:1
    long          LeaderTypeDef;                             // +0x144
    float         RecoverEvadeHitsPercent;                   // +0x148
    long          DeadBodyDecayEffect;                       // +0x14c
    unsigned char IsIndestructible[0x1];                     // +0x150 bitfield group: bool:1
    unsigned char IsPushedByExplosions[0x3];                 // +0x151 bitfield group: bool:1
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CThingCreatureDef) == 0x154);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, StunTimeMin) == 0x74);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, StunTimeMax) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, StunHealthThreshold) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DazedTimeMin) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DazedTimeMax) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DazedHealthThreshold) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, NumSecondsToPersistOnDeath) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxSlowWalkingSpeed) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxWalkingSpeed) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxJoggingSpeed) == 0x98);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxRunningSpeed) == 0x9c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxPushingSpeed) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxFlyingSpeed) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxHoverSpeedSlow) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxHoverSpeedMedium) == 0xac);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxHoverSpeedFast) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, SpeedRandomisationFactor) == 0xb4);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, MaxAcceleration) == 0xb8);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, HearingRadius) == 0xbc);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, FOV) == 0xc0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Sex) == 0xc4);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, CreatureType) == 0xc8);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, NavigatorTypes) == 0xcc);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, InitialWeaponDef) == 0xdc);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, PrimaryMeleeWeaponDef) == 0xe0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, SecondaryMeleeWeaponDef) == 0xe4);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, RangedWeaponDef) == 0xe8);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, InitialSheathedWeapon) == 0xec);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, BrainDef) == 0xf0);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, CreatureInteractionType) == 0xf4);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Property) == 0xf8);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Damage) == 0xfc);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DamageEffectDef) == 0x100);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, StunnedParticle) == 0x104);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Graphic_BankIndex) == 0x108);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Graphic_AnimStep) == 0x10c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Graphic_RenderSizeX) == 0x110);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Graphic_AdditiveAlpha) == 0x114);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, Graphic_Type) == 0x115);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, EyeGraphic_BankIndex) == 0x116);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, EyeGraphic_AnimStep) == 0x11a);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, EyeGraphic_RenderSizeX) == 0x11e);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, EyeGraphic_AdditiveAlpha) == 0x122);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, EyeGraphic_Type) == 0x123);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DefaultOwner) == 0x124);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, ControlledMovementType) == 0x128);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, CombatTypeDef) == 0x12c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, ResetCombatTypeOnUnsheatheDefaultWeapons) == 0x130);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, HeroCombatDef) == 0x134);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, HeroCombatPCDef) == 0x138);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, CombatDiameter) == 0x13c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DeferHitsIfBehindHitter) == 0x140);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, LeaderTypeDef) == 0x144);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, RecoverEvadeHitsPercent) == 0x148);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, DeadBodyDecayEffect) == 0x14c);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, IsIndestructible) == 0x150);
FABLE_STATIC_ASSERT(offsetof(CThingCreatureDef, IsPushedByExplosions) == 0x151);

#endif // FABLE_ENGINE_CTHINGCREATUREDEF_H
