#ifndef FABLE_ENGINE_CTHINGSHOTDEF_H
#define FABLE_ENGINE_CTHINGSHOTDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CThingShotDef = 0xb0.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CThingShotDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char _pad_0x28[0x4];                            // +0x28
    unsigned char _pad_0x2c[0x4];                            // +0x2c
    unsigned char _pad_0x30[0x4];                            // +0x30
    unsigned char _pad_0x34[0x4];                            // +0x34
    unsigned char _pad_0x38[0x4];                            // +0x38
    unsigned char _pad_0x3c[0x4];                            // +0x3c
    float         Speed;                                     // +0x40
    long          PrimaryEffect;                             // +0x44
    long          PrimaryEffectSound;                        // +0x48
    long          AttachedContinuousEffect;                  // +0x4c
    long          AttachedContinuousSound;                   // +0x50
    bool          UseEndTimeLineOnContinousEffect;           // +0x54
    unsigned char _pad_0x55[0x3];                            // +0x55
    float         HitThingDamage;                            // +0x58
    float         HitThingShieldDamage;                      // +0x5c
    bool          CauseDamage;                               // +0x60
    unsigned char _pad_0x61[0x3];                            // +0x61
    unsigned char ShotDefinitionClassName[0x4];              // +0x64 CDefString
    unsigned char ShotOffsetAngleRange[0x8];                 // +0x68 CFloatRange
    unsigned char ShotOffsetRadiusRange[0x8];                // +0x70 CFloatRange
    long          ExplosionDef;                              // +0x78
    long          GroundExplosionDef;                        // +0x7c
    long          ObjectDef;                                 // +0x80
    bool          LeavesObjectBehind;                        // +0x84
    bool          IsHittableByMelee;                         // +0x85
    bool          IsDeflectedOnHitByMelee;                   // +0x86
    unsigned char _pad_0x87[0x1];                            // +0x87
    float         MeleeHitDeflectionDamageMultiplier;        // +0x88
    bool          FaceMovementDirection;                     // +0x8c
    bool          AllowDeflections;                          // +0x8d
    bool          BounceOnGround;                            // +0x8e
    unsigned char _pad_0x8f[0x1];                            // +0x8f
    float         Bounciness;                                // +0x90
    bool          RotateOnDeflection;                        // +0x94
    bool          IsBlockable;                               // +0x95
    unsigned char _pad_0x96[0x2];                            // +0x96
    unsigned char DamageType[0x4];                           // +0x98 EDamageAttribute
    long          NumSubShots;                               // +0x9c
    long          SubShotType;                               // +0xa0
    float         SubShotCreationTime;                       // +0xa4
    float         SubShotMaxAngle;                           // +0xa8
    bool          RemoveMainShotOnSubShotCreation;           // +0xac
    bool          DoesExplosionDamageCaster;                 // +0xad
    bool          CanHitRollingTargets;                      // +0xae
    bool          PreventSlidingOnCollision;                 // +0xaf
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CThingShotDef) == 0xb0);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, Speed) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, PrimaryEffect) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, PrimaryEffectSound) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, AttachedContinuousEffect) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, AttachedContinuousSound) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, UseEndTimeLineOnContinousEffect) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, HitThingDamage) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, HitThingShieldDamage) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, CauseDamage) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, ShotDefinitionClassName) == 0x64);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, ShotOffsetAngleRange) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, ShotOffsetRadiusRange) == 0x70);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, ExplosionDef) == 0x78);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, GroundExplosionDef) == 0x7c);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, ObjectDef) == 0x80);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, LeavesObjectBehind) == 0x84);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, IsHittableByMelee) == 0x85);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, IsDeflectedOnHitByMelee) == 0x86);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, MeleeHitDeflectionDamageMultiplier) == 0x88);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, FaceMovementDirection) == 0x8c);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, AllowDeflections) == 0x8d);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, BounceOnGround) == 0x8e);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, Bounciness) == 0x90);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, RotateOnDeflection) == 0x94);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, IsBlockable) == 0x95);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, DamageType) == 0x98);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, NumSubShots) == 0x9c);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, SubShotType) == 0xa0);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, SubShotCreationTime) == 0xa4);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, SubShotMaxAngle) == 0xa8);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, RemoveMainShotOnSubShotCreation) == 0xac);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, DoesExplosionDamageCaster) == 0xad);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, CanHitRollingTargets) == 0xae);
FABLE_STATIC_ASSERT(offsetof(CThingShotDef, PreventSlidingOnCollision) == 0xaf);

#endif // FABLE_ENGINE_CTHINGSHOTDEF_H
