#ifndef FABLE_ENGINE_CTRAPDEF_H
#define FABLE_ENGINE_CTRAPDEF_H
// GENERATED by tools/decomp_pipeline/gen_class_headers.py -- do not edit by hand.
// Donor: Ego_r.pdb (ghidra_out/struct_layouts_egor.tsv) sizeof CTrapDef = 0x68.
// Retail evidence: 0 trusted landed function(s); reconciliation 1 conflict(s) in 1 file(s) vs 0 agreeing.
// Members are original Lionhead names; `_pad_*` are unnamed bytes; opaque
// `unsigned char X[N]` members carry their real (composite/template) type in a comment.
#include <stddef.h>
#include "rebuild_abi.h"

#pragma pack(push, 1)
struct CTrapDef {
    void*         __vftable;                                 // +0x00 vptr, or first dword of a flattened base subobject
    unsigned char _pad_0x04[0x4];                            // +0x04
    unsigned char _pad_0x08[0x4];                            // +0x08
    unsigned char _pad_0x0c[0x4];                            // +0x0c
    unsigned char _pad_0x10[0x4];                            // +0x10
    unsigned char _pad_0x14[0x4];                            // +0x14
    unsigned char _pad_0x18[0x4];                            // +0x18
    unsigned char _pad_0x1c[0x4];                            // +0x1c
    unsigned char _pad_0x20[0x4];                            // +0x20
    unsigned char _pad_0x24[0x4];                            // +0x24
    unsigned char Sound[0x10];                               // +0x28 map<CCharString,long,std::less<CCharString>,std::allocator<std::pair<CCharString_const_,long>_>_>
    unsigned char TriggerType[0x4];                          // +0x38 ETrapTriggerType
    unsigned char TrapType[0x4];                             // +0x3c ETrapType
    float         TriggerRadius;                             // +0x40
    unsigned char TriggerHelperName[0x4];                    // +0x44 CDefString
    float         TrapDamage;                                // +0x48
    long          TriggeredCollisionMesh;                    // +0x4c
    long          UntriggeredCollisionMesh;                  // +0x50
    long          ExplosionDefIndex;                         // +0x54
    long          PhysicalObstructionDefIndex;               // +0x58
    long          NumShotsToFireBeforeIdle;                  // +0x5c
    float         SecondsIdle;                               // +0x60
    float         SecondsBetweenShots;                       // +0x64
};
#pragma pack(pop)

FABLE_STATIC_ASSERT(sizeof(CTrapDef) == 0x68);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, __vftable) == 0x0);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, Sound) == 0x28);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TriggerType) == 0x38);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TrapType) == 0x3c);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TriggerRadius) == 0x40);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TriggerHelperName) == 0x44);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TrapDamage) == 0x48);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, TriggeredCollisionMesh) == 0x4c);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, UntriggeredCollisionMesh) == 0x50);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, ExplosionDefIndex) == 0x54);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, PhysicalObstructionDefIndex) == 0x58);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, NumShotsToFireBeforeIdle) == 0x5c);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, SecondsIdle) == 0x60);
FABLE_STATIC_ASSERT(offsetof(CTrapDef, SecondsBetweenShots) == 0x64);

#endif // FABLE_ENGINE_CTRAPDEF_H
